/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s4[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s5[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s7[11] = {0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13};
static const casadi_int casadi_s8[11] = {0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28};
static const casadi_int casadi_s9[11] = {0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37};
static const casadi_int casadi_s10[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s13[11] = {4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32};
static const casadi_int casadi_s14[11] = {1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38};
static const casadi_int casadi_s15[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s16[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s17[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s18[11] = {8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36};
static const casadi_int casadi_s19[11] = {2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39};
static const casadi_int casadi_s20[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s21[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s22[61] = {17, 17, 0, 4, 8, 12, 16, 19, 22, 25, 25, 25, 25, 29, 33, 37, 41, 41, 41, 41, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13, 10, 11, 12, 13};
static const casadi_int casadi_s23[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s24[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s25[3] = {0, 0, 0};
static const casadi_int casadi_s26[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s27[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s28[20] = {0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[4],i2[],i3[17])->(o0,o1[17],o2[17x17,41nz],o3[],o4[0x17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55, *w23=w+58, *w24=w+67, *w25=w+71, *w26=w+75, *w27=w+79, *w28=w+95, *w29=w+99, *w30=w+103, *w31=w+107, *w32=w+110, *w33=w+113, *w34=w+116, *w35=w+119, *w36=w+128, *w37=w+144, *w38=w+147, *w39=w+156, *w40=w+159, *w41=w+162, w42, w43, w44, w45, w46, w47, w48, *w49=w+172, w50, w51, w52, w53, w54, w55, *w56=w+187, *w57=w+228, *w58=w+232, *w62=w+241, *w63=w+245, w64, w65, *w66=w+251, w67, w68, *w69=w+257, *w70=w+260, *w71=w+263, w72, w73, w74, w75, w76, w77, w78, w79, w80, w81, w82, *w83=w+277, *w84=w+288, *w85=w+290, *w86=w+298;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 1 */
  w2 = 1.;
  /* #40: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #41: @2 = 1 */
  w2 = 1.;
  /* #42: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #43: @2 = 1 */
  w2 = 1.;
  /* #44: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #45: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #46: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #47: @2 = 0 */
  w2 = 0.;
  /* #48: @24 = zeros(1x4) */
  casadi_clear(w24, 4);
  /* #49: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #50: @4 = input[1][1] */
  w4 = arg[1] ? arg[1][1] : 0;
  /* #51: @5 = input[1][2] */
  w5 = arg[1] ? arg[1][2] : 0;
  /* #52: @6 = input[1][3] */
  w6 = arg[1] ? arg[1][3] : 0;
  /* #53: @25 = vertcat(@3, @4, @5, @6) */
  rr=w25;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #54: @26 = @25' */
  casadi_copy(w25, 4, w26);
  /* #55: @27 = zeros(4x4) */
  casadi_clear(w27, 16);
  /* #56: @3 = 0.01 */
  w3 = 1.0000000000000000e-02;
  /* #57: (@27[0] = @3) */
  for (rr=w27+0, ss=(&w3); rr!=w27+1; rr+=1) *rr = *ss++;
  /* #58: @3 = 0.01 */
  w3 = 1.0000000000000000e-02;
  /* #59: (@27[5] = @3) */
  for (rr=w27+5, ss=(&w3); rr!=w27+6; rr+=1) *rr = *ss++;
  /* #60: @3 = 0.01 */
  w3 = 1.0000000000000000e-02;
  /* #61: (@27[10] = @3) */
  for (rr=w27+10, ss=(&w3); rr!=w27+11; rr+=1) *rr = *ss++;
  /* #62: @3 = 0.01 */
  w3 = 1.0000000000000000e-02;
  /* #63: (@27[15] = @3) */
  for (rr=w27+15, ss=(&w3); rr!=w27+16; rr+=1) *rr = *ss++;
  /* #64: @24 = mac(@26,@27,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #65: @2 = mac(@24,@25,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #66: @0 = (@0+@2) */
  w0 += w2;
  /* #67: @2 = 0 */
  w2 = 0.;
  /* #68: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #69: @9 = (-@9) */
  w9 = (- w9 );
  /* #70: @10 = (-@10) */
  w10 = (- w10 );
  /* #71: @11 = (-@11) */
  w11 = (- w11 );
  /* #72: @26 = vertcat(@8, @9, @10, @11) */
  rr=w26;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #73: @28 = @21[6:10] */
  for (rr=w28, ss=w21+6; ss!=w21+10; ss+=1) *rr++ = *ss;
  /* #74: @8 = ||@28||_F */
  w8 = sqrt(casadi_dot(4, w28, w28));
  /* #75: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w8;
  /* #76: {@9, @10, @11, @3} = vertsplit(@26) */
  w9 = w26[0];
  w10 = w26[1];
  w11 = w26[2];
  w3 = w26[3];
  /* #77: @29 = @19[6:10] */
  for (rr=w29, ss=w19+6; ss!=w19+10; ss+=1) *rr++ = *ss;
  /* #78: {@4, @5, @6, @7} = vertsplit(@29) */
  w4 = w29[0];
  w5 = w29[1];
  w6 = w29[2];
  w7 = w29[3];
  /* #79: @12 = (@9*@4) */
  w12  = (w9*w4);
  /* #80: @13 = (@10*@5) */
  w13  = (w10*w5);
  /* #81: @12 = (@12-@13) */
  w12 -= w13;
  /* #82: @13 = (@11*@6) */
  w13  = (w11*w6);
  /* #83: @12 = (@12-@13) */
  w12 -= w13;
  /* #84: @13 = (@3*@7) */
  w13  = (w3*w7);
  /* #85: @12 = (@12-@13) */
  w12 -= w13;
  /* #86: @13 = 0 */
  w13 = 0.;
  /* #87: @13 = (@12<@13) */
  w13  = (w12<w13);
  /* #88: @14 = (@9*@5) */
  w14  = (w9*w5);
  /* #89: @15 = (@10*@4) */
  w15  = (w10*w4);
  /* #90: @14 = (@14+@15) */
  w14 += w15;
  /* #91: @15 = (@11*@7) */
  w15  = (w11*w7);
  /* #92: @14 = (@14+@15) */
  w14 += w15;
  /* #93: @15 = (@3*@6) */
  w15  = (w3*w6);
  /* #94: @14 = (@14-@15) */
  w14 -= w15;
  /* #95: @15 = (@9*@6) */
  w15  = (w9*w6);
  /* #96: @16 = (@10*@7) */
  w16  = (w10*w7);
  /* #97: @15 = (@15-@16) */
  w15 -= w16;
  /* #98: @16 = (@11*@4) */
  w16  = (w11*w4);
  /* #99: @15 = (@15+@16) */
  w15 += w16;
  /* #100: @16 = (@3*@5) */
  w16  = (w3*w5);
  /* #101: @15 = (@15+@16) */
  w15 += w16;
  /* #102: @9 = (@9*@7) */
  w9 *= w7;
  /* #103: @10 = (@10*@6) */
  w10 *= w6;
  /* #104: @9 = (@9+@10) */
  w9 += w10;
  /* #105: @11 = (@11*@5) */
  w11 *= w5;
  /* #106: @9 = (@9-@11) */
  w9 -= w11;
  /* #107: @3 = (@3*@4) */
  w3 *= w4;
  /* #108: @9 = (@9+@3) */
  w9 += w3;
  /* #109: @29 = vertcat(@12, @14, @15, @9) */
  rr=w29;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w9;
  /* #110: @30 = (-@29) */
  for (i=0, rr=w30, cs=w29; i<4; ++i) *rr++ = (- *cs++ );
  /* #111: @30 = (@13?@30:0) */
  for (i=0, rr=w30, cs=w30; i<4; ++i) (*rr++)  = (w13?(*cs++):0);
  /* #112: @12 = (!@13) */
  w12 = (! w13 );
  /* #113: @29 = (@12?@29:0) */
  for (i=0, rr=w29, cs=w29; i<4; ++i) (*rr++)  = (w12?(*cs++):0);
  /* #114: @30 = (@30+@29) */
  for (i=0, rr=w30, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #115: @31 = @30[1:4] */
  for (rr=w31, ss=w30+1; ss!=w30+4; ss+=1) *rr++ = *ss;
  /* #116: @32 = (2.*@31) */
  for (i=0, rr=w32, cs=w31; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #117: @14 = ||@31||_F */
  w14 = sqrt(casadi_dot(3, w31, w31));
  /* #118: @15 = @30[0] */
  for (rr=(&w15), ss=w30+0; ss!=w30+1; ss+=1) *rr++ = *ss;
  /* #119: @9 = atan2(@14,@15) */
  w9  = atan2(w14,w15);
  /* #120: @33 = (@32*@9) */
  for (i=0, rr=w33, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w9);
  /* #121: @33 = (@33/@14) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) /= w14;
  /* #122: @34 = @33' */
  casadi_copy(w33, 3, w34);
  /* #123: @35 = zeros(3x3) */
  casadi_clear(w35, 9);
  /* #124: @3 = 1 */
  w3 = 1.;
  /* #125: (@35[0] = @3) */
  for (rr=w35+0, ss=(&w3); rr!=w35+1; rr+=1) *rr = *ss++;
  /* #126: @3 = 1 */
  w3 = 1.;
  /* #127: (@35[4] = @3) */
  for (rr=w35+4, ss=(&w3); rr!=w35+5; rr+=1) *rr = *ss++;
  /* #128: @3 = 1 */
  w3 = 1.;
  /* #129: (@35[8] = @3) */
  for (rr=w35+8, ss=(&w3); rr!=w35+9; rr+=1) *rr = *ss++;
  /* #130: @22 = mac(@34,@35,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #131: @2 = mac(@22,@33,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #132: @0 = (@0+@2) */
  w0 += w2;
  /* #133: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #134: @24 = @24' */
  /* #135: @30 = zeros(1x4) */
  casadi_clear(w30, 4);
  /* #136: @25 = @25' */
  /* #137: @36 = @27' */
  for (i=0, rr=w36, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #138: @30 = mac(@25,@36,@30) */
  for (i=0, rr=w30; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w25+j, tt=w36+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #139: @30 = @30' */
  /* #140: @24 = (@24+@30) */
  for (i=0, rr=w24, cs=w30; i<4; ++i) (*rr++) += (*cs++);
  /* #141: {@0, @2, @3, @11} = vertsplit(@24) */
  w0 = w24[0];
  w2 = w24[1];
  w3 = w24[2];
  w11 = w24[3];
  /* #142: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #143: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  /* #144: output[1][2] = @3 */
  if (res[1]) res[1][2] = w3;
  /* #145: output[1][3] = @11 */
  if (res[1]) res[1][3] = w11;
  /* #146: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #147: @24 = (@26/@8) */
  for (i=0, rr=w24, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)/w8);
  /* #148: @30 = (-@24) */
  for (i=0, rr=w30, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #149: @11 = 1 */
  w11 = 1.;
  /* #150: @11 = (@12?@11:0) */
  w11  = (w12?w11:0);
  /* #151: @25 = zeros(4x1) */
  casadi_clear(w25, 4);
  /* #152: @3 = sq(@14) */
  w3 = casadi_sq( w14 );
  /* #153: @2 = sq(@15) */
  w2 = casadi_sq( w15 );
  /* #154: @3 = (@3+@2) */
  w3 += w2;
  /* #155: @2 = (@14/@3) */
  w2  = (w14/w3);
  /* #156: @22 = @22' */
  /* #157: @34 = zeros(1x3) */
  casadi_clear(w34, 3);
  /* #158: @37 = @33' */
  casadi_copy(w33, 3, w37);
  /* #159: @38 = @35' */
  for (i=0, rr=w38, cs=w35; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #160: @34 = mac(@37,@38,@34) */
  for (i=0, rr=w34; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #161: @34 = @34' */
  /* #162: @22 = (@22+@34) */
  for (i=0, rr=w22, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #163: @34 = (@22/@14) */
  for (i=0, rr=w34, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #164: @0 = dot(@32, @34) */
  w0 = casadi_dot(3, w32, w34);
  /* #165: @10 = (@2*@0) */
  w10  = (w2*w0);
  /* #166: @10 = (-@10) */
  w10 = (- w10 );
  /* #167: (@25[0] += @10) */
  for (rr=w25+0, ss=(&w10); rr!=w25+1; rr+=1) *rr += *ss++;
  /* #168: @37 = (@33/@14) */
  for (i=0, rr=w37, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #169: @39 = (-@37) */
  for (i=0, rr=w39, cs=w37; i<3; ++i) *rr++ = (- *cs++ );
  /* #170: @10 = dot(@39, @22) */
  w10 = casadi_dot(3, w39, w22);
  /* #171: @16 = (@15/@3) */
  w16  = (w15/w3);
  /* #172: @17 = (@16*@0) */
  w17  = (w16*w0);
  /* #173: @10 = (@10+@17) */
  w10 += w17;
  /* #174: @10 = (@10/@14) */
  w10 /= w14;
  /* #175: @40 = (@10*@31) */
  for (i=0, rr=w40, cs=w31; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #176: @41 = (@9*@34) */
  for (i=0, rr=w41, cs=w34; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #177: @41 = (2.*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #178: @40 = (@40+@41) */
  for (i=0, rr=w40, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #179: (@25[1:4] += @40) */
  for (rr=w25+1, ss=w40; rr!=w25+4; rr+=1) *rr += *ss++;
  /* #180: @29 = (@11*@25) */
  for (i=0, rr=w29, cs=w25; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #181: @17 = 1 */
  w17 = 1.;
  /* #182: @17 = (@13?@17:0) */
  w17  = (w13?w17:0);
  /* #183: @25 = (@17*@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #184: @29 = (@29-@25) */
  for (i=0, rr=w29, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #185: {@18, @42, @43, @44} = vertsplit(@29) */
  w18 = w29[0];
  w42 = w29[1];
  w43 = w29[2];
  w44 = w29[3];
  /* #186: @45 = (@7*@44) */
  w45  = (w7*w44);
  /* #187: @46 = (@6*@43) */
  w46  = (w6*w43);
  /* #188: @45 = (@45+@46) */
  w45 += w46;
  /* #189: @46 = (@5*@42) */
  w46  = (w5*w42);
  /* #190: @45 = (@45+@46) */
  w45 += w46;
  /* #191: @46 = (@4*@18) */
  w46  = (w4*w18);
  /* #192: @45 = (@45+@46) */
  w45 += w46;
  /* #193: @46 = (@6*@44) */
  w46  = (w6*w44);
  /* #194: @47 = (@7*@43) */
  w47  = (w7*w43);
  /* #195: @46 = (@46-@47) */
  w46 -= w47;
  /* #196: @47 = (@4*@42) */
  w47  = (w4*w42);
  /* #197: @46 = (@46+@47) */
  w46 += w47;
  /* #198: @47 = (@5*@18) */
  w47  = (w5*w18);
  /* #199: @46 = (@46-@47) */
  w46 -= w47;
  /* #200: @47 = (@4*@43) */
  w47  = (w4*w43);
  /* #201: @48 = (@5*@44) */
  w48  = (w5*w44);
  /* #202: @47 = (@47-@48) */
  w47 -= w48;
  /* #203: @48 = (@7*@42) */
  w48  = (w7*w42);
  /* #204: @47 = (@47+@48) */
  w47 += w48;
  /* #205: @48 = (@6*@18) */
  w48  = (w6*w18);
  /* #206: @47 = (@47-@48) */
  w47 -= w48;
  /* #207: @44 = (@4*@44) */
  w44  = (w4*w44);
  /* #208: @43 = (@5*@43) */
  w43  = (w5*w43);
  /* #209: @44 = (@44+@43) */
  w44 += w43;
  /* #210: @42 = (@6*@42) */
  w42  = (w6*w42);
  /* #211: @44 = (@44-@42) */
  w44 -= w42;
  /* #212: @18 = (@7*@18) */
  w18  = (w7*w18);
  /* #213: @44 = (@44-@18) */
  w44 -= w18;
  /* #214: @29 = vertcat(@45, @46, @47, @44) */
  rr=w29;
  *rr++ = w45;
  *rr++ = w46;
  *rr++ = w47;
  *rr++ = w44;
  /* #215: @45 = dot(@30, @29) */
  w45 = casadi_dot(4, w30, w29);
  /* #216: @45 = (@45/@8) */
  w45 /= w8;
  /* #217: @25 = (@45*@28) */
  for (i=0, rr=w25, cs=w28; i<4; ++i) (*rr++)  = (w45*(*cs++));
  /* #218: (@21[6:10] += @25) */
  for (rr=w21+6, ss=w25; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #219: @1 = @1' */
  /* #220: @40 = zeros(1x3) */
  casadi_clear(w40, 3);
  /* #221: @20 = @20' */
  /* #222: @49 = @23' */
  for (i=0, rr=w49, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #223: @40 = mac(@20,@49,@40) */
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w49+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #224: @40 = @40' */
  /* #225: @1 = (@1+@40) */
  for (i=0, rr=w1, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #226: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #227: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #228: {@46, @47, @44, @18, @42, @43, @48, @50, @51, @52, @53, @54, @55} = vertsplit(@21) */
  w46 = w21[0];
  w47 = w21[1];
  w44 = w21[2];
  w18 = w21[3];
  w42 = w21[4];
  w43 = w21[5];
  w48 = w21[6];
  w50 = w21[7];
  w51 = w21[8];
  w52 = w21[9];
  w53 = w21[10];
  w54 = w21[11];
  w55 = w21[12];
  /* #229: output[1][4] = @46 */
  if (res[1]) res[1][4] = w46;
  /* #230: output[1][5] = @47 */
  if (res[1]) res[1][5] = w47;
  /* #231: output[1][6] = @44 */
  if (res[1]) res[1][6] = w44;
  /* #232: output[1][7] = @18 */
  if (res[1]) res[1][7] = w18;
  /* #233: output[1][8] = @42 */
  if (res[1]) res[1][8] = w42;
  /* #234: output[1][9] = @43 */
  if (res[1]) res[1][9] = w43;
  /* #235: @25 = (@29/@8) */
  for (i=0, rr=w25, cr=w29; i<4; ++i) (*rr++)  = ((*cr++)/w8);
  /* #236: {@43, @42, @18, @44} = vertsplit(@25) */
  w43 = w25[0];
  w42 = w25[1];
  w18 = w25[2];
  w44 = w25[3];
  /* #237: @43 = (@43+@48) */
  w43 += w48;
  /* #238: output[1][10] = @43 */
  if (res[1]) res[1][10] = w43;
  /* #239: @50 = (@50-@42) */
  w50 -= w42;
  /* #240: output[1][11] = @50 */
  if (res[1]) res[1][11] = w50;
  /* #241: @51 = (@51-@18) */
  w51 -= w18;
  /* #242: output[1][12] = @51 */
  if (res[1]) res[1][12] = w51;
  /* #243: @52 = (@52-@44) */
  w52 -= w44;
  /* #244: output[1][13] = @52 */
  if (res[1]) res[1][13] = w52;
  /* #245: output[1][14] = @53 */
  if (res[1]) res[1][14] = w53;
  /* #246: output[1][15] = @54 */
  if (res[1]) res[1][15] = w54;
  /* #247: output[1][16] = @55 */
  if (res[1]) res[1][16] = w55;
  /* #248: @56 = zeros(17x17,41nz) */
  casadi_clear(w56, 41);
  /* #249: @57 = zeros(1x4) */
  casadi_clear(w57, 4);
  /* #250: @58 = ones(17x1,9nz) */
  casadi_fill(w58, 9, 1.);
  /* #251: {@55, NULL, NULL, NULL, @54, NULL, NULL, NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@58) */
  w55 = w58[0];
  w54 = w58[1];
  w53 = w58[5];
  /* #252: @59 = 00 */
  /* #253: @60 = 00 */
  /* #254: @61 = 00 */
  /* #255: @52 = vertcat(@55, @59, @60, @61) */
  rr=(&w52);
  *rr++ = w55;
  /* #256: @55 = @52' */
  casadi_copy((&w52), 1, (&w55));
  /* #257: @57 = mac(@55,@27,@57) */
  casadi_mtimes((&w55), casadi_s2, w27, casadi_s1, w57, casadi_s0, w, 0);
  /* #258: @57 = @57' */
  /* #259: @62 = zeros(1x4) */
  casadi_clear(w62, 4);
  /* #260: @52 = @52' */
  /* #261: @62 = mac(@52,@36,@62) */
  casadi_mtimes((&w52), casadi_s2, w36, casadi_s1, w62, casadi_s0, w, 0);
  /* #262: @62 = @62' */
  /* #263: @57 = (@57+@62) */
  for (i=0, rr=w57, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #264: {@52, @55, @44, @51} = vertsplit(@57) */
  w52 = w57[0];
  w55 = w57[1];
  w44 = w57[2];
  w51 = w57[3];
  /* #265: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #266: @57 = zeros(4x1) */
  casadi_clear(w57, 4);
  /* #267: @18 = 1 */
  w18 = 1.;
  /* #268: @12 = (@12?@18:0) */
  w12  = (w12?w18:0);
  /* #269: @59 = 00 */
  /* #270: @60 = 00 */
  /* #271: @61 = 00 */
  /* #272: @18 = vertcat(@53, @59, @60, @61) */
  rr=(&w18);
  *rr++ = w53;
  /* #273: @18 = (@18/@8) */
  w18 /= w8;
  /* #274: @62 = dense(@18) */
  casadi_densify((&w18), casadi_s3, w62, 0);
  /* #275: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w8;
  /* #276: @18 = project(@28) */
  casadi_sparsify(w28, (&w18), casadi_s3, 0);
  /* #277: @50 = @53[0] */
  for (rr=(&w50), ss=(&w53)+0; ss!=(&w53)+1; ss+=1) *rr++ = *ss;
  /* #278: @53 = dot(@18, @50) */
  w53 = casadi_dot(1, (&w18), (&w50));
  /* #279: @53 = (@53/@8) */
  w53 /= w8;
  /* #280: @63 = (@26*@53) */
  for (i=0, rr=w63, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #281: @62 = (@62-@63) */
  for (i=0, rr=w62, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #282: {@18, @42, @43, @48} = vertsplit(@62) */
  w18 = w62[0];
  w42 = w62[1];
  w43 = w62[2];
  w48 = w62[3];
  /* #283: @47 = (@4*@18) */
  w47  = (w4*w18);
  /* #284: @46 = (@5*@42) */
  w46  = (w5*w42);
  /* #285: @47 = (@47-@46) */
  w47 -= w46;
  /* #286: @46 = (@6*@43) */
  w46  = (w6*w43);
  /* #287: @47 = (@47-@46) */
  w47 -= w46;
  /* #288: @46 = (@7*@48) */
  w46  = (w7*w48);
  /* #289: @47 = (@47-@46) */
  w47 -= w46;
  /* #290: @46 = (@5*@18) */
  w46  = (w5*w18);
  /* #291: @64 = (@4*@42) */
  w64  = (w4*w42);
  /* #292: @46 = (@46+@64) */
  w46 += w64;
  /* #293: @64 = (@7*@43) */
  w64  = (w7*w43);
  /* #294: @46 = (@46+@64) */
  w46 += w64;
  /* #295: @64 = (@6*@48) */
  w64  = (w6*w48);
  /* #296: @46 = (@46-@64) */
  w46 -= w64;
  /* #297: @64 = (@6*@18) */
  w64  = (w6*w18);
  /* #298: @65 = (@7*@42) */
  w65  = (w7*w42);
  /* #299: @64 = (@64-@65) */
  w64 -= w65;
  /* #300: @65 = (@4*@43) */
  w65  = (w4*w43);
  /* #301: @64 = (@64+@65) */
  w64 += w65;
  /* #302: @65 = (@5*@48) */
  w65  = (w5*w48);
  /* #303: @64 = (@64+@65) */
  w64 += w65;
  /* #304: @18 = (@7*@18) */
  w18  = (w7*w18);
  /* #305: @42 = (@6*@42) */
  w42  = (w6*w42);
  /* #306: @18 = (@18+@42) */
  w18 += w42;
  /* #307: @43 = (@5*@43) */
  w43  = (w5*w43);
  /* #308: @18 = (@18-@43) */
  w18 -= w43;
  /* #309: @48 = (@4*@48) */
  w48  = (w4*w48);
  /* #310: @18 = (@18+@48) */
  w18 += w48;
  /* #311: @63 = vertcat(@47, @46, @64, @18) */
  rr=w63;
  *rr++ = w47;
  *rr++ = w46;
  *rr++ = w64;
  *rr++ = w18;
  /* #312: @66 = (@12*@63) */
  for (i=0, rr=w66, cs=w63; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #313: @47 = 1 */
  w47 = 1.;
  /* #314: @13 = (@13?@47:0) */
  w13  = (w13?w47:0);
  /* #315: @63 = (@13*@63) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #316: @66 = (@66-@63) */
  for (i=0, rr=w66, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #317: @1 = @66[1:4] */
  for (rr=w1, ss=w66+1; ss!=w66+4; ss+=1) *rr++ = *ss;
  /* #318: @47 = dot(@31, @1) */
  w47 = casadi_dot(3, w31, w1);
  /* #319: @47 = (@47/@14) */
  w47 /= w14;
  /* #320: @46 = (@47/@3) */
  w46  = (w47/w3);
  /* #321: @64 = (@2/@3) */
  w64  = (w2/w3);
  /* #322: @18 = (2.*@14) */
  w18 = (2.* w14 );
  /* #323: @48 = (@18*@47) */
  w48  = (w18*w47);
  /* #324: @43 = (2.*@15) */
  w43 = (2.* w15 );
  /* #325: @42 = @66[0] */
  for (rr=(&w42), ss=w66+0; ss!=w66+1; ss+=1) *rr++ = *ss;
  /* #326: @65 = (@43*@42) */
  w65  = (w43*w42);
  /* #327: @48 = (@48+@65) */
  w48 += w65;
  /* #328: @65 = (@64*@48) */
  w65  = (w64*w48);
  /* #329: @46 = (@46-@65) */
  w46 -= w65;
  /* #330: @46 = (@0*@46) */
  w46  = (w0*w46);
  /* #331: @40 = zeros(1x3) */
  casadi_clear(w40, 3);
  /* #332: @20 = (2.*@1) */
  for (i=0, rr=w20, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #333: @41 = (@9*@20) */
  for (i=0, rr=w41, cs=w20; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #334: @65 = sq(@14) */
  w65 = casadi_sq( w14 );
  /* #335: @67 = sq(@15) */
  w67 = casadi_sq( w15 );
  /* #336: @65 = (@65+@67) */
  w65 += w67;
  /* #337: @15 = (@15/@65) */
  w15 /= w65;
  /* #338: @67 = (@15*@47) */
  w67  = (w15*w47);
  /* #339: @65 = (@14/@65) */
  w65  = (w14/w65);
  /* #340: @68 = (@65*@42) */
  w68  = (w65*w42);
  /* #341: @67 = (@67-@68) */
  w67 -= w68;
  /* #342: @69 = (@32*@67) */
  for (i=0, rr=w69, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w67);
  /* #343: @41 = (@41+@69) */
  for (i=0, rr=w41, cs=w69; i<3; ++i) (*rr++) += (*cs++);
  /* #344: @41 = (@41/@14) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w14;
  /* #345: @33 = (@33/@14) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) /= w14;
  /* #346: @69 = (@33*@47) */
  for (i=0, rr=w69, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #347: @41 = (@41-@69) */
  for (i=0, rr=w41, cs=w69; i<3; ++i) (*rr++) -= (*cs++);
  /* #348: @69 = @41' */
  casadi_copy(w41, 3, w69);
  /* #349: @40 = mac(@69,@35,@40) */
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w69+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #350: @40 = @40' */
  /* #351: @69 = zeros(1x3) */
  casadi_clear(w69, 3);
  /* #352: @70 = @41' */
  casadi_copy(w41, 3, w70);
  /* #353: @69 = mac(@70,@38,@69) */
  for (i=0, rr=w69; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w70+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #354: @69 = @69' */
  /* #355: @40 = (@40+@69) */
  for (i=0, rr=w40, cs=w69; i<3; ++i) (*rr++) += (*cs++);
  /* #356: @69 = (@40/@14) */
  for (i=0, rr=w69, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #357: @70 = (@34/@14) */
  for (i=0, rr=w70, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #358: @71 = (@70*@47) */
  for (i=0, rr=w71, cr=w70; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #359: @69 = (@69-@71) */
  for (i=0, rr=w69, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  /* #360: @68 = dot(@32, @69) */
  w68 = casadi_dot(3, w32, w69);
  /* #361: @72 = dot(@20, @34) */
  w72 = casadi_dot(3, w20, w34);
  /* #362: @68 = (@68+@72) */
  w68 += w72;
  /* #363: @72 = (@2*@68) */
  w72  = (w2*w68);
  /* #364: @46 = (@46+@72) */
  w46 += w72;
  /* #365: @46 = (-@46) */
  w46 = (- w46 );
  /* #366: (@57[0] += @46) */
  for (rr=w57+0, ss=(&w46); rr!=w57+1; rr+=1) *rr += *ss++;
  /* #367: @46 = dot(@39, @40) */
  w46 = casadi_dot(3, w39, w40);
  /* #368: @41 = (@41/@14) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w14;
  /* #369: @37 = (@37/@14) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w14;
  /* #370: @40 = (@37*@47) */
  for (i=0, rr=w40, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #371: @41 = (@41-@40) */
  for (i=0, rr=w41, cs=w40; i<3; ++i) (*rr++) -= (*cs++);
  /* #372: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #373: @72 = dot(@41, @22) */
  w72 = casadi_dot(3, w41, w22);
  /* #374: @46 = (@46+@72) */
  w46 += w72;
  /* #375: @42 = (@42/@3) */
  w42 /= w3;
  /* #376: @72 = (@16/@3) */
  w72  = (w16/w3);
  /* #377: @48 = (@72*@48) */
  w48  = (w72*w48);
  /* #378: @42 = (@42-@48) */
  w42 -= w48;
  /* #379: @42 = (@0*@42) */
  w42  = (w0*w42);
  /* #380: @68 = (@16*@68) */
  w68  = (w16*w68);
  /* #381: @42 = (@42+@68) */
  w42 += w68;
  /* #382: @46 = (@46+@42) */
  w46 += w42;
  /* #383: @46 = (@46/@14) */
  w46 /= w14;
  /* #384: @42 = (@10/@14) */
  w42  = (w10/w14);
  /* #385: @47 = (@42*@47) */
  w47  = (w42*w47);
  /* #386: @46 = (@46-@47) */
  w46 -= w47;
  /* #387: @41 = (@31*@46) */
  for (i=0, rr=w41, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w46);
  /* #388: @1 = (@10*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #389: @41 = (@41+@1) */
  for (i=0, rr=w41, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #390: @1 = (@34*@67) */
  for (i=0, rr=w1, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w67);
  /* #391: @69 = (@9*@69) */
  for (i=0, rr=w69, cs=w69; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #392: @1 = (@1+@69) */
  for (i=0, rr=w1, cs=w69; i<3; ++i) (*rr++) += (*cs++);
  /* #393: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #394: @41 = (@41+@1) */
  for (i=0, rr=w41, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #395: (@57[1:4] += @41) */
  for (rr=w57+1, ss=w41; rr!=w57+4; rr+=1) *rr += *ss++;
  /* #396: @66 = (@11*@57) */
  for (i=0, rr=w66, cs=w57; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #397: @57 = (@17*@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #398: @66 = (@66-@57) */
  for (i=0, rr=w66, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #399: {@67, @46, @47, @68} = vertsplit(@66) */
  w67 = w66[0];
  w46 = w66[1];
  w47 = w66[2];
  w68 = w66[3];
  /* #400: @48 = (@7*@68) */
  w48  = (w7*w68);
  /* #401: @73 = (@6*@47) */
  w73  = (w6*w47);
  /* #402: @48 = (@48+@73) */
  w48 += w73;
  /* #403: @73 = (@5*@46) */
  w73  = (w5*w46);
  /* #404: @48 = (@48+@73) */
  w48 += w73;
  /* #405: @73 = (@4*@67) */
  w73  = (w4*w67);
  /* #406: @48 = (@48+@73) */
  w48 += w73;
  /* #407: @73 = (@6*@68) */
  w73  = (w6*w68);
  /* #408: @74 = (@7*@47) */
  w74  = (w7*w47);
  /* #409: @73 = (@73-@74) */
  w73 -= w74;
  /* #410: @74 = (@4*@46) */
  w74  = (w4*w46);
  /* #411: @73 = (@73+@74) */
  w73 += w74;
  /* #412: @74 = (@5*@67) */
  w74  = (w5*w67);
  /* #413: @73 = (@73-@74) */
  w73 -= w74;
  /* #414: @74 = (@4*@47) */
  w74  = (w4*w47);
  /* #415: @75 = (@5*@68) */
  w75  = (w5*w68);
  /* #416: @74 = (@74-@75) */
  w74 -= w75;
  /* #417: @75 = (@7*@46) */
  w75  = (w7*w46);
  /* #418: @74 = (@74+@75) */
  w74 += w75;
  /* #419: @75 = (@6*@67) */
  w75  = (w6*w67);
  /* #420: @74 = (@74-@75) */
  w74 -= w75;
  /* #421: @68 = (@4*@68) */
  w68  = (w4*w68);
  /* #422: @47 = (@5*@47) */
  w47  = (w5*w47);
  /* #423: @68 = (@68+@47) */
  w68 += w47;
  /* #424: @46 = (@6*@46) */
  w46  = (w6*w46);
  /* #425: @68 = (@68-@46) */
  w68 -= w46;
  /* #426: @67 = (@7*@67) */
  w67  = (w7*w67);
  /* #427: @68 = (@68-@67) */
  w68 -= w67;
  /* #428: @66 = vertcat(@48, @73, @74, @68) */
  rr=w66;
  *rr++ = w48;
  *rr++ = w73;
  *rr++ = w74;
  *rr++ = w68;
  /* #429: @48 = dot(@30, @66) */
  w48 = casadi_dot(4, w30, w66);
  /* #430: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w8;
  /* #431: @24 = (@24/@8) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w8;
  /* #432: @57 = (@24*@53) */
  for (i=0, rr=w57, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #433: @62 = (@62-@57) */
  for (i=0, rr=w62, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #434: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) *rr++ = (- *cs++ );
  /* #435: @73 = dot(@62, @29) */
  w73 = casadi_dot(4, w62, w29);
  /* #436: @48 = (@48+@73) */
  w48 += w73;
  /* #437: @48 = (@48/@8) */
  w48 /= w8;
  /* #438: @73 = (@45/@8) */
  w73  = (w45/w8);
  /* #439: @74 = (@73*@53) */
  w74  = (w73*w53);
  /* #440: @48 = (@48-@74) */
  w48 -= w74;
  /* #441: @62 = (@28*@48) */
  for (i=0, rr=w62, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w48);
  /* #442: @50 = (@45*@50) */
  w50  = (w45*w50);
  /* #443: @57 = dense(@50) */
  casadi_densify((&w50), casadi_s3, w57, 0);
  /* #444: @62 = (@62+@57) */
  for (i=0, rr=w62, cs=w57; i<4; ++i) (*rr++) += (*cs++);
  /* #445: (@21[6:10] += @62) */
  for (rr=w21+6, ss=w62; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #446: @41 = zeros(1x3) */
  casadi_clear(w41, 3);
  /* #447: @50 = @54[0] */
  for (rr=(&w50), ss=(&w54)+0; ss!=(&w54)+1; ss+=1) *rr++ = *ss;
  /* #448: @50 = (-@50) */
  w50 = (- w50 );
  /* #449: @54 = @50' */
  casadi_copy((&w50), 1, (&w54));
  /* #450: @41 = mac(@54,@23,@41) */
  casadi_mtimes((&w54), casadi_s6, w23, casadi_s5, w41, casadi_s4, w, 0);
  /* #451: @41 = @41' */
  /* #452: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #453: @50 = @50' */
  /* #454: @1 = mac(@50,@49,@1) */
  casadi_mtimes((&w50), casadi_s6, w49, casadi_s5, w1, casadi_s4, w, 0);
  /* #455: @1 = @1' */
  /* #456: @41 = (@41+@1) */
  for (i=0, rr=w41, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #457: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #458: (@21[:3] += @41) */
  for (rr=w21+0, ss=w41; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #459: {@50, @54, @48, @74, @68, @67, @46, @47, @75, @76, @77, @78, @79} = vertsplit(@21) */
  w50 = w21[0];
  w54 = w21[1];
  w48 = w21[2];
  w74 = w21[3];
  w68 = w21[4];
  w67 = w21[5];
  w46 = w21[6];
  w47 = w21[7];
  w75 = w21[8];
  w76 = w21[9];
  w77 = w21[10];
  w78 = w21[11];
  w79 = w21[12];
  /* #460: @66 = (@66/@8) */
  for (i=0, rr=w66; i<4; ++i) (*rr++) /= w8;
  /* #461: @25 = (@25/@8) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) /= w8;
  /* #462: @62 = (@25*@53) */
  for (i=0, rr=w62, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #463: @66 = (@66-@62) */
  for (i=0, rr=w66, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #464: {@53, @80, @81, @82} = vertsplit(@66) */
  w53 = w66[0];
  w80 = w66[1];
  w81 = w66[2];
  w82 = w66[3];
  /* #465: @53 = (@53+@46) */
  w53 += w46;
  /* #466: @47 = (@47-@80) */
  w47 -= w80;
  /* #467: @75 = (@75-@81) */
  w75 -= w81;
  /* #468: @76 = (@76-@82) */
  w76 -= w82;
  /* #469: @19 = vertcat(@52, @55, @44, @51, @50, @54, @48, @74, @68, @67, @53, @47, @75, @76, @77, @78, @79) */
  rr=w19;
  *rr++ = w52;
  *rr++ = w55;
  *rr++ = w44;
  *rr++ = w51;
  *rr++ = w50;
  *rr++ = w54;
  *rr++ = w48;
  *rr++ = w74;
  *rr++ = w68;
  *rr++ = w67;
  *rr++ = w53;
  *rr++ = w47;
  *rr++ = w75;
  *rr++ = w76;
  *rr++ = w77;
  *rr++ = w78;
  *rr++ = w79;
  /* #470: @83 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w83, ss=w19; cii!=casadi_s7+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #471: (@56[0, 1, 2, 3, 16, 17, 18, 25, 26, 27, 28] = @83) */
  for (cii=casadi_s8, rr=w56, ss=w83; cii!=casadi_s8+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #472: @83 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w83, ss=w19; cii!=casadi_s7+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #473: (@56[0, 4, 8, 12, 16, 19, 22, 25, 29, 33, 37] = @83) */
  for (cii=casadi_s9, rr=w56, ss=w83; cii!=casadi_s9+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #474: @66 = zeros(1x4) */
  casadi_clear(w66, 4);
  /* #475: @59 = 00 */
  /* #476: @41 = ones(17x1,3nz) */
  casadi_fill(w41, 3, 1.);
  /* #477: {NULL, @52, NULL, NULL, NULL, @55, NULL, NULL, NULL, NULL, NULL, @44, NULL, NULL, NULL, NULL, NULL} = vertsplit(@41) */
  w52 = w41[0];
  w55 = w41[1];
  w44 = w41[2];
  /* #478: @60 = 00 */
  /* #479: @61 = 00 */
  /* #480: @51 = vertcat(@59, @52, @60, @61) */
  rr=(&w51);
  *rr++ = w52;
  /* #481: @52 = @51' */
  casadi_copy((&w51), 1, (&w52));
  /* #482: @66 = mac(@52,@27,@66) */
  casadi_mtimes((&w52), casadi_s10, w27, casadi_s1, w66, casadi_s0, w, 0);
  /* #483: @66 = @66' */
  /* #484: @62 = zeros(1x4) */
  casadi_clear(w62, 4);
  /* #485: @51 = @51' */
  /* #486: @62 = mac(@51,@36,@62) */
  casadi_mtimes((&w51), casadi_s10, w36, casadi_s1, w62, casadi_s0, w, 0);
  /* #487: @62 = @62' */
  /* #488: @66 = (@66+@62) */
  for (i=0, rr=w66, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #489: {@51, @52, @50, @54} = vertsplit(@66) */
  w51 = w66[0];
  w52 = w66[1];
  w50 = w66[2];
  w54 = w66[3];
  /* #490: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #491: @66 = zeros(4x1) */
  casadi_clear(w66, 4);
  /* #492: @59 = 00 */
  /* #493: @48 = (-@44) */
  w48 = (- w44 );
  /* #494: @60 = 00 */
  /* #495: @61 = 00 */
  /* #496: @74 = vertcat(@59, @48, @60, @61) */
  rr=(&w74);
  *rr++ = w48;
  /* #497: @74 = (@74/@8) */
  w74 /= w8;
  /* #498: @62 = dense(@74) */
  casadi_densify((&w74), casadi_s11, w62, 0);
  /* #499: @74 = project(@28) */
  casadi_sparsify(w28, (&w74), casadi_s11, 0);
  /* #500: @48 = @44[0] */
  for (rr=(&w48), ss=(&w44)+0; ss!=(&w44)+1; ss+=1) *rr++ = *ss;
  /* #501: @44 = dot(@74, @48) */
  w44 = casadi_dot(1, (&w74), (&w48));
  /* #502: @44 = (@44/@8) */
  w44 /= w8;
  /* #503: @57 = (@26*@44) */
  for (i=0, rr=w57, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #504: @62 = (@62-@57) */
  for (i=0, rr=w62, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #505: {@74, @68, @67, @53} = vertsplit(@62) */
  w74 = w62[0];
  w68 = w62[1];
  w67 = w62[2];
  w53 = w62[3];
  /* #506: @47 = (@4*@74) */
  w47  = (w4*w74);
  /* #507: @75 = (@5*@68) */
  w75  = (w5*w68);
  /* #508: @47 = (@47-@75) */
  w47 -= w75;
  /* #509: @75 = (@6*@67) */
  w75  = (w6*w67);
  /* #510: @47 = (@47-@75) */
  w47 -= w75;
  /* #511: @75 = (@7*@53) */
  w75  = (w7*w53);
  /* #512: @47 = (@47-@75) */
  w47 -= w75;
  /* #513: @75 = (@5*@74) */
  w75  = (w5*w74);
  /* #514: @76 = (@4*@68) */
  w76  = (w4*w68);
  /* #515: @75 = (@75+@76) */
  w75 += w76;
  /* #516: @76 = (@7*@67) */
  w76  = (w7*w67);
  /* #517: @75 = (@75+@76) */
  w75 += w76;
  /* #518: @76 = (@6*@53) */
  w76  = (w6*w53);
  /* #519: @75 = (@75-@76) */
  w75 -= w76;
  /* #520: @76 = (@6*@74) */
  w76  = (w6*w74);
  /* #521: @77 = (@7*@68) */
  w77  = (w7*w68);
  /* #522: @76 = (@76-@77) */
  w76 -= w77;
  /* #523: @77 = (@4*@67) */
  w77  = (w4*w67);
  /* #524: @76 = (@76+@77) */
  w76 += w77;
  /* #525: @77 = (@5*@53) */
  w77  = (w5*w53);
  /* #526: @76 = (@76+@77) */
  w76 += w77;
  /* #527: @74 = (@7*@74) */
  w74  = (w7*w74);
  /* #528: @68 = (@6*@68) */
  w68  = (w6*w68);
  /* #529: @74 = (@74+@68) */
  w74 += w68;
  /* #530: @67 = (@5*@67) */
  w67  = (w5*w67);
  /* #531: @74 = (@74-@67) */
  w74 -= w67;
  /* #532: @53 = (@4*@53) */
  w53  = (w4*w53);
  /* #533: @74 = (@74+@53) */
  w74 += w53;
  /* #534: @57 = vertcat(@47, @75, @76, @74) */
  rr=w57;
  *rr++ = w47;
  *rr++ = w75;
  *rr++ = w76;
  *rr++ = w74;
  /* #535: @63 = (@12*@57) */
  for (i=0, rr=w63, cs=w57; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #536: @57 = (@13*@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #537: @63 = (@63-@57) */
  for (i=0, rr=w63, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #538: @41 = @63[1:4] */
  for (rr=w41, ss=w63+1; ss!=w63+4; ss+=1) *rr++ = *ss;
  /* #539: @47 = dot(@31, @41) */
  w47 = casadi_dot(3, w31, w41);
  /* #540: @47 = (@47/@14) */
  w47 /= w14;
  /* #541: @75 = (@47/@3) */
  w75  = (w47/w3);
  /* #542: @76 = (@18*@47) */
  w76  = (w18*w47);
  /* #543: @74 = @63[0] */
  for (rr=(&w74), ss=w63+0; ss!=w63+1; ss+=1) *rr++ = *ss;
  /* #544: @53 = (@43*@74) */
  w53  = (w43*w74);
  /* #545: @76 = (@76+@53) */
  w76 += w53;
  /* #546: @53 = (@64*@76) */
  w53  = (w64*w76);
  /* #547: @75 = (@75-@53) */
  w75 -= w53;
  /* #548: @75 = (@0*@75) */
  w75  = (w0*w75);
  /* #549: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #550: @69 = (2.*@41) */
  for (i=0, rr=w69, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #551: @40 = (@9*@69) */
  for (i=0, rr=w40, cs=w69; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #552: @53 = (@15*@47) */
  w53  = (w15*w47);
  /* #553: @67 = (@65*@74) */
  w67  = (w65*w74);
  /* #554: @53 = (@53-@67) */
  w53 -= w67;
  /* #555: @20 = (@32*@53) */
  for (i=0, rr=w20, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #556: @40 = (@40+@20) */
  for (i=0, rr=w40, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #557: @40 = (@40/@14) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) /= w14;
  /* #558: @20 = (@33*@47) */
  for (i=0, rr=w20, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #559: @40 = (@40-@20) */
  for (i=0, rr=w40, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #560: @20 = @40' */
  casadi_copy(w40, 3, w20);
  /* #561: @1 = mac(@20,@35,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #562: @1 = @1' */
  /* #563: @20 = zeros(1x3) */
  casadi_clear(w20, 3);
  /* #564: @71 = @40' */
  casadi_copy(w40, 3, w71);
  /* #565: @20 = mac(@71,@38,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w71+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #566: @20 = @20' */
  /* #567: @1 = (@1+@20) */
  for (i=0, rr=w1, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #568: @20 = (@1/@14) */
  for (i=0, rr=w20, cr=w1; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #569: @71 = (@70*@47) */
  for (i=0, rr=w71, cr=w70; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #570: @20 = (@20-@71) */
  for (i=0, rr=w20, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  /* #571: @67 = dot(@32, @20) */
  w67 = casadi_dot(3, w32, w20);
  /* #572: @68 = dot(@69, @34) */
  w68 = casadi_dot(3, w69, w34);
  /* #573: @67 = (@67+@68) */
  w67 += w68;
  /* #574: @68 = (@2*@67) */
  w68  = (w2*w67);
  /* #575: @75 = (@75+@68) */
  w75 += w68;
  /* #576: @75 = (-@75) */
  w75 = (- w75 );
  /* #577: (@66[0] += @75) */
  for (rr=w66+0, ss=(&w75); rr!=w66+1; rr+=1) *rr += *ss++;
  /* #578: @75 = dot(@39, @1) */
  w75 = casadi_dot(3, w39, w1);
  /* #579: @40 = (@40/@14) */
  for (i=0, rr=w40; i<3; ++i) (*rr++) /= w14;
  /* #580: @1 = (@37*@47) */
  for (i=0, rr=w1, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #581: @40 = (@40-@1) */
  for (i=0, rr=w40, cs=w1; i<3; ++i) (*rr++) -= (*cs++);
  /* #582: @40 = (-@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #583: @68 = dot(@40, @22) */
  w68 = casadi_dot(3, w40, w22);
  /* #584: @75 = (@75+@68) */
  w75 += w68;
  /* #585: @74 = (@74/@3) */
  w74 /= w3;
  /* #586: @76 = (@72*@76) */
  w76  = (w72*w76);
  /* #587: @74 = (@74-@76) */
  w74 -= w76;
  /* #588: @74 = (@0*@74) */
  w74  = (w0*w74);
  /* #589: @67 = (@16*@67) */
  w67  = (w16*w67);
  /* #590: @74 = (@74+@67) */
  w74 += w67;
  /* #591: @75 = (@75+@74) */
  w75 += w74;
  /* #592: @75 = (@75/@14) */
  w75 /= w14;
  /* #593: @47 = (@42*@47) */
  w47  = (w42*w47);
  /* #594: @75 = (@75-@47) */
  w75 -= w47;
  /* #595: @40 = (@31*@75) */
  for (i=0, rr=w40, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  /* #596: @41 = (@10*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #597: @40 = (@40+@41) */
  for (i=0, rr=w40, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #598: @41 = (@34*@53) */
  for (i=0, rr=w41, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #599: @20 = (@9*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #600: @41 = (@41+@20) */
  for (i=0, rr=w41, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #601: @41 = (2.*@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #602: @40 = (@40+@41) */
  for (i=0, rr=w40, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #603: (@66[1:4] += @40) */
  for (rr=w66+1, ss=w40; rr!=w66+4; rr+=1) *rr += *ss++;
  /* #604: @63 = (@11*@66) */
  for (i=0, rr=w63, cs=w66; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #605: @66 = (@17*@66) */
  for (i=0, rr=w66, cs=w66; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #606: @63 = (@63-@66) */
  for (i=0, rr=w63, cs=w66; i<4; ++i) (*rr++) -= (*cs++);
  /* #607: {@53, @75, @47, @74} = vertsplit(@63) */
  w53 = w63[0];
  w75 = w63[1];
  w47 = w63[2];
  w74 = w63[3];
  /* #608: @67 = (@7*@74) */
  w67  = (w7*w74);
  /* #609: @76 = (@6*@47) */
  w76  = (w6*w47);
  /* #610: @67 = (@67+@76) */
  w67 += w76;
  /* #611: @76 = (@5*@75) */
  w76  = (w5*w75);
  /* #612: @67 = (@67+@76) */
  w67 += w76;
  /* #613: @76 = (@4*@53) */
  w76  = (w4*w53);
  /* #614: @67 = (@67+@76) */
  w67 += w76;
  /* #615: @76 = (@6*@74) */
  w76  = (w6*w74);
  /* #616: @68 = (@7*@47) */
  w68  = (w7*w47);
  /* #617: @76 = (@76-@68) */
  w76 -= w68;
  /* #618: @68 = (@4*@75) */
  w68  = (w4*w75);
  /* #619: @76 = (@76+@68) */
  w76 += w68;
  /* #620: @68 = (@5*@53) */
  w68  = (w5*w53);
  /* #621: @76 = (@76-@68) */
  w76 -= w68;
  /* #622: @68 = (@4*@47) */
  w68  = (w4*w47);
  /* #623: @77 = (@5*@74) */
  w77  = (w5*w74);
  /* #624: @68 = (@68-@77) */
  w68 -= w77;
  /* #625: @77 = (@7*@75) */
  w77  = (w7*w75);
  /* #626: @68 = (@68+@77) */
  w68 += w77;
  /* #627: @77 = (@6*@53) */
  w77  = (w6*w53);
  /* #628: @68 = (@68-@77) */
  w68 -= w77;
  /* #629: @74 = (@4*@74) */
  w74  = (w4*w74);
  /* #630: @47 = (@5*@47) */
  w47  = (w5*w47);
  /* #631: @74 = (@74+@47) */
  w74 += w47;
  /* #632: @75 = (@6*@75) */
  w75  = (w6*w75);
  /* #633: @74 = (@74-@75) */
  w74 -= w75;
  /* #634: @53 = (@7*@53) */
  w53  = (w7*w53);
  /* #635: @74 = (@74-@53) */
  w74 -= w53;
  /* #636: @63 = vertcat(@67, @76, @68, @74) */
  rr=w63;
  *rr++ = w67;
  *rr++ = w76;
  *rr++ = w68;
  *rr++ = w74;
  /* #637: @67 = dot(@30, @63) */
  w67 = casadi_dot(4, w30, w63);
  /* #638: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w8;
  /* #639: @66 = (@24*@44) */
  for (i=0, rr=w66, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #640: @62 = (@62-@66) */
  for (i=0, rr=w62, cs=w66; i<4; ++i) (*rr++) -= (*cs++);
  /* #641: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) *rr++ = (- *cs++ );
  /* #642: @76 = dot(@62, @29) */
  w76 = casadi_dot(4, w62, w29);
  /* #643: @67 = (@67+@76) */
  w67 += w76;
  /* #644: @67 = (@67/@8) */
  w67 /= w8;
  /* #645: @76 = (@73*@44) */
  w76  = (w73*w44);
  /* #646: @67 = (@67-@76) */
  w67 -= w76;
  /* #647: @62 = (@28*@67) */
  for (i=0, rr=w62, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w67);
  /* #648: @48 = (@45*@48) */
  w48  = (w45*w48);
  /* #649: @66 = dense(@48) */
  casadi_densify((&w48), casadi_s11, w66, 0);
  /* #650: @62 = (@62+@66) */
  for (i=0, rr=w62, cs=w66; i<4; ++i) (*rr++) += (*cs++);
  /* #651: (@21[6:10] += @62) */
  for (rr=w21+6, ss=w62; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #652: @40 = zeros(1x3) */
  casadi_clear(w40, 3);
  /* #653: @48 = @55[0] */
  for (rr=(&w48), ss=(&w55)+0; ss!=(&w55)+1; ss+=1) *rr++ = *ss;
  /* #654: @48 = (-@48) */
  w48 = (- w48 );
  /* #655: @55 = @48' */
  casadi_copy((&w48), 1, (&w55));
  /* #656: @40 = mac(@55,@23,@40) */
  casadi_mtimes((&w55), casadi_s12, w23, casadi_s5, w40, casadi_s4, w, 0);
  /* #657: @40 = @40' */
  /* #658: @41 = zeros(1x3) */
  casadi_clear(w41, 3);
  /* #659: @48 = @48' */
  /* #660: @41 = mac(@48,@49,@41) */
  casadi_mtimes((&w48), casadi_s12, w49, casadi_s5, w41, casadi_s4, w, 0);
  /* #661: @41 = @41' */
  /* #662: @40 = (@40+@41) */
  for (i=0, rr=w40, cs=w41; i<3; ++i) (*rr++) += (*cs++);
  /* #663: @40 = (-@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (- *cs++ );
  /* #664: (@21[:3] += @40) */
  for (rr=w21+0, ss=w40; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #665: {@48, @55, @67, @76, @68, @74, @53, @75, @47, @77, @78, @79, @82} = vertsplit(@21) */
  w48 = w21[0];
  w55 = w21[1];
  w67 = w21[2];
  w76 = w21[3];
  w68 = w21[4];
  w74 = w21[5];
  w53 = w21[6];
  w75 = w21[7];
  w47 = w21[8];
  w77 = w21[9];
  w78 = w21[10];
  w79 = w21[11];
  w82 = w21[12];
  /* #666: @63 = (@63/@8) */
  for (i=0, rr=w63; i<4; ++i) (*rr++) /= w8;
  /* #667: @62 = (@25*@44) */
  for (i=0, rr=w62, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w44);
  /* #668: @63 = (@63-@62) */
  for (i=0, rr=w63, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #669: {@44, @81, @80, @46} = vertsplit(@63) */
  w44 = w63[0];
  w81 = w63[1];
  w80 = w63[2];
  w46 = w63[3];
  /* #670: @44 = (@44+@53) */
  w44 += w53;
  /* #671: @75 = (@75-@81) */
  w75 -= w81;
  /* #672: @47 = (@47-@80) */
  w47 -= w80;
  /* #673: @77 = (@77-@46) */
  w77 -= w46;
  /* #674: @19 = vertcat(@51, @52, @50, @54, @48, @55, @67, @76, @68, @74, @44, @75, @47, @77, @78, @79, @82) */
  rr=w19;
  *rr++ = w51;
  *rr++ = w52;
  *rr++ = w50;
  *rr++ = w54;
  *rr++ = w48;
  *rr++ = w55;
  *rr++ = w67;
  *rr++ = w76;
  *rr++ = w68;
  *rr++ = w74;
  *rr++ = w44;
  *rr++ = w75;
  *rr++ = w47;
  *rr++ = w77;
  *rr++ = w78;
  *rr++ = w79;
  *rr++ = w82;
  /* #675: @83 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w83, ss=w19; cii!=casadi_s7+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #676: (@56[4, 5, 6, 7, 19, 20, 21, 29, 30, 31, 32] = @83) */
  for (cii=casadi_s13, rr=w56, ss=w83; cii!=casadi_s13+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #677: @83 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w83, ss=w19; cii!=casadi_s7+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #678: (@56[1, 5, 9, 13, 17, 20, 23, 26, 30, 34, 38] = @83) */
  for (cii=casadi_s14, rr=w56, ss=w83; cii!=casadi_s14+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #679: @63 = zeros(1x4) */
  casadi_clear(w63, 4);
  /* #680: @59 = 00 */
  /* #681: @60 = 00 */
  /* #682: @40 = ones(17x1,3nz) */
  casadi_fill(w40, 3, 1.);
  /* #683: {NULL, NULL, @51, NULL, NULL, NULL, @52, NULL, NULL, NULL, NULL, NULL, @50, NULL, NULL, NULL, NULL} = vertsplit(@40) */
  w51 = w40[0];
  w52 = w40[1];
  w50 = w40[2];
  /* #684: @61 = 00 */
  /* #685: @54 = vertcat(@59, @60, @51, @61) */
  rr=(&w54);
  *rr++ = w51;
  /* #686: @51 = @54' */
  casadi_copy((&w54), 1, (&w51));
  /* #687: @63 = mac(@51,@27,@63) */
  casadi_mtimes((&w51), casadi_s15, w27, casadi_s1, w63, casadi_s0, w, 0);
  /* #688: @63 = @63' */
  /* #689: @62 = zeros(1x4) */
  casadi_clear(w62, 4);
  /* #690: @54 = @54' */
  /* #691: @62 = mac(@54,@36,@62) */
  casadi_mtimes((&w54), casadi_s15, w36, casadi_s1, w62, casadi_s0, w, 0);
  /* #692: @62 = @62' */
  /* #693: @63 = (@63+@62) */
  for (i=0, rr=w63, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #694: {@54, @51, @48, @55} = vertsplit(@63) */
  w54 = w63[0];
  w51 = w63[1];
  w48 = w63[2];
  w55 = w63[3];
  /* #695: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #696: @63 = zeros(4x1) */
  casadi_clear(w63, 4);
  /* #697: @59 = 00 */
  /* #698: @60 = 00 */
  /* #699: @67 = (-@50) */
  w67 = (- w50 );
  /* #700: @61 = 00 */
  /* #701: @76 = vertcat(@59, @60, @67, @61) */
  rr=(&w76);
  *rr++ = w67;
  /* #702: @76 = (@76/@8) */
  w76 /= w8;
  /* #703: @62 = dense(@76) */
  casadi_densify((&w76), casadi_s16, w62, 0);
  /* #704: @76 = project(@28) */
  casadi_sparsify(w28, (&w76), casadi_s16, 0);
  /* #705: @67 = @50[0] */
  for (rr=(&w67), ss=(&w50)+0; ss!=(&w50)+1; ss+=1) *rr++ = *ss;
  /* #706: @50 = dot(@76, @67) */
  w50 = casadi_dot(1, (&w76), (&w67));
  /* #707: @50 = (@50/@8) */
  w50 /= w8;
  /* #708: @66 = (@26*@50) */
  for (i=0, rr=w66, cr=w26; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #709: @62 = (@62-@66) */
  for (i=0, rr=w62, cs=w66; i<4; ++i) (*rr++) -= (*cs++);
  /* #710: {@76, @68, @74, @44} = vertsplit(@62) */
  w76 = w62[0];
  w68 = w62[1];
  w74 = w62[2];
  w44 = w62[3];
  /* #711: @75 = (@4*@76) */
  w75  = (w4*w76);
  /* #712: @47 = (@5*@68) */
  w47  = (w5*w68);
  /* #713: @75 = (@75-@47) */
  w75 -= w47;
  /* #714: @47 = (@6*@74) */
  w47  = (w6*w74);
  /* #715: @75 = (@75-@47) */
  w75 -= w47;
  /* #716: @47 = (@7*@44) */
  w47  = (w7*w44);
  /* #717: @75 = (@75-@47) */
  w75 -= w47;
  /* #718: @47 = (@5*@76) */
  w47  = (w5*w76);
  /* #719: @77 = (@4*@68) */
  w77  = (w4*w68);
  /* #720: @47 = (@47+@77) */
  w47 += w77;
  /* #721: @77 = (@7*@74) */
  w77  = (w7*w74);
  /* #722: @47 = (@47+@77) */
  w47 += w77;
  /* #723: @77 = (@6*@44) */
  w77  = (w6*w44);
  /* #724: @47 = (@47-@77) */
  w47 -= w77;
  /* #725: @77 = (@6*@76) */
  w77  = (w6*w76);
  /* #726: @78 = (@7*@68) */
  w78  = (w7*w68);
  /* #727: @77 = (@77-@78) */
  w77 -= w78;
  /* #728: @78 = (@4*@74) */
  w78  = (w4*w74);
  /* #729: @77 = (@77+@78) */
  w77 += w78;
  /* #730: @78 = (@5*@44) */
  w78  = (w5*w44);
  /* #731: @77 = (@77+@78) */
  w77 += w78;
  /* #732: @76 = (@7*@76) */
  w76  = (w7*w76);
  /* #733: @68 = (@6*@68) */
  w68  = (w6*w68);
  /* #734: @76 = (@76+@68) */
  w76 += w68;
  /* #735: @74 = (@5*@74) */
  w74  = (w5*w74);
  /* #736: @76 = (@76-@74) */
  w76 -= w74;
  /* #737: @44 = (@4*@44) */
  w44  = (w4*w44);
  /* #738: @76 = (@76+@44) */
  w76 += w44;
  /* #739: @66 = vertcat(@75, @47, @77, @76) */
  rr=w66;
  *rr++ = w75;
  *rr++ = w47;
  *rr++ = w77;
  *rr++ = w76;
  /* #740: @57 = (@12*@66) */
  for (i=0, rr=w57, cs=w66; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #741: @66 = (@13*@66) */
  for (i=0, rr=w66, cs=w66; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #742: @57 = (@57-@66) */
  for (i=0, rr=w57, cs=w66; i<4; ++i) (*rr++) -= (*cs++);
  /* #743: @40 = @57[1:4] */
  for (rr=w40, ss=w57+1; ss!=w57+4; ss+=1) *rr++ = *ss;
  /* #744: @75 = dot(@31, @40) */
  w75 = casadi_dot(3, w31, w40);
  /* #745: @75 = (@75/@14) */
  w75 /= w14;
  /* #746: @47 = (@75/@3) */
  w47  = (w75/w3);
  /* #747: @77 = (@18*@75) */
  w77  = (w18*w75);
  /* #748: @76 = @57[0] */
  for (rr=(&w76), ss=w57+0; ss!=w57+1; ss+=1) *rr++ = *ss;
  /* #749: @44 = (@43*@76) */
  w44  = (w43*w76);
  /* #750: @77 = (@77+@44) */
  w77 += w44;
  /* #751: @44 = (@64*@77) */
  w44  = (w64*w77);
  /* #752: @47 = (@47-@44) */
  w47 -= w44;
  /* #753: @47 = (@0*@47) */
  w47  = (w0*w47);
  /* #754: @41 = zeros(1x3) */
  casadi_clear(w41, 3);
  /* #755: @20 = (2.*@40) */
  for (i=0, rr=w20, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #756: @1 = (@9*@20) */
  for (i=0, rr=w1, cs=w20; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #757: @44 = (@15*@75) */
  w44  = (w15*w75);
  /* #758: @74 = (@65*@76) */
  w74  = (w65*w76);
  /* #759: @44 = (@44-@74) */
  w44 -= w74;
  /* #760: @69 = (@32*@44) */
  for (i=0, rr=w69, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #761: @1 = (@1+@69) */
  for (i=0, rr=w1, cs=w69; i<3; ++i) (*rr++) += (*cs++);
  /* #762: @1 = (@1/@14) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w14;
  /* #763: @69 = (@33*@75) */
  for (i=0, rr=w69, cr=w33; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  /* #764: @1 = (@1-@69) */
  for (i=0, rr=w1, cs=w69; i<3; ++i) (*rr++) -= (*cs++);
  /* #765: @69 = @1' */
  casadi_copy(w1, 3, w69);
  /* #766: @41 = mac(@69,@35,@41) */
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w69+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #767: @41 = @41' */
  /* #768: @69 = zeros(1x3) */
  casadi_clear(w69, 3);
  /* #769: @71 = @1' */
  casadi_copy(w1, 3, w71);
  /* #770: @69 = mac(@71,@38,@69) */
  for (i=0, rr=w69; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w71+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #771: @69 = @69' */
  /* #772: @41 = (@41+@69) */
  for (i=0, rr=w41, cs=w69; i<3; ++i) (*rr++) += (*cs++);
  /* #773: @69 = (@41/@14) */
  for (i=0, rr=w69, cr=w41; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #774: @71 = (@70*@75) */
  for (i=0, rr=w71, cr=w70; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  /* #775: @69 = (@69-@71) */
  for (i=0, rr=w69, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  /* #776: @74 = dot(@32, @69) */
  w74 = casadi_dot(3, w32, w69);
  /* #777: @68 = dot(@20, @34) */
  w68 = casadi_dot(3, w20, w34);
  /* #778: @74 = (@74+@68) */
  w74 += w68;
  /* #779: @68 = (@2*@74) */
  w68  = (w2*w74);
  /* #780: @47 = (@47+@68) */
  w47 += w68;
  /* #781: @47 = (-@47) */
  w47 = (- w47 );
  /* #782: (@63[0] += @47) */
  for (rr=w63+0, ss=(&w47); rr!=w63+1; rr+=1) *rr += *ss++;
  /* #783: @47 = dot(@39, @41) */
  w47 = casadi_dot(3, w39, w41);
  /* #784: @1 = (@1/@14) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w14;
  /* #785: @41 = (@37*@75) */
  for (i=0, rr=w41, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  /* #786: @1 = (@1-@41) */
  for (i=0, rr=w1, cs=w41; i<3; ++i) (*rr++) -= (*cs++);
  /* #787: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #788: @68 = dot(@1, @22) */
  w68 = casadi_dot(3, w1, w22);
  /* #789: @47 = (@47+@68) */
  w47 += w68;
  /* #790: @76 = (@76/@3) */
  w76 /= w3;
  /* #791: @77 = (@72*@77) */
  w77  = (w72*w77);
  /* #792: @76 = (@76-@77) */
  w76 -= w77;
  /* #793: @76 = (@0*@76) */
  w76  = (w0*w76);
  /* #794: @74 = (@16*@74) */
  w74  = (w16*w74);
  /* #795: @76 = (@76+@74) */
  w76 += w74;
  /* #796: @47 = (@47+@76) */
  w47 += w76;
  /* #797: @47 = (@47/@14) */
  w47 /= w14;
  /* #798: @75 = (@42*@75) */
  w75  = (w42*w75);
  /* #799: @47 = (@47-@75) */
  w47 -= w75;
  /* #800: @1 = (@31*@47) */
  for (i=0, rr=w1, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w47);
  /* #801: @40 = (@10*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #802: @1 = (@1+@40) */
  for (i=0, rr=w1, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #803: @40 = (@34*@44) */
  for (i=0, rr=w40, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w44);
  /* #804: @69 = (@9*@69) */
  for (i=0, rr=w69, cs=w69; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #805: @40 = (@40+@69) */
  for (i=0, rr=w40, cs=w69; i<3; ++i) (*rr++) += (*cs++);
  /* #806: @40 = (2.*@40) */
  for (i=0, rr=w40, cs=w40; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #807: @1 = (@1+@40) */
  for (i=0, rr=w1, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #808: (@63[1:4] += @1) */
  for (rr=w63+1, ss=w1; rr!=w63+4; rr+=1) *rr += *ss++;
  /* #809: @57 = (@11*@63) */
  for (i=0, rr=w57, cs=w63; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #810: @63 = (@17*@63) */
  for (i=0, rr=w63, cs=w63; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #811: @57 = (@57-@63) */
  for (i=0, rr=w57, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #812: {@44, @47, @75, @76} = vertsplit(@57) */
  w44 = w57[0];
  w47 = w57[1];
  w75 = w57[2];
  w76 = w57[3];
  /* #813: @74 = (@7*@76) */
  w74  = (w7*w76);
  /* #814: @77 = (@6*@75) */
  w77  = (w6*w75);
  /* #815: @74 = (@74+@77) */
  w74 += w77;
  /* #816: @77 = (@5*@47) */
  w77  = (w5*w47);
  /* #817: @74 = (@74+@77) */
  w74 += w77;
  /* #818: @77 = (@4*@44) */
  w77  = (w4*w44);
  /* #819: @74 = (@74+@77) */
  w74 += w77;
  /* #820: @77 = (@6*@76) */
  w77  = (w6*w76);
  /* #821: @68 = (@7*@75) */
  w68  = (w7*w75);
  /* #822: @77 = (@77-@68) */
  w77 -= w68;
  /* #823: @68 = (@4*@47) */
  w68  = (w4*w47);
  /* #824: @77 = (@77+@68) */
  w77 += w68;
  /* #825: @68 = (@5*@44) */
  w68  = (w5*w44);
  /* #826: @77 = (@77-@68) */
  w77 -= w68;
  /* #827: @68 = (@4*@75) */
  w68  = (w4*w75);
  /* #828: @78 = (@5*@76) */
  w78  = (w5*w76);
  /* #829: @68 = (@68-@78) */
  w68 -= w78;
  /* #830: @78 = (@7*@47) */
  w78  = (w7*w47);
  /* #831: @68 = (@68+@78) */
  w68 += w78;
  /* #832: @78 = (@6*@44) */
  w78  = (w6*w44);
  /* #833: @68 = (@68-@78) */
  w68 -= w78;
  /* #834: @76 = (@4*@76) */
  w76  = (w4*w76);
  /* #835: @75 = (@5*@75) */
  w75  = (w5*w75);
  /* #836: @76 = (@76+@75) */
  w76 += w75;
  /* #837: @47 = (@6*@47) */
  w47  = (w6*w47);
  /* #838: @76 = (@76-@47) */
  w76 -= w47;
  /* #839: @44 = (@7*@44) */
  w44  = (w7*w44);
  /* #840: @76 = (@76-@44) */
  w76 -= w44;
  /* #841: @57 = vertcat(@74, @77, @68, @76) */
  rr=w57;
  *rr++ = w74;
  *rr++ = w77;
  *rr++ = w68;
  *rr++ = w76;
  /* #842: @74 = dot(@30, @57) */
  w74 = casadi_dot(4, w30, w57);
  /* #843: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w8;
  /* #844: @63 = (@24*@50) */
  for (i=0, rr=w63, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #845: @62 = (@62-@63) */
  for (i=0, rr=w62, cs=w63; i<4; ++i) (*rr++) -= (*cs++);
  /* #846: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) *rr++ = (- *cs++ );
  /* #847: @77 = dot(@62, @29) */
  w77 = casadi_dot(4, w62, w29);
  /* #848: @74 = (@74+@77) */
  w74 += w77;
  /* #849: @74 = (@74/@8) */
  w74 /= w8;
  /* #850: @77 = (@73*@50) */
  w77  = (w73*w50);
  /* #851: @74 = (@74-@77) */
  w74 -= w77;
  /* #852: @62 = (@28*@74) */
  for (i=0, rr=w62, cr=w28; i<4; ++i) (*rr++)  = ((*cr++)*w74);
  /* #853: @67 = (@45*@67) */
  w67  = (w45*w67);
  /* #854: @63 = dense(@67) */
  casadi_densify((&w67), casadi_s16, w63, 0);
  /* #855: @62 = (@62+@63) */
  for (i=0, rr=w62, cs=w63; i<4; ++i) (*rr++) += (*cs++);
  /* #856: (@21[6:10] += @62) */
  for (rr=w21+6, ss=w62; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #857: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #858: @67 = @52[0] */
  for (rr=(&w67), ss=(&w52)+0; ss!=(&w52)+1; ss+=1) *rr++ = *ss;
  /* #859: @67 = (-@67) */
  w67 = (- w67 );
  /* #860: @52 = @67' */
  casadi_copy((&w67), 1, (&w52));
  /* #861: @1 = mac(@52,@23,@1) */
  casadi_mtimes((&w52), casadi_s17, w23, casadi_s5, w1, casadi_s4, w, 0);
  /* #862: @1 = @1' */
  /* #863: @40 = zeros(1x3) */
  casadi_clear(w40, 3);
  /* #864: @67 = @67' */
  /* #865: @40 = mac(@67,@49,@40) */
  casadi_mtimes((&w67), casadi_s17, w49, casadi_s5, w40, casadi_s4, w, 0);
  /* #866: @40 = @40' */
  /* #867: @1 = (@1+@40) */
  for (i=0, rr=w1, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #868: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #869: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #870: {@67, @52, @74, @77, @68, @76, @44, @47, @75, @78, @79, @82, @46} = vertsplit(@21) */
  w67 = w21[0];
  w52 = w21[1];
  w74 = w21[2];
  w77 = w21[3];
  w68 = w21[4];
  w76 = w21[5];
  w44 = w21[6];
  w47 = w21[7];
  w75 = w21[8];
  w78 = w21[9];
  w79 = w21[10];
  w82 = w21[11];
  w46 = w21[12];
  /* #871: @57 = (@57/@8) */
  for (i=0, rr=w57; i<4; ++i) (*rr++) /= w8;
  /* #872: @62 = (@25*@50) */
  for (i=0, rr=w62, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #873: @57 = (@57-@62) */
  for (i=0, rr=w57, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #874: {@50, @80, @81, @53} = vertsplit(@57) */
  w50 = w57[0];
  w80 = w57[1];
  w81 = w57[2];
  w53 = w57[3];
  /* #875: @50 = (@50+@44) */
  w50 += w44;
  /* #876: @47 = (@47-@80) */
  w47 -= w80;
  /* #877: @75 = (@75-@81) */
  w75 -= w81;
  /* #878: @78 = (@78-@53) */
  w78 -= w53;
  /* #879: @19 = vertcat(@54, @51, @48, @55, @67, @52, @74, @77, @68, @76, @50, @47, @75, @78, @79, @82, @46) */
  rr=w19;
  *rr++ = w54;
  *rr++ = w51;
  *rr++ = w48;
  *rr++ = w55;
  *rr++ = w67;
  *rr++ = w52;
  *rr++ = w74;
  *rr++ = w77;
  *rr++ = w68;
  *rr++ = w76;
  *rr++ = w50;
  *rr++ = w47;
  *rr++ = w75;
  *rr++ = w78;
  *rr++ = w79;
  *rr++ = w82;
  *rr++ = w46;
  /* #880: @83 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w83, ss=w19; cii!=casadi_s7+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #881: (@56[8, 9, 10, 11, 22, 23, 24, 33, 34, 35, 36] = @83) */
  for (cii=casadi_s18, rr=w56, ss=w83; cii!=casadi_s18+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #882: @83 = @19[0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13] */
  for (cii=casadi_s7, rr=w83, ss=w19; cii!=casadi_s7+11; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #883: (@56[2, 6, 10, 14, 18, 21, 24, 27, 31, 35, 39] = @83) */
  for (cii=casadi_s19, rr=w56, ss=w83; cii!=casadi_s19+11; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #884: @57 = zeros(1x4) */
  casadi_clear(w57, 4);
  /* #885: @59 = 00 */
  /* #886: @60 = 00 */
  /* #887: @61 = 00 */
  /* #888: @84 = ones(17x1,2nz) */
  casadi_fill(w84, 2, 1.);
  /* #889: {NULL, NULL, NULL, @54, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @51, NULL, NULL, NULL} = vertsplit(@84) */
  w54 = w84[0];
  w51 = w84[1];
  /* #890: @48 = vertcat(@59, @60, @61, @54) */
  rr=(&w48);
  *rr++ = w54;
  /* #891: @54 = @48' */
  casadi_copy((&w48), 1, (&w54));
  /* #892: @57 = mac(@54,@27,@57) */
  casadi_mtimes((&w54), casadi_s20, w27, casadi_s1, w57, casadi_s0, w, 0);
  /* #893: @57 = @57' */
  /* #894: @62 = zeros(1x4) */
  casadi_clear(w62, 4);
  /* #895: @48 = @48' */
  /* #896: @62 = mac(@48,@36,@62) */
  casadi_mtimes((&w48), casadi_s20, w36, casadi_s1, w62, casadi_s0, w, 0);
  /* #897: @62 = @62' */
  /* #898: @57 = (@57+@62) */
  for (i=0, rr=w57, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #899: {@48, @54, @55, @67} = vertsplit(@57) */
  w48 = w57[0];
  w54 = w57[1];
  w55 = w57[2];
  w67 = w57[3];
  /* #900: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #901: @57 = zeros(4x1) */
  casadi_clear(w57, 4);
  /* #902: @59 = 00 */
  /* #903: @60 = 00 */
  /* #904: @61 = 00 */
  /* #905: @52 = (-@51) */
  w52 = (- w51 );
  /* #906: @74 = vertcat(@59, @60, @61, @52) */
  rr=(&w74);
  *rr++ = w52;
  /* #907: @74 = (@74/@8) */
  w74 /= w8;
  /* #908: @62 = dense(@74) */
  casadi_densify((&w74), casadi_s21, w62, 0);
  /* #909: @74 = project(@28) */
  casadi_sparsify(w28, (&w74), casadi_s21, 0);
  /* #910: @52 = @51[0] */
  for (rr=(&w52), ss=(&w51)+0; ss!=(&w51)+1; ss+=1) *rr++ = *ss;
  /* #911: @51 = dot(@74, @52) */
  w51 = casadi_dot(1, (&w74), (&w52));
  /* #912: @51 = (@51/@8) */
  w51 /= w8;
  /* #913: @26 = (@26*@51) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) *= w51;
  /* #914: @62 = (@62-@26) */
  for (i=0, rr=w62, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #915: {@74, @77, @68, @76} = vertsplit(@62) */
  w74 = w62[0];
  w77 = w62[1];
  w68 = w62[2];
  w76 = w62[3];
  /* #916: @50 = (@4*@74) */
  w50  = (w4*w74);
  /* #917: @47 = (@5*@77) */
  w47  = (w5*w77);
  /* #918: @50 = (@50-@47) */
  w50 -= w47;
  /* #919: @47 = (@6*@68) */
  w47  = (w6*w68);
  /* #920: @50 = (@50-@47) */
  w50 -= w47;
  /* #921: @47 = (@7*@76) */
  w47  = (w7*w76);
  /* #922: @50 = (@50-@47) */
  w50 -= w47;
  /* #923: @47 = (@5*@74) */
  w47  = (w5*w74);
  /* #924: @75 = (@4*@77) */
  w75  = (w4*w77);
  /* #925: @47 = (@47+@75) */
  w47 += w75;
  /* #926: @75 = (@7*@68) */
  w75  = (w7*w68);
  /* #927: @47 = (@47+@75) */
  w47 += w75;
  /* #928: @75 = (@6*@76) */
  w75  = (w6*w76);
  /* #929: @47 = (@47-@75) */
  w47 -= w75;
  /* #930: @75 = (@6*@74) */
  w75  = (w6*w74);
  /* #931: @78 = (@7*@77) */
  w78  = (w7*w77);
  /* #932: @75 = (@75-@78) */
  w75 -= w78;
  /* #933: @78 = (@4*@68) */
  w78  = (w4*w68);
  /* #934: @75 = (@75+@78) */
  w75 += w78;
  /* #935: @78 = (@5*@76) */
  w78  = (w5*w76);
  /* #936: @75 = (@75+@78) */
  w75 += w78;
  /* #937: @74 = (@7*@74) */
  w74  = (w7*w74);
  /* #938: @77 = (@6*@77) */
  w77  = (w6*w77);
  /* #939: @74 = (@74+@77) */
  w74 += w77;
  /* #940: @68 = (@5*@68) */
  w68  = (w5*w68);
  /* #941: @74 = (@74-@68) */
  w74 -= w68;
  /* #942: @76 = (@4*@76) */
  w76  = (w4*w76);
  /* #943: @74 = (@74+@76) */
  w74 += w76;
  /* #944: @26 = vertcat(@50, @47, @75, @74) */
  rr=w26;
  *rr++ = w50;
  *rr++ = w47;
  *rr++ = w75;
  *rr++ = w74;
  /* #945: @63 = (@12*@26) */
  for (i=0, rr=w63, cs=w26; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #946: @26 = (@13*@26) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #947: @63 = (@63-@26) */
  for (i=0, rr=w63, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #948: @1 = @63[1:4] */
  for (rr=w1, ss=w63+1; ss!=w63+4; ss+=1) *rr++ = *ss;
  /* #949: @13 = dot(@31, @1) */
  w13 = casadi_dot(3, w31, w1);
  /* #950: @13 = (@13/@14) */
  w13 /= w14;
  /* #951: @12 = (@13/@3) */
  w12  = (w13/w3);
  /* #952: @18 = (@18*@13) */
  w18 *= w13;
  /* #953: @50 = @63[0] */
  for (rr=(&w50), ss=w63+0; ss!=w63+1; ss+=1) *rr++ = *ss;
  /* #954: @43 = (@43*@50) */
  w43 *= w50;
  /* #955: @18 = (@18+@43) */
  w18 += w43;
  /* #956: @64 = (@64*@18) */
  w64 *= w18;
  /* #957: @12 = (@12-@64) */
  w12 -= w64;
  /* #958: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #959: @40 = zeros(1x3) */
  casadi_clear(w40, 3);
  /* #960: @69 = (2.*@1) */
  for (i=0, rr=w69, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #961: @41 = (@9*@69) */
  for (i=0, rr=w41, cs=w69; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #962: @15 = (@15*@13) */
  w15 *= w13;
  /* #963: @65 = (@65*@50) */
  w65 *= w50;
  /* #964: @15 = (@15-@65) */
  w15 -= w65;
  /* #965: @20 = (@32*@15) */
  for (i=0, rr=w20, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w15);
  /* #966: @41 = (@41+@20) */
  for (i=0, rr=w41, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #967: @41 = (@41/@14) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w14;
  /* #968: @33 = (@33*@13) */
  for (i=0, rr=w33; i<3; ++i) (*rr++) *= w13;
  /* #969: @41 = (@41-@33) */
  for (i=0, rr=w41, cs=w33; i<3; ++i) (*rr++) -= (*cs++);
  /* #970: @33 = @41' */
  casadi_copy(w41, 3, w33);
  /* #971: @40 = mac(@33,@35,@40) */
  for (i=0, rr=w40; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #972: @40 = @40' */
  /* #973: @33 = zeros(1x3) */
  casadi_clear(w33, 3);
  /* #974: @20 = @41' */
  casadi_copy(w41, 3, w20);
  /* #975: @33 = mac(@20,@38,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w38+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #976: @33 = @33' */
  /* #977: @40 = (@40+@33) */
  for (i=0, rr=w40, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #978: @33 = (@40/@14) */
  for (i=0, rr=w33, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #979: @70 = (@70*@13) */
  for (i=0, rr=w70; i<3; ++i) (*rr++) *= w13;
  /* #980: @33 = (@33-@70) */
  for (i=0, rr=w33, cs=w70; i<3; ++i) (*rr++) -= (*cs++);
  /* #981: @65 = dot(@32, @33) */
  w65 = casadi_dot(3, w32, w33);
  /* #982: @64 = dot(@69, @34) */
  w64 = casadi_dot(3, w69, w34);
  /* #983: @65 = (@65+@64) */
  w65 += w64;
  /* #984: @2 = (@2*@65) */
  w2 *= w65;
  /* #985: @12 = (@12+@2) */
  w12 += w2;
  /* #986: @12 = (-@12) */
  w12 = (- w12 );
  /* #987: (@57[0] += @12) */
  for (rr=w57+0, ss=(&w12); rr!=w57+1; rr+=1) *rr += *ss++;
  /* #988: @12 = dot(@39, @40) */
  w12 = casadi_dot(3, w39, w40);
  /* #989: @41 = (@41/@14) */
  for (i=0, rr=w41; i<3; ++i) (*rr++) /= w14;
  /* #990: @37 = (@37*@13) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w13;
  /* #991: @41 = (@41-@37) */
  for (i=0, rr=w41, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #992: @41 = (-@41) */
  for (i=0, rr=w41, cs=w41; i<3; ++i) *rr++ = (- *cs++ );
  /* #993: @2 = dot(@41, @22) */
  w2 = casadi_dot(3, w41, w22);
  /* #994: @12 = (@12+@2) */
  w12 += w2;
  /* #995: @50 = (@50/@3) */
  w50 /= w3;
  /* #996: @72 = (@72*@18) */
  w72 *= w18;
  /* #997: @50 = (@50-@72) */
  w50 -= w72;
  /* #998: @0 = (@0*@50) */
  w0 *= w50;
  /* #999: @16 = (@16*@65) */
  w16 *= w65;
  /* #1000: @0 = (@0+@16) */
  w0 += w16;
  /* #1001: @12 = (@12+@0) */
  w12 += w0;
  /* #1002: @12 = (@12/@14) */
  w12 /= w14;
  /* #1003: @42 = (@42*@13) */
  w42 *= w13;
  /* #1004: @12 = (@12-@42) */
  w12 -= w42;
  /* #1005: @31 = (@31*@12) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) *= w12;
  /* #1006: @1 = (@10*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #1007: @31 = (@31+@1) */
  for (i=0, rr=w31, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #1008: @34 = (@34*@15) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) *= w15;
  /* #1009: @33 = (@9*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #1010: @34 = (@34+@33) */
  for (i=0, rr=w34, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #1011: @34 = (2.*@34) */
  for (i=0, rr=w34, cs=w34; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1012: @31 = (@31+@34) */
  for (i=0, rr=w31, cs=w34; i<3; ++i) (*rr++) += (*cs++);
  /* #1013: (@57[1:4] += @31) */
  for (rr=w57+1, ss=w31; rr!=w57+4; rr+=1) *rr += *ss++;
  /* #1014: @63 = (@11*@57) */
  for (i=0, rr=w63, cs=w57; i<4; ++i) (*rr++)  = (w11*(*cs++));
  /* #1015: @57 = (@17*@57) */
  for (i=0, rr=w57, cs=w57; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #1016: @63 = (@63-@57) */
  for (i=0, rr=w63, cs=w57; i<4; ++i) (*rr++) -= (*cs++);
  /* #1017: {@17, @11, @9, @15} = vertsplit(@63) */
  w17 = w63[0];
  w11 = w63[1];
  w9 = w63[2];
  w15 = w63[3];
  /* #1018: @10 = (@7*@15) */
  w10  = (w7*w15);
  /* #1019: @12 = (@6*@9) */
  w12  = (w6*w9);
  /* #1020: @10 = (@10+@12) */
  w10 += w12;
  /* #1021: @12 = (@5*@11) */
  w12  = (w5*w11);
  /* #1022: @10 = (@10+@12) */
  w10 += w12;
  /* #1023: @12 = (@4*@17) */
  w12  = (w4*w17);
  /* #1024: @10 = (@10+@12) */
  w10 += w12;
  /* #1025: @12 = (@6*@15) */
  w12  = (w6*w15);
  /* #1026: @42 = (@7*@9) */
  w42  = (w7*w9);
  /* #1027: @12 = (@12-@42) */
  w12 -= w42;
  /* #1028: @42 = (@4*@11) */
  w42  = (w4*w11);
  /* #1029: @12 = (@12+@42) */
  w12 += w42;
  /* #1030: @42 = (@5*@17) */
  w42  = (w5*w17);
  /* #1031: @12 = (@12-@42) */
  w12 -= w42;
  /* #1032: @42 = (@4*@9) */
  w42  = (w4*w9);
  /* #1033: @13 = (@5*@15) */
  w13  = (w5*w15);
  /* #1034: @42 = (@42-@13) */
  w42 -= w13;
  /* #1035: @13 = (@7*@11) */
  w13  = (w7*w11);
  /* #1036: @42 = (@42+@13) */
  w42 += w13;
  /* #1037: @13 = (@6*@17) */
  w13  = (w6*w17);
  /* #1038: @42 = (@42-@13) */
  w42 -= w13;
  /* #1039: @4 = (@4*@15) */
  w4 *= w15;
  /* #1040: @5 = (@5*@9) */
  w5 *= w9;
  /* #1041: @4 = (@4+@5) */
  w4 += w5;
  /* #1042: @6 = (@6*@11) */
  w6 *= w11;
  /* #1043: @4 = (@4-@6) */
  w4 -= w6;
  /* #1044: @7 = (@7*@17) */
  w7 *= w17;
  /* #1045: @4 = (@4-@7) */
  w4 -= w7;
  /* #1046: @63 = vertcat(@10, @12, @42, @4) */
  rr=w63;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w42;
  *rr++ = w4;
  /* #1047: @10 = dot(@30, @63) */
  w10 = casadi_dot(4, w30, w63);
  /* #1048: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w8;
  /* #1049: @24 = (@24*@51) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) *= w51;
  /* #1050: @62 = (@62-@24) */
  for (i=0, rr=w62, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #1051: @62 = (-@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) *rr++ = (- *cs++ );
  /* #1052: @12 = dot(@62, @29) */
  w12 = casadi_dot(4, w62, w29);
  /* #1053: @10 = (@10+@12) */
  w10 += w12;
  /* #1054: @10 = (@10/@8) */
  w10 /= w8;
  /* #1055: @73 = (@73*@51) */
  w73 *= w51;
  /* #1056: @10 = (@10-@73) */
  w10 -= w73;
  /* #1057: @28 = (@28*@10) */
  for (i=0, rr=w28; i<4; ++i) (*rr++) *= w10;
  /* #1058: @45 = (@45*@52) */
  w45 *= w52;
  /* #1059: @62 = dense(@45) */
  casadi_densify((&w45), casadi_s21, w62, 0);
  /* #1060: @28 = (@28+@62) */
  for (i=0, rr=w28, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #1061: (@21[6:10] += @28) */
  for (rr=w21+6, ss=w28; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #1062: {@45, @52, @10, @73, @12, @42, @4, @7, @17, @6, @11, @5, @9} = vertsplit(@21) */
  w45 = w21[0];
  w52 = w21[1];
  w10 = w21[2];
  w73 = w21[3];
  w12 = w21[4];
  w42 = w21[5];
  w4 = w21[6];
  w7 = w21[7];
  w17 = w21[8];
  w6 = w21[9];
  w11 = w21[10];
  w5 = w21[11];
  w9 = w21[12];
  /* #1063: @63 = (@63/@8) */
  for (i=0, rr=w63; i<4; ++i) (*rr++) /= w8;
  /* #1064: @25 = (@25*@51) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) *= w51;
  /* #1065: @63 = (@63-@25) */
  for (i=0, rr=w63, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #1066: {@51, @8, @15, @13} = vertsplit(@63) */
  w51 = w63[0];
  w8 = w63[1];
  w15 = w63[2];
  w13 = w63[3];
  /* #1067: @51 = (@51+@4) */
  w51 += w4;
  /* #1068: @7 = (@7-@8) */
  w7 -= w8;
  /* #1069: @17 = (@17-@15) */
  w17 -= w15;
  /* #1070: @6 = (@6-@13) */
  w6 -= w13;
  /* #1071: @19 = vertcat(@48, @54, @55, @67, @45, @52, @10, @73, @12, @42, @51, @7, @17, @6, @11, @5, @9) */
  rr=w19;
  *rr++ = w48;
  *rr++ = w54;
  *rr++ = w55;
  *rr++ = w67;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w10;
  *rr++ = w73;
  *rr++ = w12;
  *rr++ = w42;
  *rr++ = w51;
  *rr++ = w7;
  *rr++ = w17;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w5;
  *rr++ = w9;
  /* #1072: @85 = @19[:20:10;:4] */
  for (rr=w85, ss=w19+0; ss!=w19+20; ss+=10) for (tt=ss+0; tt!=ss+4; tt+=1) *rr++ = *tt;
  /* #1073: (@56[:50:25;12:16] = @85) */
  for (rr=w56+0, ss=w85; rr!=w56+50; rr+=25) for (tt=rr+12; tt!=rr+16; tt+=1) *tt = *ss++;
  /* #1074: @85 = @19[:20:10;:4] */
  for (rr=w85, ss=w19+0; ss!=w19+20; ss+=10) for (tt=ss+0; tt!=ss+4; tt+=1) *rr++ = *tt;
  /* #1075: (@56[:50:25;3:19:4] = @85) */
  for (rr=w56+0, ss=w85; rr!=w56+50; rr+=25) for (tt=rr+3; tt!=rr+19; tt+=4) *tt = *ss++;
  /* #1076: @86 = @56' */
  casadi_trans(w56,casadi_s22, w86, casadi_s22, iw);
  /* #1077: output[2][0] = @86 */
  casadi_copy(w86, 41, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s23;
    case 1: return casadi_s24;
    case 2: return casadi_s25;
    case 3: return casadi_s26;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s27;
    case 1: return casadi_s26;
    case 2: return casadi_s22;
    case 3: return casadi_s25;
    case 4: return casadi_s28;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 22;
  if (sz_iw) *sz_iw = 18;
  if (sz_w) *sz_w = 339;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
