/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};

/* Drone_ode_complete_cost_ext_cost_e_fun_jac:(i0[13],i1[],i2[],i3[17])->(o0,o1[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55, *w23=w+58, *w24=w+67, *w25=w+71, *w26=w+75, *w27=w+79, *w28=w+83, *w29=w+86, *w30=w+89, *w31=w+92, *w32=w+95, *w33=w+104, *w34=w+107;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 1 */
  w2 = 1.;
  /* #40: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #41: @2 = 1 */
  w2 = 1.;
  /* #42: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #43: @2 = 1 */
  w2 = 1.;
  /* #44: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #45: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #46: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #47: @2 = 0 */
  w2 = 0.;
  /* #48: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #49: @9 = (-@9) */
  w9 = (- w9 );
  /* #50: @10 = (-@10) */
  w10 = (- w10 );
  /* #51: @11 = (-@11) */
  w11 = (- w11 );
  /* #52: @24 = vertcat(@8, @9, @10, @11) */
  rr=w24;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #53: @25 = @21[6:10] */
  for (rr=w25, ss=w21+6; ss!=w21+10; ss+=1) *rr++ = *ss;
  /* #54: @8 = ||@25||_F */
  w8 = sqrt(casadi_dot(4, w25, w25));
  /* #55: @24 = (@24/@8) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w8;
  /* #56: {@9, @10, @11, @3} = vertsplit(@24) */
  w9 = w24[0];
  w10 = w24[1];
  w11 = w24[2];
  w3 = w24[3];
  /* #57: @26 = @19[6:10] */
  for (rr=w26, ss=w19+6; ss!=w19+10; ss+=1) *rr++ = *ss;
  /* #58: {@4, @5, @6, @7} = vertsplit(@26) */
  w4 = w26[0];
  w5 = w26[1];
  w6 = w26[2];
  w7 = w26[3];
  /* #59: @12 = (@9*@4) */
  w12  = (w9*w4);
  /* #60: @13 = (@10*@5) */
  w13  = (w10*w5);
  /* #61: @12 = (@12-@13) */
  w12 -= w13;
  /* #62: @13 = (@11*@6) */
  w13  = (w11*w6);
  /* #63: @12 = (@12-@13) */
  w12 -= w13;
  /* #64: @13 = (@3*@7) */
  w13  = (w3*w7);
  /* #65: @12 = (@12-@13) */
  w12 -= w13;
  /* #66: @13 = 0 */
  w13 = 0.;
  /* #67: @13 = (@12<@13) */
  w13  = (w12<w13);
  /* #68: @14 = (@9*@5) */
  w14  = (w9*w5);
  /* #69: @15 = (@10*@4) */
  w15  = (w10*w4);
  /* #70: @14 = (@14+@15) */
  w14 += w15;
  /* #71: @15 = (@11*@7) */
  w15  = (w11*w7);
  /* #72: @14 = (@14+@15) */
  w14 += w15;
  /* #73: @15 = (@3*@6) */
  w15  = (w3*w6);
  /* #74: @14 = (@14-@15) */
  w14 -= w15;
  /* #75: @15 = (@9*@6) */
  w15  = (w9*w6);
  /* #76: @16 = (@10*@7) */
  w16  = (w10*w7);
  /* #77: @15 = (@15-@16) */
  w15 -= w16;
  /* #78: @16 = (@11*@4) */
  w16  = (w11*w4);
  /* #79: @15 = (@15+@16) */
  w15 += w16;
  /* #80: @16 = (@3*@5) */
  w16  = (w3*w5);
  /* #81: @15 = (@15+@16) */
  w15 += w16;
  /* #82: @9 = (@9*@7) */
  w9 *= w7;
  /* #83: @10 = (@10*@6) */
  w10 *= w6;
  /* #84: @9 = (@9+@10) */
  w9 += w10;
  /* #85: @11 = (@11*@5) */
  w11 *= w5;
  /* #86: @9 = (@9-@11) */
  w9 -= w11;
  /* #87: @3 = (@3*@4) */
  w3 *= w4;
  /* #88: @9 = (@9+@3) */
  w9 += w3;
  /* #89: @26 = vertcat(@12, @14, @15, @9) */
  rr=w26;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w9;
  /* #90: @27 = (-@26) */
  for (i=0, rr=w27, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #91: @27 = (@13?@27:0) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w13?(*cs++):0);
  /* #92: @12 = (!@13) */
  w12 = (! w13 );
  /* #93: @26 = (@12?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w12?(*cs++):0);
  /* #94: @27 = (@27+@26) */
  for (i=0, rr=w27, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #95: @28 = @27[1:4] */
  for (rr=w28, ss=w27+1; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #96: @29 = (2.*@28) */
  for (i=0, rr=w29, cs=w28; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #97: @14 = ||@28||_F */
  w14 = sqrt(casadi_dot(3, w28, w28));
  /* #98: @15 = @27[0] */
  for (rr=(&w15), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #99: @9 = atan2(@14,@15) */
  w9  = atan2(w14,w15);
  /* #100: @30 = (@29*@9) */
  for (i=0, rr=w30, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w9);
  /* #101: @30 = (@30/@14) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w14;
  /* #102: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #103: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #104: @3 = 1 */
  w3 = 1.;
  /* #105: (@32[0] = @3) */
  for (rr=w32+0, ss=(&w3); rr!=w32+1; rr+=1) *rr = *ss++;
  /* #106: @3 = 1 */
  w3 = 1.;
  /* #107: (@32[4] = @3) */
  for (rr=w32+4, ss=(&w3); rr!=w32+5; rr+=1) *rr = *ss++;
  /* #108: @3 = 1 */
  w3 = 1.;
  /* #109: (@32[8] = @3) */
  for (rr=w32+8, ss=(&w3); rr!=w32+9; rr+=1) *rr = *ss++;
  /* #110: @22 = mac(@31,@32,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #111: @2 = mac(@22,@30,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #112: @0 = (@0+@2) */
  w0 += w2;
  /* #113: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #114: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #115: @24 = (@24/@8) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w8;
  /* #116: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #117: @0 = 1 */
  w0 = 1.;
  /* #118: @12 = (@12?@0:0) */
  w12  = (w12?w0:0);
  /* #119: @27 = zeros(4x1) */
  casadi_clear(w27, 4);
  /* #120: @0 = sq(@14) */
  w0 = casadi_sq( w14 );
  /* #121: @2 = sq(@15) */
  w2 = casadi_sq( w15 );
  /* #122: @0 = (@0+@2) */
  w0 += w2;
  /* #123: @2 = (@14/@0) */
  w2  = (w14/w0);
  /* #124: @22 = @22' */
  /* #125: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #126: @33 = @30' */
  casadi_copy(w30, 3, w33);
  /* #127: @34 = @32' */
  for (i=0, rr=w34, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #128: @31 = mac(@33,@34,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #129: @31 = @31' */
  /* #130: @22 = (@22+@31) */
  for (i=0, rr=w22, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #131: @31 = (@22/@14) */
  for (i=0, rr=w31, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #132: @3 = dot(@29, @31) */
  w3 = casadi_dot(3, w29, w31);
  /* #133: @2 = (@2*@3) */
  w2 *= w3;
  /* #134: @2 = (-@2) */
  w2 = (- w2 );
  /* #135: (@27[0] += @2) */
  for (rr=w27+0, ss=(&w2); rr!=w27+1; rr+=1) *rr += *ss++;
  /* #136: @30 = (@30/@14) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w14;
  /* #137: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) *rr++ = (- *cs++ );
  /* #138: @2 = dot(@30, @22) */
  w2 = casadi_dot(3, w30, w22);
  /* #139: @15 = (@15/@0) */
  w15 /= w0;
  /* #140: @15 = (@15*@3) */
  w15 *= w3;
  /* #141: @2 = (@2+@15) */
  w2 += w15;
  /* #142: @2 = (@2/@14) */
  w2 /= w14;
  /* #143: @28 = (@2*@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #144: @31 = (@9*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #145: @31 = (2.*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #146: @28 = (@28+@31) */
  for (i=0, rr=w28, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #147: (@27[1:4] += @28) */
  for (rr=w27+1, ss=w28; rr!=w27+4; rr+=1) *rr += *ss++;
  /* #148: @26 = (@12*@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #149: @12 = 1 */
  w12 = 1.;
  /* #150: @13 = (@13?@12:0) */
  w13  = (w13?w12:0);
  /* #151: @27 = (@13*@27) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #152: @26 = (@26-@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) (*rr++) -= (*cs++);
  /* #153: {@13, @12, @9, @2} = vertsplit(@26) */
  w13 = w26[0];
  w12 = w26[1];
  w9 = w26[2];
  w2 = w26[3];
  /* #154: @14 = (@7*@2) */
  w14  = (w7*w2);
  /* #155: @15 = (@6*@9) */
  w15  = (w6*w9);
  /* #156: @14 = (@14+@15) */
  w14 += w15;
  /* #157: @15 = (@5*@12) */
  w15  = (w5*w12);
  /* #158: @14 = (@14+@15) */
  w14 += w15;
  /* #159: @15 = (@4*@13) */
  w15  = (w4*w13);
  /* #160: @14 = (@14+@15) */
  w14 += w15;
  /* #161: @15 = (@6*@2) */
  w15  = (w6*w2);
  /* #162: @3 = (@7*@9) */
  w3  = (w7*w9);
  /* #163: @15 = (@15-@3) */
  w15 -= w3;
  /* #164: @3 = (@4*@12) */
  w3  = (w4*w12);
  /* #165: @15 = (@15+@3) */
  w15 += w3;
  /* #166: @3 = (@5*@13) */
  w3  = (w5*w13);
  /* #167: @15 = (@15-@3) */
  w15 -= w3;
  /* #168: @3 = (@4*@9) */
  w3  = (w4*w9);
  /* #169: @0 = (@5*@2) */
  w0  = (w5*w2);
  /* #170: @3 = (@3-@0) */
  w3 -= w0;
  /* #171: @0 = (@7*@12) */
  w0  = (w7*w12);
  /* #172: @3 = (@3+@0) */
  w3 += w0;
  /* #173: @0 = (@6*@13) */
  w0  = (w6*w13);
  /* #174: @3 = (@3-@0) */
  w3 -= w0;
  /* #175: @4 = (@4*@2) */
  w4 *= w2;
  /* #176: @5 = (@5*@9) */
  w5 *= w9;
  /* #177: @4 = (@4+@5) */
  w4 += w5;
  /* #178: @6 = (@6*@12) */
  w6 *= w12;
  /* #179: @4 = (@4-@6) */
  w4 -= w6;
  /* #180: @7 = (@7*@13) */
  w7 *= w13;
  /* #181: @4 = (@4-@7) */
  w4 -= w7;
  /* #182: @26 = vertcat(@14, @15, @3, @4) */
  rr=w26;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w3;
  *rr++ = w4;
  /* #183: @14 = dot(@24, @26) */
  w14 = casadi_dot(4, w24, w26);
  /* #184: @14 = (@14/@8) */
  w14 /= w8;
  /* #185: @25 = (@14*@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #186: (@21[6:10] += @25) */
  for (rr=w21+6, ss=w25; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #187: @1 = @1' */
  /* #188: @28 = zeros(1x3) */
  casadi_clear(w28, 3);
  /* #189: @20 = @20' */
  /* #190: @34 = @23' */
  for (i=0, rr=w34, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #191: @28 = mac(@20,@34,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #192: @28 = @28' */
  /* #193: @1 = (@1+@28) */
  for (i=0, rr=w1, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #194: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #195: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #196: {@14, @15, @3, @4, @7, @13, @6, @12, @5, @9, @2, @0, @11} = vertsplit(@21) */
  w14 = w21[0];
  w15 = w21[1];
  w3 = w21[2];
  w4 = w21[3];
  w7 = w21[4];
  w13 = w21[5];
  w6 = w21[6];
  w12 = w21[7];
  w5 = w21[8];
  w9 = w21[9];
  w2 = w21[10];
  w0 = w21[11];
  w11 = w21[12];
  /* #197: output[1][0] = @14 */
  if (res[1]) res[1][0] = w14;
  /* #198: output[1][1] = @15 */
  if (res[1]) res[1][1] = w15;
  /* #199: output[1][2] = @3 */
  if (res[1]) res[1][2] = w3;
  /* #200: output[1][3] = @4 */
  if (res[1]) res[1][3] = w4;
  /* #201: output[1][4] = @7 */
  if (res[1]) res[1][4] = w7;
  /* #202: output[1][5] = @13 */
  if (res[1]) res[1][5] = w13;
  /* #203: @26 = (@26/@8) */
  for (i=0, rr=w26; i<4; ++i) (*rr++) /= w8;
  /* #204: {@8, @13, @7, @4} = vertsplit(@26) */
  w8 = w26[0];
  w13 = w26[1];
  w7 = w26[2];
  w4 = w26[3];
  /* #205: @8 = (@8+@6) */
  w8 += w6;
  /* #206: output[1][6] = @8 */
  if (res[1]) res[1][6] = w8;
  /* #207: @12 = (@12-@13) */
  w12 -= w13;
  /* #208: output[1][7] = @12 */
  if (res[1]) res[1][7] = w12;
  /* #209: @5 = (@5-@7) */
  w5 -= w7;
  /* #210: output[1][8] = @5 */
  if (res[1]) res[1][8] = w5;
  /* #211: @9 = (@9-@4) */
  w9 -= w4;
  /* #212: output[1][9] = @9 */
  if (res[1]) res[1][9] = w9;
  /* #213: output[1][10] = @2 */
  if (res[1]) res[1][10] = w2;
  /* #214: output[1][11] = @0 */
  if (res[1]) res[1][11] = w0;
  /* #215: output[1][12] = @11 */
  if (res[1]) res[1][12] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_e_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 116;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
