/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s2[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[7] = {0, 1, 2, 6, 7, 8, 9};
static const casadi_int casadi_s5[7] = {0, 1, 2, 9, 10, 11, 12};
static const casadi_int casadi_s6[7] = {0, 3, 6, 9, 13, 17, 21};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s9[7] = {3, 4, 5, 13, 14, 15, 16};
static const casadi_int casadi_s10[7] = {1, 4, 7, 10, 14, 18, 22};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s13[7] = {6, 7, 8, 17, 18, 19, 20};
static const casadi_int casadi_s14[7] = {2, 5, 8, 11, 15, 19, 23};
static const casadi_int casadi_s15[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s16[41] = {13, 13, 0, 3, 6, 9, 9, 9, 9, 13, 17, 21, 25, 25, 25, 25, 0, 1, 2, 0, 1, 2, 0, 1, 2, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9};
static const casadi_int casadi_s17[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s18[3] = {0, 0, 0};
static const casadi_int casadi_s19[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s20[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s21[16] = {0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[],i2[],i3[17])->(o0,o1[13],o2[13x13,25nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+39, *w21=w+42, *w22=w+55, *w23=w+58, *w24=w+67, *w25=w+71, *w26=w+75, *w27=w+79, *w28=w+83, *w29=w+86, *w30=w+89, *w31=w+92, *w32=w+95, *w33=w+104, *w34=w+108, *w35=w+111, *w36=w+120, *w37=w+123, *w38=w+126, *w39=w+129, w40, w41, w42, w43, w44, w45, w46, *w47=w+140, w48, w49, w50, w51, w52, w53, *w54=w+155, *w55=w+180, *w56=w+184, *w60=w+192, *w61=w+196, *w62=w+200, *w63=w+204, *w64=w+207, *w65=w+210, w66, w67, w68, w69, w70, w71, w72, w73, w74, w75, w76, *w77=w+224, *w78=w+231, *w79=w+233;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = input[3][16] */
  w18 = arg[3] ? arg[3][16] : 0;
  /* #19: @19 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #20: @20 = @19[:3] */
  for (rr=w20, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #21: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #22: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #23: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #24: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #25: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #26: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #27: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #28: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #29: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #30: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #31: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #32: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #33: @14 = input[0][12] */
  w14 = arg[0] ? arg[0][12] : 0;
  /* #34: @21 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14) */
  rr=w21;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #35: @22 = @21[:3] */
  for (rr=w22, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #36: @20 = (@20-@22) */
  for (i=0, rr=w20, cs=w22; i<3; ++i) (*rr++) -= (*cs++);
  /* #37: @22 = @20' */
  casadi_copy(w20, 3, w22);
  /* #38: @23 = zeros(3x3) */
  casadi_clear(w23, 9);
  /* #39: @2 = 1 */
  w2 = 1.;
  /* #40: (@23[0] = @2) */
  for (rr=w23+0, ss=(&w2); rr!=w23+1; rr+=1) *rr = *ss++;
  /* #41: @2 = 1 */
  w2 = 1.;
  /* #42: (@23[4] = @2) */
  for (rr=w23+4, ss=(&w2); rr!=w23+5; rr+=1) *rr = *ss++;
  /* #43: @2 = 1 */
  w2 = 1.;
  /* #44: (@23[8] = @2) */
  for (rr=w23+8, ss=(&w2); rr!=w23+9; rr+=1) *rr = *ss++;
  /* #45: @1 = mac(@22,@23,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #46: @0 = mac(@1,@20,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #47: @2 = 0 */
  w2 = 0.;
  /* #48: @22 = zeros(1x3) */
  casadi_clear(w22, 3);
  /* #49: @9 = (-@9) */
  w9 = (- w9 );
  /* #50: @10 = (-@10) */
  w10 = (- w10 );
  /* #51: @11 = (-@11) */
  w11 = (- w11 );
  /* #52: @24 = vertcat(@8, @9, @10, @11) */
  rr=w24;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  /* #53: @25 = @21[6:10] */
  for (rr=w25, ss=w21+6; ss!=w21+10; ss+=1) *rr++ = *ss;
  /* #54: @8 = ||@25||_F */
  w8 = sqrt(casadi_dot(4, w25, w25));
  /* #55: @24 = (@24/@8) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w8;
  /* #56: {@9, @10, @11, @3} = vertsplit(@24) */
  w9 = w24[0];
  w10 = w24[1];
  w11 = w24[2];
  w3 = w24[3];
  /* #57: @26 = @19[6:10] */
  for (rr=w26, ss=w19+6; ss!=w19+10; ss+=1) *rr++ = *ss;
  /* #58: {@4, @5, @6, @7} = vertsplit(@26) */
  w4 = w26[0];
  w5 = w26[1];
  w6 = w26[2];
  w7 = w26[3];
  /* #59: @12 = (@9*@4) */
  w12  = (w9*w4);
  /* #60: @13 = (@10*@5) */
  w13  = (w10*w5);
  /* #61: @12 = (@12-@13) */
  w12 -= w13;
  /* #62: @13 = (@11*@6) */
  w13  = (w11*w6);
  /* #63: @12 = (@12-@13) */
  w12 -= w13;
  /* #64: @13 = (@3*@7) */
  w13  = (w3*w7);
  /* #65: @12 = (@12-@13) */
  w12 -= w13;
  /* #66: @13 = 0 */
  w13 = 0.;
  /* #67: @13 = (@12<@13) */
  w13  = (w12<w13);
  /* #68: @14 = (@9*@5) */
  w14  = (w9*w5);
  /* #69: @15 = (@10*@4) */
  w15  = (w10*w4);
  /* #70: @14 = (@14+@15) */
  w14 += w15;
  /* #71: @15 = (@11*@7) */
  w15  = (w11*w7);
  /* #72: @14 = (@14+@15) */
  w14 += w15;
  /* #73: @15 = (@3*@6) */
  w15  = (w3*w6);
  /* #74: @14 = (@14-@15) */
  w14 -= w15;
  /* #75: @15 = (@9*@6) */
  w15  = (w9*w6);
  /* #76: @16 = (@10*@7) */
  w16  = (w10*w7);
  /* #77: @15 = (@15-@16) */
  w15 -= w16;
  /* #78: @16 = (@11*@4) */
  w16  = (w11*w4);
  /* #79: @15 = (@15+@16) */
  w15 += w16;
  /* #80: @16 = (@3*@5) */
  w16  = (w3*w5);
  /* #81: @15 = (@15+@16) */
  w15 += w16;
  /* #82: @9 = (@9*@7) */
  w9 *= w7;
  /* #83: @10 = (@10*@6) */
  w10 *= w6;
  /* #84: @9 = (@9+@10) */
  w9 += w10;
  /* #85: @11 = (@11*@5) */
  w11 *= w5;
  /* #86: @9 = (@9-@11) */
  w9 -= w11;
  /* #87: @3 = (@3*@4) */
  w3 *= w4;
  /* #88: @9 = (@9+@3) */
  w9 += w3;
  /* #89: @26 = vertcat(@12, @14, @15, @9) */
  rr=w26;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w9;
  /* #90: @27 = (-@26) */
  for (i=0, rr=w27, cs=w26; i<4; ++i) *rr++ = (- *cs++ );
  /* #91: @27 = (@13?@27:0) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) (*rr++)  = (w13?(*cs++):0);
  /* #92: @12 = (!@13) */
  w12 = (! w13 );
  /* #93: @26 = (@12?@26:0) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w12?(*cs++):0);
  /* #94: @27 = (@27+@26) */
  for (i=0, rr=w27, cs=w26; i<4; ++i) (*rr++) += (*cs++);
  /* #95: @28 = @27[1:4] */
  for (rr=w28, ss=w27+1; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #96: @29 = (2.*@28) */
  for (i=0, rr=w29, cs=w28; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #97: @14 = ||@28||_F */
  w14 = sqrt(casadi_dot(3, w28, w28));
  /* #98: @15 = @27[0] */
  for (rr=(&w15), ss=w27+0; ss!=w27+1; ss+=1) *rr++ = *ss;
  /* #99: @9 = atan2(@14,@15) */
  w9  = atan2(w14,w15);
  /* #100: @30 = (@29*@9) */
  for (i=0, rr=w30, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w9);
  /* #101: @30 = (@30/@14) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w14;
  /* #102: @31 = @30' */
  casadi_copy(w30, 3, w31);
  /* #103: @32 = zeros(3x3) */
  casadi_clear(w32, 9);
  /* #104: @3 = 1 */
  w3 = 1.;
  /* #105: (@32[0] = @3) */
  for (rr=w32+0, ss=(&w3); rr!=w32+1; rr+=1) *rr = *ss++;
  /* #106: @3 = 1 */
  w3 = 1.;
  /* #107: (@32[4] = @3) */
  for (rr=w32+4, ss=(&w3); rr!=w32+5; rr+=1) *rr = *ss++;
  /* #108: @3 = 1 */
  w3 = 1.;
  /* #109: (@32[8] = @3) */
  for (rr=w32+8, ss=(&w3); rr!=w32+9; rr+=1) *rr = *ss++;
  /* #110: @22 = mac(@31,@32,@22) */
  for (i=0, rr=w22; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w31+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #111: @2 = mac(@22,@30,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #112: @0 = (@0+@2) */
  w0 += w2;
  /* #113: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #114: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #115: @27 = (@24/@8) */
  for (i=0, rr=w27, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)/w8);
  /* #116: @26 = (-@27) */
  for (i=0, rr=w26, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #117: @0 = 1 */
  w0 = 1.;
  /* #118: @0 = (@12?@0:0) */
  w0  = (w12?w0:0);
  /* #119: @33 = zeros(4x1) */
  casadi_clear(w33, 4);
  /* #120: @2 = sq(@14) */
  w2 = casadi_sq( w14 );
  /* #121: @3 = sq(@15) */
  w3 = casadi_sq( w15 );
  /* #122: @2 = (@2+@3) */
  w2 += w3;
  /* #123: @3 = (@14/@2) */
  w3  = (w14/w2);
  /* #124: @22 = @22' */
  /* #125: @31 = zeros(1x3) */
  casadi_clear(w31, 3);
  /* #126: @34 = @30' */
  casadi_copy(w30, 3, w34);
  /* #127: @35 = @32' */
  for (i=0, rr=w35, cs=w32; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #128: @31 = mac(@34,@35,@31) */
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w34+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #129: @31 = @31' */
  /* #130: @22 = (@22+@31) */
  for (i=0, rr=w22, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #131: @31 = (@22/@14) */
  for (i=0, rr=w31, cr=w22; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #132: @11 = dot(@29, @31) */
  w11 = casadi_dot(3, w29, w31);
  /* #133: @10 = (@3*@11) */
  w10  = (w3*w11);
  /* #134: @10 = (-@10) */
  w10 = (- w10 );
  /* #135: (@33[0] += @10) */
  for (rr=w33+0, ss=(&w10); rr!=w33+1; rr+=1) *rr += *ss++;
  /* #136: @34 = (@30/@14) */
  for (i=0, rr=w34, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #137: @36 = (-@34) */
  for (i=0, rr=w36, cs=w34; i<3; ++i) *rr++ = (- *cs++ );
  /* #138: @10 = dot(@36, @22) */
  w10 = casadi_dot(3, w36, w22);
  /* #139: @16 = (@15/@2) */
  w16  = (w15/w2);
  /* #140: @17 = (@16*@11) */
  w17  = (w16*w11);
  /* #141: @10 = (@10+@17) */
  w10 += w17;
  /* #142: @10 = (@10/@14) */
  w10 /= w14;
  /* #143: @37 = (@10*@28) */
  for (i=0, rr=w37, cs=w28; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #144: @38 = (@9*@31) */
  for (i=0, rr=w38, cs=w31; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #145: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #146: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #147: (@33[1:4] += @37) */
  for (rr=w33+1, ss=w37; rr!=w33+4; rr+=1) *rr += *ss++;
  /* #148: @39 = (@0*@33) */
  for (i=0, rr=w39, cs=w33; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #149: @17 = 1 */
  w17 = 1.;
  /* #150: @17 = (@13?@17:0) */
  w17  = (w13?w17:0);
  /* #151: @33 = (@17*@33) */
  for (i=0, rr=w33, cs=w33; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #152: @39 = (@39-@33) */
  for (i=0, rr=w39, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #153: {@18, @40, @41, @42} = vertsplit(@39) */
  w18 = w39[0];
  w40 = w39[1];
  w41 = w39[2];
  w42 = w39[3];
  /* #154: @43 = (@7*@42) */
  w43  = (w7*w42);
  /* #155: @44 = (@6*@41) */
  w44  = (w6*w41);
  /* #156: @43 = (@43+@44) */
  w43 += w44;
  /* #157: @44 = (@5*@40) */
  w44  = (w5*w40);
  /* #158: @43 = (@43+@44) */
  w43 += w44;
  /* #159: @44 = (@4*@18) */
  w44  = (w4*w18);
  /* #160: @43 = (@43+@44) */
  w43 += w44;
  /* #161: @44 = (@6*@42) */
  w44  = (w6*w42);
  /* #162: @45 = (@7*@41) */
  w45  = (w7*w41);
  /* #163: @44 = (@44-@45) */
  w44 -= w45;
  /* #164: @45 = (@4*@40) */
  w45  = (w4*w40);
  /* #165: @44 = (@44+@45) */
  w44 += w45;
  /* #166: @45 = (@5*@18) */
  w45  = (w5*w18);
  /* #167: @44 = (@44-@45) */
  w44 -= w45;
  /* #168: @45 = (@4*@41) */
  w45  = (w4*w41);
  /* #169: @46 = (@5*@42) */
  w46  = (w5*w42);
  /* #170: @45 = (@45-@46) */
  w45 -= w46;
  /* #171: @46 = (@7*@40) */
  w46  = (w7*w40);
  /* #172: @45 = (@45+@46) */
  w45 += w46;
  /* #173: @46 = (@6*@18) */
  w46  = (w6*w18);
  /* #174: @45 = (@45-@46) */
  w45 -= w46;
  /* #175: @42 = (@4*@42) */
  w42  = (w4*w42);
  /* #176: @41 = (@5*@41) */
  w41  = (w5*w41);
  /* #177: @42 = (@42+@41) */
  w42 += w41;
  /* #178: @40 = (@6*@40) */
  w40  = (w6*w40);
  /* #179: @42 = (@42-@40) */
  w42 -= w40;
  /* #180: @18 = (@7*@18) */
  w18  = (w7*w18);
  /* #181: @42 = (@42-@18) */
  w42 -= w18;
  /* #182: @39 = vertcat(@43, @44, @45, @42) */
  rr=w39;
  *rr++ = w43;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w42;
  /* #183: @43 = dot(@26, @39) */
  w43 = casadi_dot(4, w26, w39);
  /* #184: @43 = (@43/@8) */
  w43 /= w8;
  /* #185: @33 = (@43*@25) */
  for (i=0, rr=w33, cs=w25; i<4; ++i) (*rr++)  = (w43*(*cs++));
  /* #186: (@21[6:10] += @33) */
  for (rr=w21+6, ss=w33; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #187: @1 = @1' */
  /* #188: @37 = zeros(1x3) */
  casadi_clear(w37, 3);
  /* #189: @20 = @20' */
  /* #190: @47 = @23' */
  for (i=0, rr=w47, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #191: @37 = mac(@20,@47,@37) */
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w47+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #192: @37 = @37' */
  /* #193: @1 = (@1+@37) */
  for (i=0, rr=w1, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #194: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #195: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #196: {@44, @45, @42, @18, @40, @41, @46, @48, @49, @50, @51, @52, @53} = vertsplit(@21) */
  w44 = w21[0];
  w45 = w21[1];
  w42 = w21[2];
  w18 = w21[3];
  w40 = w21[4];
  w41 = w21[5];
  w46 = w21[6];
  w48 = w21[7];
  w49 = w21[8];
  w50 = w21[9];
  w51 = w21[10];
  w52 = w21[11];
  w53 = w21[12];
  /* #197: output[1][0] = @44 */
  if (res[1]) res[1][0] = w44;
  /* #198: output[1][1] = @45 */
  if (res[1]) res[1][1] = w45;
  /* #199: output[1][2] = @42 */
  if (res[1]) res[1][2] = w42;
  /* #200: output[1][3] = @18 */
  if (res[1]) res[1][3] = w18;
  /* #201: output[1][4] = @40 */
  if (res[1]) res[1][4] = w40;
  /* #202: output[1][5] = @41 */
  if (res[1]) res[1][5] = w41;
  /* #203: @33 = (@39/@8) */
  for (i=0, rr=w33, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)/w8);
  /* #204: {@41, @40, @18, @42} = vertsplit(@33) */
  w41 = w33[0];
  w40 = w33[1];
  w18 = w33[2];
  w42 = w33[3];
  /* #205: @41 = (@41+@46) */
  w41 += w46;
  /* #206: output[1][6] = @41 */
  if (res[1]) res[1][6] = w41;
  /* #207: @48 = (@48-@40) */
  w48 -= w40;
  /* #208: output[1][7] = @48 */
  if (res[1]) res[1][7] = w48;
  /* #209: @49 = (@49-@18) */
  w49 -= w18;
  /* #210: output[1][8] = @49 */
  if (res[1]) res[1][8] = w49;
  /* #211: @50 = (@50-@42) */
  w50 -= w42;
  /* #212: output[1][9] = @50 */
  if (res[1]) res[1][9] = w50;
  /* #213: output[1][10] = @51 */
  if (res[1]) res[1][10] = w51;
  /* #214: output[1][11] = @52 */
  if (res[1]) res[1][11] = w52;
  /* #215: output[1][12] = @53 */
  if (res[1]) res[1][12] = w53;
  /* #216: @54 = zeros(13x13,25nz) */
  casadi_clear(w54, 25);
  /* #217: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #218: @55 = zeros(4x1) */
  casadi_clear(w55, 4);
  /* #219: @53 = 1 */
  w53 = 1.;
  /* #220: @12 = (@12?@53:0) */
  w12  = (w12?w53:0);
  /* #221: @56 = ones(13x1,8nz) */
  casadi_fill(w56, 8, 1.);
  /* #222: {@53, NULL, NULL, NULL, NULL, NULL, @52, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@56) */
  w53 = w56[0];
  w52 = w56[4];
  /* #223: @57 = 00 */
  /* #224: @58 = 00 */
  /* #225: @59 = 00 */
  /* #226: @51 = vertcat(@52, @57, @58, @59) */
  rr=(&w51);
  *rr++ = w52;
  /* #227: @51 = (@51/@8) */
  w51 /= w8;
  /* #228: @60 = dense(@51) */
  casadi_densify((&w51), casadi_s0, w60, 0);
  /* #229: @24 = (@24/@8) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w8;
  /* #230: @51 = project(@25) */
  casadi_sparsify(w25, (&w51), casadi_s0, 0);
  /* #231: @50 = @52[0] */
  for (rr=(&w50), ss=(&w52)+0; ss!=(&w52)+1; ss+=1) *rr++ = *ss;
  /* #232: @52 = dot(@51, @50) */
  w52 = casadi_dot(1, (&w51), (&w50));
  /* #233: @52 = (@52/@8) */
  w52 /= w8;
  /* #234: @61 = (@24*@52) */
  for (i=0, rr=w61, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w52);
  /* #235: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #236: {@51, @42, @49, @18} = vertsplit(@60) */
  w51 = w60[0];
  w42 = w60[1];
  w49 = w60[2];
  w18 = w60[3];
  /* #237: @48 = (@4*@51) */
  w48  = (w4*w51);
  /* #238: @40 = (@5*@42) */
  w40  = (w5*w42);
  /* #239: @48 = (@48-@40) */
  w48 -= w40;
  /* #240: @40 = (@6*@49) */
  w40  = (w6*w49);
  /* #241: @48 = (@48-@40) */
  w48 -= w40;
  /* #242: @40 = (@7*@18) */
  w40  = (w7*w18);
  /* #243: @48 = (@48-@40) */
  w48 -= w40;
  /* #244: @40 = (@5*@51) */
  w40  = (w5*w51);
  /* #245: @41 = (@4*@42) */
  w41  = (w4*w42);
  /* #246: @40 = (@40+@41) */
  w40 += w41;
  /* #247: @41 = (@7*@49) */
  w41  = (w7*w49);
  /* #248: @40 = (@40+@41) */
  w40 += w41;
  /* #249: @41 = (@6*@18) */
  w41  = (w6*w18);
  /* #250: @40 = (@40-@41) */
  w40 -= w41;
  /* #251: @41 = (@6*@51) */
  w41  = (w6*w51);
  /* #252: @46 = (@7*@42) */
  w46  = (w7*w42);
  /* #253: @41 = (@41-@46) */
  w41 -= w46;
  /* #254: @46 = (@4*@49) */
  w46  = (w4*w49);
  /* #255: @41 = (@41+@46) */
  w41 += w46;
  /* #256: @46 = (@5*@18) */
  w46  = (w5*w18);
  /* #257: @41 = (@41+@46) */
  w41 += w46;
  /* #258: @51 = (@7*@51) */
  w51  = (w7*w51);
  /* #259: @42 = (@6*@42) */
  w42  = (w6*w42);
  /* #260: @51 = (@51+@42) */
  w51 += w42;
  /* #261: @49 = (@5*@49) */
  w49  = (w5*w49);
  /* #262: @51 = (@51-@49) */
  w51 -= w49;
  /* #263: @18 = (@4*@18) */
  w18  = (w4*w18);
  /* #264: @51 = (@51+@18) */
  w51 += w18;
  /* #265: @61 = vertcat(@48, @40, @41, @51) */
  rr=w61;
  *rr++ = w48;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w51;
  /* #266: @62 = (@12*@61) */
  for (i=0, rr=w62, cs=w61; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #267: @48 = 1 */
  w48 = 1.;
  /* #268: @13 = (@13?@48:0) */
  w13  = (w13?w48:0);
  /* #269: @61 = (@13*@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #270: @62 = (@62-@61) */
  for (i=0, rr=w62, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #271: @1 = @62[1:4] */
  for (rr=w1, ss=w62+1; ss!=w62+4; ss+=1) *rr++ = *ss;
  /* #272: @48 = dot(@28, @1) */
  w48 = casadi_dot(3, w28, w1);
  /* #273: @48 = (@48/@14) */
  w48 /= w14;
  /* #274: @40 = (@48/@2) */
  w40  = (w48/w2);
  /* #275: @41 = (@3/@2) */
  w41  = (w3/w2);
  /* #276: @51 = (2.*@14) */
  w51 = (2.* w14 );
  /* #277: @18 = (@51*@48) */
  w18  = (w51*w48);
  /* #278: @49 = (2.*@15) */
  w49 = (2.* w15 );
  /* #279: @42 = @62[0] */
  for (rr=(&w42), ss=w62+0; ss!=w62+1; ss+=1) *rr++ = *ss;
  /* #280: @46 = (@49*@42) */
  w46  = (w49*w42);
  /* #281: @18 = (@18+@46) */
  w18 += w46;
  /* #282: @46 = (@41*@18) */
  w46  = (w41*w18);
  /* #283: @40 = (@40-@46) */
  w40 -= w46;
  /* #284: @40 = (@11*@40) */
  w40  = (w11*w40);
  /* #285: @37 = zeros(1x3) */
  casadi_clear(w37, 3);
  /* #286: @20 = (2.*@1) */
  for (i=0, rr=w20, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #287: @38 = (@9*@20) */
  for (i=0, rr=w38, cs=w20; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #288: @46 = sq(@14) */
  w46 = casadi_sq( w14 );
  /* #289: @45 = sq(@15) */
  w45 = casadi_sq( w15 );
  /* #290: @46 = (@46+@45) */
  w46 += w45;
  /* #291: @15 = (@15/@46) */
  w15 /= w46;
  /* #292: @45 = (@15*@48) */
  w45  = (w15*w48);
  /* #293: @46 = (@14/@46) */
  w46  = (w14/w46);
  /* #294: @44 = (@46*@42) */
  w44  = (w46*w42);
  /* #295: @45 = (@45-@44) */
  w45 -= w44;
  /* #296: @63 = (@29*@45) */
  for (i=0, rr=w63, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w45);
  /* #297: @38 = (@38+@63) */
  for (i=0, rr=w38, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #298: @38 = (@38/@14) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w14;
  /* #299: @30 = (@30/@14) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) /= w14;
  /* #300: @63 = (@30*@48) */
  for (i=0, rr=w63, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #301: @38 = (@38-@63) */
  for (i=0, rr=w38, cs=w63; i<3; ++i) (*rr++) -= (*cs++);
  /* #302: @63 = @38' */
  casadi_copy(w38, 3, w63);
  /* #303: @37 = mac(@63,@32,@37) */
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w63+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #304: @37 = @37' */
  /* #305: @63 = zeros(1x3) */
  casadi_clear(w63, 3);
  /* #306: @64 = @38' */
  casadi_copy(w38, 3, w64);
  /* #307: @63 = mac(@64,@35,@63) */
  for (i=0, rr=w63; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #308: @63 = @63' */
  /* #309: @37 = (@37+@63) */
  for (i=0, rr=w37, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #310: @63 = (@37/@14) */
  for (i=0, rr=w63, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #311: @64 = (@31/@14) */
  for (i=0, rr=w64, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #312: @65 = (@64*@48) */
  for (i=0, rr=w65, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #313: @63 = (@63-@65) */
  for (i=0, rr=w63, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #314: @44 = dot(@29, @63) */
  w44 = casadi_dot(3, w29, w63);
  /* #315: @66 = dot(@20, @31) */
  w66 = casadi_dot(3, w20, w31);
  /* #316: @44 = (@44+@66) */
  w44 += w66;
  /* #317: @66 = (@3*@44) */
  w66  = (w3*w44);
  /* #318: @40 = (@40+@66) */
  w40 += w66;
  /* #319: @40 = (-@40) */
  w40 = (- w40 );
  /* #320: (@55[0] += @40) */
  for (rr=w55+0, ss=(&w40); rr!=w55+1; rr+=1) *rr += *ss++;
  /* #321: @40 = dot(@36, @37) */
  w40 = casadi_dot(3, w36, w37);
  /* #322: @38 = (@38/@14) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w14;
  /* #323: @34 = (@34/@14) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) /= w14;
  /* #324: @37 = (@34*@48) */
  for (i=0, rr=w37, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #325: @38 = (@38-@37) */
  for (i=0, rr=w38, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #326: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #327: @66 = dot(@38, @22) */
  w66 = casadi_dot(3, w38, w22);
  /* #328: @40 = (@40+@66) */
  w40 += w66;
  /* #329: @42 = (@42/@2) */
  w42 /= w2;
  /* #330: @66 = (@16/@2) */
  w66  = (w16/w2);
  /* #331: @18 = (@66*@18) */
  w18  = (w66*w18);
  /* #332: @42 = (@42-@18) */
  w42 -= w18;
  /* #333: @42 = (@11*@42) */
  w42  = (w11*w42);
  /* #334: @44 = (@16*@44) */
  w44  = (w16*w44);
  /* #335: @42 = (@42+@44) */
  w42 += w44;
  /* #336: @40 = (@40+@42) */
  w40 += w42;
  /* #337: @40 = (@40/@14) */
  w40 /= w14;
  /* #338: @42 = (@10/@14) */
  w42  = (w10/w14);
  /* #339: @48 = (@42*@48) */
  w48  = (w42*w48);
  /* #340: @40 = (@40-@48) */
  w40 -= w48;
  /* #341: @38 = (@28*@40) */
  for (i=0, rr=w38, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w40);
  /* #342: @1 = (@10*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #343: @38 = (@38+@1) */
  for (i=0, rr=w38, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #344: @1 = (@31*@45) */
  for (i=0, rr=w1, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w45);
  /* #345: @63 = (@9*@63) */
  for (i=0, rr=w63, cs=w63; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #346: @1 = (@1+@63) */
  for (i=0, rr=w1, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #347: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #348: @38 = (@38+@1) */
  for (i=0, rr=w38, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #349: (@55[1:4] += @38) */
  for (rr=w55+1, ss=w38; rr!=w55+4; rr+=1) *rr += *ss++;
  /* #350: @62 = (@0*@55) */
  for (i=0, rr=w62, cs=w55; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #351: @55 = (@17*@55) */
  for (i=0, rr=w55, cs=w55; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #352: @62 = (@62-@55) */
  for (i=0, rr=w62, cs=w55; i<4; ++i) (*rr++) -= (*cs++);
  /* #353: {@45, @40, @48, @44} = vertsplit(@62) */
  w45 = w62[0];
  w40 = w62[1];
  w48 = w62[2];
  w44 = w62[3];
  /* #354: @18 = (@7*@44) */
  w18  = (w7*w44);
  /* #355: @67 = (@6*@48) */
  w67  = (w6*w48);
  /* #356: @18 = (@18+@67) */
  w18 += w67;
  /* #357: @67 = (@5*@40) */
  w67  = (w5*w40);
  /* #358: @18 = (@18+@67) */
  w18 += w67;
  /* #359: @67 = (@4*@45) */
  w67  = (w4*w45);
  /* #360: @18 = (@18+@67) */
  w18 += w67;
  /* #361: @67 = (@6*@44) */
  w67  = (w6*w44);
  /* #362: @68 = (@7*@48) */
  w68  = (w7*w48);
  /* #363: @67 = (@67-@68) */
  w67 -= w68;
  /* #364: @68 = (@4*@40) */
  w68  = (w4*w40);
  /* #365: @67 = (@67+@68) */
  w67 += w68;
  /* #366: @68 = (@5*@45) */
  w68  = (w5*w45);
  /* #367: @67 = (@67-@68) */
  w67 -= w68;
  /* #368: @68 = (@4*@48) */
  w68  = (w4*w48);
  /* #369: @69 = (@5*@44) */
  w69  = (w5*w44);
  /* #370: @68 = (@68-@69) */
  w68 -= w69;
  /* #371: @69 = (@7*@40) */
  w69  = (w7*w40);
  /* #372: @68 = (@68+@69) */
  w68 += w69;
  /* #373: @69 = (@6*@45) */
  w69  = (w6*w45);
  /* #374: @68 = (@68-@69) */
  w68 -= w69;
  /* #375: @44 = (@4*@44) */
  w44  = (w4*w44);
  /* #376: @48 = (@5*@48) */
  w48  = (w5*w48);
  /* #377: @44 = (@44+@48) */
  w44 += w48;
  /* #378: @40 = (@6*@40) */
  w40  = (w6*w40);
  /* #379: @44 = (@44-@40) */
  w44 -= w40;
  /* #380: @45 = (@7*@45) */
  w45  = (w7*w45);
  /* #381: @44 = (@44-@45) */
  w44 -= w45;
  /* #382: @62 = vertcat(@18, @67, @68, @44) */
  rr=w62;
  *rr++ = w18;
  *rr++ = w67;
  *rr++ = w68;
  *rr++ = w44;
  /* #383: @18 = dot(@26, @62) */
  w18 = casadi_dot(4, w26, w62);
  /* #384: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w8;
  /* #385: @27 = (@27/@8) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) /= w8;
  /* #386: @55 = (@27*@52) */
  for (i=0, rr=w55, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w52);
  /* #387: @60 = (@60-@55) */
  for (i=0, rr=w60, cs=w55; i<4; ++i) (*rr++) -= (*cs++);
  /* #388: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #389: @67 = dot(@60, @39) */
  w67 = casadi_dot(4, w60, w39);
  /* #390: @18 = (@18+@67) */
  w18 += w67;
  /* #391: @18 = (@18/@8) */
  w18 /= w8;
  /* #392: @67 = (@43/@8) */
  w67  = (w43/w8);
  /* #393: @68 = (@67*@52) */
  w68  = (w67*w52);
  /* #394: @18 = (@18-@68) */
  w18 -= w68;
  /* #395: @60 = (@25*@18) */
  for (i=0, rr=w60, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #396: @50 = (@43*@50) */
  w50  = (w43*w50);
  /* #397: @55 = dense(@50) */
  casadi_densify((&w50), casadi_s0, w55, 0);
  /* #398: @60 = (@60+@55) */
  for (i=0, rr=w60, cs=w55; i<4; ++i) (*rr++) += (*cs++);
  /* #399: (@21[6:10] += @60) */
  for (rr=w21+6, ss=w60; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #400: @38 = zeros(1x3) */
  casadi_clear(w38, 3);
  /* #401: @50 = @53[0] */
  for (rr=(&w50), ss=(&w53)+0; ss!=(&w53)+1; ss+=1) *rr++ = *ss;
  /* #402: @50 = (-@50) */
  w50 = (- w50 );
  /* #403: @53 = @50' */
  casadi_copy((&w50), 1, (&w53));
  /* #404: @38 = mac(@53,@23,@38) */
  casadi_mtimes((&w53), casadi_s3, w23, casadi_s2, w38, casadi_s1, w, 0);
  /* #405: @38 = @38' */
  /* #406: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #407: @50 = @50' */
  /* #408: @1 = mac(@50,@47,@1) */
  casadi_mtimes((&w50), casadi_s3, w47, casadi_s2, w1, casadi_s1, w, 0);
  /* #409: @1 = @1' */
  /* #410: @38 = (@38+@1) */
  for (i=0, rr=w38, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #411: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #412: (@21[:3] += @38) */
  for (rr=w21+0, ss=w38; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #413: {@50, @53, @18, @68, @44, @45, @40, @48, @69, @70, @71, @72, @73} = vertsplit(@21) */
  w50 = w21[0];
  w53 = w21[1];
  w18 = w21[2];
  w68 = w21[3];
  w44 = w21[4];
  w45 = w21[5];
  w40 = w21[6];
  w48 = w21[7];
  w69 = w21[8];
  w70 = w21[9];
  w71 = w21[10];
  w72 = w21[11];
  w73 = w21[12];
  /* #414: @62 = (@62/@8) */
  for (i=0, rr=w62; i<4; ++i) (*rr++) /= w8;
  /* #415: @33 = (@33/@8) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) /= w8;
  /* #416: @60 = (@33*@52) */
  for (i=0, rr=w60, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w52);
  /* #417: @62 = (@62-@60) */
  for (i=0, rr=w62, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #418: {@52, @74, @75, @76} = vertsplit(@62) */
  w52 = w62[0];
  w74 = w62[1];
  w75 = w62[2];
  w76 = w62[3];
  /* #419: @52 = (@52+@40) */
  w52 += w40;
  /* #420: @48 = (@48-@74) */
  w48 -= w74;
  /* #421: @69 = (@69-@75) */
  w69 -= w75;
  /* #422: @70 = (@70-@76) */
  w70 -= w76;
  /* #423: @21 = vertcat(@50, @53, @18, @68, @44, @45, @52, @48, @69, @70, @71, @72, @73) */
  rr=w21;
  *rr++ = w50;
  *rr++ = w53;
  *rr++ = w18;
  *rr++ = w68;
  *rr++ = w44;
  *rr++ = w45;
  *rr++ = w52;
  *rr++ = w48;
  *rr++ = w69;
  *rr++ = w70;
  *rr++ = w71;
  *rr++ = w72;
  *rr++ = w73;
  /* #424: @77 = @21[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w77, ss=w21; cii!=casadi_s4+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #425: (@54[0, 1, 2, 9, 10, 11, 12] = @77) */
  for (cii=casadi_s5, rr=w54, ss=w77; cii!=casadi_s5+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #426: @77 = @21[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w77, ss=w21; cii!=casadi_s4+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #427: (@54[0, 3, 6, 9, 13, 17, 21] = @77) */
  for (cii=casadi_s6, rr=w54, ss=w77; cii!=casadi_s6+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #428: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #429: @62 = zeros(4x1) */
  casadi_clear(w62, 4);
  /* #430: @57 = 00 */
  /* #431: @78 = ones(13x1,2nz) */
  casadi_fill(w78, 2, 1.);
  /* #432: {NULL, @50, NULL, NULL, NULL, NULL, NULL, @53, NULL, NULL, NULL, NULL, NULL} = vertsplit(@78) */
  w50 = w78[0];
  w53 = w78[1];
  /* #433: @18 = (-@53) */
  w18 = (- w53 );
  /* #434: @58 = 00 */
  /* #435: @59 = 00 */
  /* #436: @68 = vertcat(@57, @18, @58, @59) */
  rr=(&w68);
  *rr++ = w18;
  /* #437: @68 = (@68/@8) */
  w68 /= w8;
  /* #438: @60 = dense(@68) */
  casadi_densify((&w68), casadi_s7, w60, 0);
  /* #439: @68 = project(@25) */
  casadi_sparsify(w25, (&w68), casadi_s7, 0);
  /* #440: @18 = @53[0] */
  for (rr=(&w18), ss=(&w53)+0; ss!=(&w53)+1; ss+=1) *rr++ = *ss;
  /* #441: @53 = dot(@68, @18) */
  w53 = casadi_dot(1, (&w68), (&w18));
  /* #442: @53 = (@53/@8) */
  w53 /= w8;
  /* #443: @55 = (@24*@53) */
  for (i=0, rr=w55, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #444: @60 = (@60-@55) */
  for (i=0, rr=w60, cs=w55; i<4; ++i) (*rr++) -= (*cs++);
  /* #445: {@68, @44, @45, @52} = vertsplit(@60) */
  w68 = w60[0];
  w44 = w60[1];
  w45 = w60[2];
  w52 = w60[3];
  /* #446: @48 = (@4*@68) */
  w48  = (w4*w68);
  /* #447: @69 = (@5*@44) */
  w69  = (w5*w44);
  /* #448: @48 = (@48-@69) */
  w48 -= w69;
  /* #449: @69 = (@6*@45) */
  w69  = (w6*w45);
  /* #450: @48 = (@48-@69) */
  w48 -= w69;
  /* #451: @69 = (@7*@52) */
  w69  = (w7*w52);
  /* #452: @48 = (@48-@69) */
  w48 -= w69;
  /* #453: @69 = (@5*@68) */
  w69  = (w5*w68);
  /* #454: @70 = (@4*@44) */
  w70  = (w4*w44);
  /* #455: @69 = (@69+@70) */
  w69 += w70;
  /* #456: @70 = (@7*@45) */
  w70  = (w7*w45);
  /* #457: @69 = (@69+@70) */
  w69 += w70;
  /* #458: @70 = (@6*@52) */
  w70  = (w6*w52);
  /* #459: @69 = (@69-@70) */
  w69 -= w70;
  /* #460: @70 = (@6*@68) */
  w70  = (w6*w68);
  /* #461: @71 = (@7*@44) */
  w71  = (w7*w44);
  /* #462: @70 = (@70-@71) */
  w70 -= w71;
  /* #463: @71 = (@4*@45) */
  w71  = (w4*w45);
  /* #464: @70 = (@70+@71) */
  w70 += w71;
  /* #465: @71 = (@5*@52) */
  w71  = (w5*w52);
  /* #466: @70 = (@70+@71) */
  w70 += w71;
  /* #467: @68 = (@7*@68) */
  w68  = (w7*w68);
  /* #468: @44 = (@6*@44) */
  w44  = (w6*w44);
  /* #469: @68 = (@68+@44) */
  w68 += w44;
  /* #470: @45 = (@5*@45) */
  w45  = (w5*w45);
  /* #471: @68 = (@68-@45) */
  w68 -= w45;
  /* #472: @52 = (@4*@52) */
  w52  = (w4*w52);
  /* #473: @68 = (@68+@52) */
  w68 += w52;
  /* #474: @55 = vertcat(@48, @69, @70, @68) */
  rr=w55;
  *rr++ = w48;
  *rr++ = w69;
  *rr++ = w70;
  *rr++ = w68;
  /* #475: @61 = (@12*@55) */
  for (i=0, rr=w61, cs=w55; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #476: @55 = (@13*@55) */
  for (i=0, rr=w55, cs=w55; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #477: @61 = (@61-@55) */
  for (i=0, rr=w61, cs=w55; i<4; ++i) (*rr++) -= (*cs++);
  /* #478: @38 = @61[1:4] */
  for (rr=w38, ss=w61+1; ss!=w61+4; ss+=1) *rr++ = *ss;
  /* #479: @48 = dot(@28, @38) */
  w48 = casadi_dot(3, w28, w38);
  /* #480: @48 = (@48/@14) */
  w48 /= w14;
  /* #481: @69 = (@48/@2) */
  w69  = (w48/w2);
  /* #482: @70 = (@51*@48) */
  w70  = (w51*w48);
  /* #483: @68 = @61[0] */
  for (rr=(&w68), ss=w61+0; ss!=w61+1; ss+=1) *rr++ = *ss;
  /* #484: @52 = (@49*@68) */
  w52  = (w49*w68);
  /* #485: @70 = (@70+@52) */
  w70 += w52;
  /* #486: @52 = (@41*@70) */
  w52  = (w41*w70);
  /* #487: @69 = (@69-@52) */
  w69 -= w52;
  /* #488: @69 = (@11*@69) */
  w69  = (w11*w69);
  /* #489: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #490: @63 = (2.*@38) */
  for (i=0, rr=w63, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #491: @37 = (@9*@63) */
  for (i=0, rr=w37, cs=w63; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #492: @52 = (@15*@48) */
  w52  = (w15*w48);
  /* #493: @45 = (@46*@68) */
  w45  = (w46*w68);
  /* #494: @52 = (@52-@45) */
  w52 -= w45;
  /* #495: @20 = (@29*@52) */
  for (i=0, rr=w20, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #496: @37 = (@37+@20) */
  for (i=0, rr=w37, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #497: @37 = (@37/@14) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w14;
  /* #498: @20 = (@30*@48) */
  for (i=0, rr=w20, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #499: @37 = (@37-@20) */
  for (i=0, rr=w37, cs=w20; i<3; ++i) (*rr++) -= (*cs++);
  /* #500: @20 = @37' */
  casadi_copy(w37, 3, w20);
  /* #501: @1 = mac(@20,@32,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #502: @1 = @1' */
  /* #503: @20 = zeros(1x3) */
  casadi_clear(w20, 3);
  /* #504: @65 = @37' */
  casadi_copy(w37, 3, w65);
  /* #505: @20 = mac(@65,@35,@20) */
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w65+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #506: @20 = @20' */
  /* #507: @1 = (@1+@20) */
  for (i=0, rr=w1, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #508: @20 = (@1/@14) */
  for (i=0, rr=w20, cr=w1; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #509: @65 = (@64*@48) */
  for (i=0, rr=w65, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #510: @20 = (@20-@65) */
  for (i=0, rr=w20, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #511: @45 = dot(@29, @20) */
  w45 = casadi_dot(3, w29, w20);
  /* #512: @44 = dot(@63, @31) */
  w44 = casadi_dot(3, w63, w31);
  /* #513: @45 = (@45+@44) */
  w45 += w44;
  /* #514: @44 = (@3*@45) */
  w44  = (w3*w45);
  /* #515: @69 = (@69+@44) */
  w69 += w44;
  /* #516: @69 = (-@69) */
  w69 = (- w69 );
  /* #517: (@62[0] += @69) */
  for (rr=w62+0, ss=(&w69); rr!=w62+1; rr+=1) *rr += *ss++;
  /* #518: @69 = dot(@36, @1) */
  w69 = casadi_dot(3, w36, w1);
  /* #519: @37 = (@37/@14) */
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w14;
  /* #520: @1 = (@34*@48) */
  for (i=0, rr=w1, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #521: @37 = (@37-@1) */
  for (i=0, rr=w37, cs=w1; i<3; ++i) (*rr++) -= (*cs++);
  /* #522: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (- *cs++ );
  /* #523: @44 = dot(@37, @22) */
  w44 = casadi_dot(3, w37, w22);
  /* #524: @69 = (@69+@44) */
  w69 += w44;
  /* #525: @68 = (@68/@2) */
  w68 /= w2;
  /* #526: @70 = (@66*@70) */
  w70  = (w66*w70);
  /* #527: @68 = (@68-@70) */
  w68 -= w70;
  /* #528: @68 = (@11*@68) */
  w68  = (w11*w68);
  /* #529: @45 = (@16*@45) */
  w45  = (w16*w45);
  /* #530: @68 = (@68+@45) */
  w68 += w45;
  /* #531: @69 = (@69+@68) */
  w69 += w68;
  /* #532: @69 = (@69/@14) */
  w69 /= w14;
  /* #533: @48 = (@42*@48) */
  w48  = (w42*w48);
  /* #534: @69 = (@69-@48) */
  w69 -= w48;
  /* #535: @37 = (@28*@69) */
  for (i=0, rr=w37, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #536: @38 = (@10*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #537: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #538: @38 = (@31*@52) */
  for (i=0, rr=w38, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w52);
  /* #539: @20 = (@9*@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #540: @38 = (@38+@20) */
  for (i=0, rr=w38, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #541: @38 = (2.*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #542: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #543: (@62[1:4] += @37) */
  for (rr=w62+1, ss=w37; rr!=w62+4; rr+=1) *rr += *ss++;
  /* #544: @61 = (@0*@62) */
  for (i=0, rr=w61, cs=w62; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #545: @62 = (@17*@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #546: @61 = (@61-@62) */
  for (i=0, rr=w61, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #547: {@52, @69, @48, @68} = vertsplit(@61) */
  w52 = w61[0];
  w69 = w61[1];
  w48 = w61[2];
  w68 = w61[3];
  /* #548: @45 = (@7*@68) */
  w45  = (w7*w68);
  /* #549: @70 = (@6*@48) */
  w70  = (w6*w48);
  /* #550: @45 = (@45+@70) */
  w45 += w70;
  /* #551: @70 = (@5*@69) */
  w70  = (w5*w69);
  /* #552: @45 = (@45+@70) */
  w45 += w70;
  /* #553: @70 = (@4*@52) */
  w70  = (w4*w52);
  /* #554: @45 = (@45+@70) */
  w45 += w70;
  /* #555: @70 = (@6*@68) */
  w70  = (w6*w68);
  /* #556: @44 = (@7*@48) */
  w44  = (w7*w48);
  /* #557: @70 = (@70-@44) */
  w70 -= w44;
  /* #558: @44 = (@4*@69) */
  w44  = (w4*w69);
  /* #559: @70 = (@70+@44) */
  w70 += w44;
  /* #560: @44 = (@5*@52) */
  w44  = (w5*w52);
  /* #561: @70 = (@70-@44) */
  w70 -= w44;
  /* #562: @44 = (@4*@48) */
  w44  = (w4*w48);
  /* #563: @71 = (@5*@68) */
  w71  = (w5*w68);
  /* #564: @44 = (@44-@71) */
  w44 -= w71;
  /* #565: @71 = (@7*@69) */
  w71  = (w7*w69);
  /* #566: @44 = (@44+@71) */
  w44 += w71;
  /* #567: @71 = (@6*@52) */
  w71  = (w6*w52);
  /* #568: @44 = (@44-@71) */
  w44 -= w71;
  /* #569: @68 = (@4*@68) */
  w68  = (w4*w68);
  /* #570: @48 = (@5*@48) */
  w48  = (w5*w48);
  /* #571: @68 = (@68+@48) */
  w68 += w48;
  /* #572: @69 = (@6*@69) */
  w69  = (w6*w69);
  /* #573: @68 = (@68-@69) */
  w68 -= w69;
  /* #574: @52 = (@7*@52) */
  w52  = (w7*w52);
  /* #575: @68 = (@68-@52) */
  w68 -= w52;
  /* #576: @61 = vertcat(@45, @70, @44, @68) */
  rr=w61;
  *rr++ = w45;
  *rr++ = w70;
  *rr++ = w44;
  *rr++ = w68;
  /* #577: @45 = dot(@26, @61) */
  w45 = casadi_dot(4, w26, w61);
  /* #578: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w8;
  /* #579: @62 = (@27*@53) */
  for (i=0, rr=w62, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #580: @60 = (@60-@62) */
  for (i=0, rr=w60, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #581: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #582: @70 = dot(@60, @39) */
  w70 = casadi_dot(4, w60, w39);
  /* #583: @45 = (@45+@70) */
  w45 += w70;
  /* #584: @45 = (@45/@8) */
  w45 /= w8;
  /* #585: @70 = (@67*@53) */
  w70  = (w67*w53);
  /* #586: @45 = (@45-@70) */
  w45 -= w70;
  /* #587: @60 = (@25*@45) */
  for (i=0, rr=w60, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w45);
  /* #588: @18 = (@43*@18) */
  w18  = (w43*w18);
  /* #589: @62 = dense(@18) */
  casadi_densify((&w18), casadi_s7, w62, 0);
  /* #590: @60 = (@60+@62) */
  for (i=0, rr=w60, cs=w62; i<4; ++i) (*rr++) += (*cs++);
  /* #591: (@21[6:10] += @60) */
  for (rr=w21+6, ss=w60; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #592: @37 = zeros(1x3) */
  casadi_clear(w37, 3);
  /* #593: @18 = @50[0] */
  for (rr=(&w18), ss=(&w50)+0; ss!=(&w50)+1; ss+=1) *rr++ = *ss;
  /* #594: @18 = (-@18) */
  w18 = (- w18 );
  /* #595: @50 = @18' */
  casadi_copy((&w18), 1, (&w50));
  /* #596: @37 = mac(@50,@23,@37) */
  casadi_mtimes((&w50), casadi_s8, w23, casadi_s2, w37, casadi_s1, w, 0);
  /* #597: @37 = @37' */
  /* #598: @38 = zeros(1x3) */
  casadi_clear(w38, 3);
  /* #599: @18 = @18' */
  /* #600: @38 = mac(@18,@47,@38) */
  casadi_mtimes((&w18), casadi_s8, w47, casadi_s2, w38, casadi_s1, w, 0);
  /* #601: @38 = @38' */
  /* #602: @37 = (@37+@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) += (*cs++);
  /* #603: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (- *cs++ );
  /* #604: (@21[:3] += @37) */
  for (rr=w21+0, ss=w37; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #605: {@18, @50, @45, @70, @44, @68, @52, @69, @48, @71, @72, @73, @76} = vertsplit(@21) */
  w18 = w21[0];
  w50 = w21[1];
  w45 = w21[2];
  w70 = w21[3];
  w44 = w21[4];
  w68 = w21[5];
  w52 = w21[6];
  w69 = w21[7];
  w48 = w21[8];
  w71 = w21[9];
  w72 = w21[10];
  w73 = w21[11];
  w76 = w21[12];
  /* #606: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w8;
  /* #607: @60 = (@33*@53) */
  for (i=0, rr=w60, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w53);
  /* #608: @61 = (@61-@60) */
  for (i=0, rr=w61, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #609: {@53, @75, @74, @40} = vertsplit(@61) */
  w53 = w61[0];
  w75 = w61[1];
  w74 = w61[2];
  w40 = w61[3];
  /* #610: @53 = (@53+@52) */
  w53 += w52;
  /* #611: @69 = (@69-@75) */
  w69 -= w75;
  /* #612: @48 = (@48-@74) */
  w48 -= w74;
  /* #613: @71 = (@71-@40) */
  w71 -= w40;
  /* #614: @21 = vertcat(@18, @50, @45, @70, @44, @68, @53, @69, @48, @71, @72, @73, @76) */
  rr=w21;
  *rr++ = w18;
  *rr++ = w50;
  *rr++ = w45;
  *rr++ = w70;
  *rr++ = w44;
  *rr++ = w68;
  *rr++ = w53;
  *rr++ = w69;
  *rr++ = w48;
  *rr++ = w71;
  *rr++ = w72;
  *rr++ = w73;
  *rr++ = w76;
  /* #615: @77 = @21[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w77, ss=w21; cii!=casadi_s4+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #616: (@54[3, 4, 5, 13, 14, 15, 16] = @77) */
  for (cii=casadi_s9, rr=w54, ss=w77; cii!=casadi_s9+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #617: @77 = @21[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w77, ss=w21; cii!=casadi_s4+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #618: (@54[1, 4, 7, 10, 14, 18, 22] = @77) */
  for (cii=casadi_s10, rr=w54, ss=w77; cii!=casadi_s10+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #619: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #620: @61 = zeros(4x1) */
  casadi_clear(w61, 4);
  /* #621: @57 = 00 */
  /* #622: @58 = 00 */
  /* #623: @78 = ones(13x1,2nz) */
  casadi_fill(w78, 2, 1.);
  /* #624: {NULL, NULL, @18, NULL, NULL, NULL, NULL, NULL, @50, NULL, NULL, NULL, NULL} = vertsplit(@78) */
  w18 = w78[0];
  w50 = w78[1];
  /* #625: @45 = (-@50) */
  w45 = (- w50 );
  /* #626: @59 = 00 */
  /* #627: @70 = vertcat(@57, @58, @45, @59) */
  rr=(&w70);
  *rr++ = w45;
  /* #628: @70 = (@70/@8) */
  w70 /= w8;
  /* #629: @60 = dense(@70) */
  casadi_densify((&w70), casadi_s11, w60, 0);
  /* #630: @70 = project(@25) */
  casadi_sparsify(w25, (&w70), casadi_s11, 0);
  /* #631: @45 = @50[0] */
  for (rr=(&w45), ss=(&w50)+0; ss!=(&w50)+1; ss+=1) *rr++ = *ss;
  /* #632: @50 = dot(@70, @45) */
  w50 = casadi_dot(1, (&w70), (&w45));
  /* #633: @50 = (@50/@8) */
  w50 /= w8;
  /* #634: @62 = (@24*@50) */
  for (i=0, rr=w62, cr=w24; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #635: @60 = (@60-@62) */
  for (i=0, rr=w60, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #636: {@70, @44, @68, @53} = vertsplit(@60) */
  w70 = w60[0];
  w44 = w60[1];
  w68 = w60[2];
  w53 = w60[3];
  /* #637: @69 = (@4*@70) */
  w69  = (w4*w70);
  /* #638: @48 = (@5*@44) */
  w48  = (w5*w44);
  /* #639: @69 = (@69-@48) */
  w69 -= w48;
  /* #640: @48 = (@6*@68) */
  w48  = (w6*w68);
  /* #641: @69 = (@69-@48) */
  w69 -= w48;
  /* #642: @48 = (@7*@53) */
  w48  = (w7*w53);
  /* #643: @69 = (@69-@48) */
  w69 -= w48;
  /* #644: @48 = (@5*@70) */
  w48  = (w5*w70);
  /* #645: @71 = (@4*@44) */
  w71  = (w4*w44);
  /* #646: @48 = (@48+@71) */
  w48 += w71;
  /* #647: @71 = (@7*@68) */
  w71  = (w7*w68);
  /* #648: @48 = (@48+@71) */
  w48 += w71;
  /* #649: @71 = (@6*@53) */
  w71  = (w6*w53);
  /* #650: @48 = (@48-@71) */
  w48 -= w71;
  /* #651: @71 = (@6*@70) */
  w71  = (w6*w70);
  /* #652: @72 = (@7*@44) */
  w72  = (w7*w44);
  /* #653: @71 = (@71-@72) */
  w71 -= w72;
  /* #654: @72 = (@4*@68) */
  w72  = (w4*w68);
  /* #655: @71 = (@71+@72) */
  w71 += w72;
  /* #656: @72 = (@5*@53) */
  w72  = (w5*w53);
  /* #657: @71 = (@71+@72) */
  w71 += w72;
  /* #658: @70 = (@7*@70) */
  w70  = (w7*w70);
  /* #659: @44 = (@6*@44) */
  w44  = (w6*w44);
  /* #660: @70 = (@70+@44) */
  w70 += w44;
  /* #661: @68 = (@5*@68) */
  w68  = (w5*w68);
  /* #662: @70 = (@70-@68) */
  w70 -= w68;
  /* #663: @53 = (@4*@53) */
  w53  = (w4*w53);
  /* #664: @70 = (@70+@53) */
  w70 += w53;
  /* #665: @62 = vertcat(@69, @48, @71, @70) */
  rr=w62;
  *rr++ = w69;
  *rr++ = w48;
  *rr++ = w71;
  *rr++ = w70;
  /* #666: @55 = (@12*@62) */
  for (i=0, rr=w55, cs=w62; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #667: @62 = (@13*@62) */
  for (i=0, rr=w62, cs=w62; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #668: @55 = (@55-@62) */
  for (i=0, rr=w55, cs=w62; i<4; ++i) (*rr++) -= (*cs++);
  /* #669: @37 = @55[1:4] */
  for (rr=w37, ss=w55+1; ss!=w55+4; ss+=1) *rr++ = *ss;
  /* #670: @69 = dot(@28, @37) */
  w69 = casadi_dot(3, w28, w37);
  /* #671: @69 = (@69/@14) */
  w69 /= w14;
  /* #672: @48 = (@69/@2) */
  w48  = (w69/w2);
  /* #673: @71 = (@51*@69) */
  w71  = (w51*w69);
  /* #674: @70 = @55[0] */
  for (rr=(&w70), ss=w55+0; ss!=w55+1; ss+=1) *rr++ = *ss;
  /* #675: @53 = (@49*@70) */
  w53  = (w49*w70);
  /* #676: @71 = (@71+@53) */
  w71 += w53;
  /* #677: @53 = (@41*@71) */
  w53  = (w41*w71);
  /* #678: @48 = (@48-@53) */
  w48 -= w53;
  /* #679: @48 = (@11*@48) */
  w48  = (w11*w48);
  /* #680: @38 = zeros(1x3) */
  casadi_clear(w38, 3);
  /* #681: @20 = (2.*@37) */
  for (i=0, rr=w20, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #682: @1 = (@9*@20) */
  for (i=0, rr=w1, cs=w20; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #683: @53 = (@15*@69) */
  w53  = (w15*w69);
  /* #684: @68 = (@46*@70) */
  w68  = (w46*w70);
  /* #685: @53 = (@53-@68) */
  w53 -= w68;
  /* #686: @63 = (@29*@53) */
  for (i=0, rr=w63, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #687: @1 = (@1+@63) */
  for (i=0, rr=w1, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #688: @1 = (@1/@14) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w14;
  /* #689: @63 = (@30*@69) */
  for (i=0, rr=w63, cr=w30; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #690: @1 = (@1-@63) */
  for (i=0, rr=w1, cs=w63; i<3; ++i) (*rr++) -= (*cs++);
  /* #691: @63 = @1' */
  casadi_copy(w1, 3, w63);
  /* #692: @38 = mac(@63,@32,@38) */
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w63+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #693: @38 = @38' */
  /* #694: @63 = zeros(1x3) */
  casadi_clear(w63, 3);
  /* #695: @65 = @1' */
  casadi_copy(w1, 3, w65);
  /* #696: @63 = mac(@65,@35,@63) */
  for (i=0, rr=w63; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w65+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #697: @63 = @63' */
  /* #698: @38 = (@38+@63) */
  for (i=0, rr=w38, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #699: @63 = (@38/@14) */
  for (i=0, rr=w63, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #700: @65 = (@64*@69) */
  for (i=0, rr=w65, cr=w64; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #701: @63 = (@63-@65) */
  for (i=0, rr=w63, cs=w65; i<3; ++i) (*rr++) -= (*cs++);
  /* #702: @68 = dot(@29, @63) */
  w68 = casadi_dot(3, w29, w63);
  /* #703: @44 = dot(@20, @31) */
  w44 = casadi_dot(3, w20, w31);
  /* #704: @68 = (@68+@44) */
  w68 += w44;
  /* #705: @44 = (@3*@68) */
  w44  = (w3*w68);
  /* #706: @48 = (@48+@44) */
  w48 += w44;
  /* #707: @48 = (-@48) */
  w48 = (- w48 );
  /* #708: (@61[0] += @48) */
  for (rr=w61+0, ss=(&w48); rr!=w61+1; rr+=1) *rr += *ss++;
  /* #709: @48 = dot(@36, @38) */
  w48 = casadi_dot(3, w36, w38);
  /* #710: @1 = (@1/@14) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w14;
  /* #711: @38 = (@34*@69) */
  for (i=0, rr=w38, cr=w34; i<3; ++i) (*rr++)  = ((*cr++)*w69);
  /* #712: @1 = (@1-@38) */
  for (i=0, rr=w1, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #713: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #714: @44 = dot(@1, @22) */
  w44 = casadi_dot(3, w1, w22);
  /* #715: @48 = (@48+@44) */
  w48 += w44;
  /* #716: @70 = (@70/@2) */
  w70 /= w2;
  /* #717: @71 = (@66*@71) */
  w71  = (w66*w71);
  /* #718: @70 = (@70-@71) */
  w70 -= w71;
  /* #719: @70 = (@11*@70) */
  w70  = (w11*w70);
  /* #720: @68 = (@16*@68) */
  w68  = (w16*w68);
  /* #721: @70 = (@70+@68) */
  w70 += w68;
  /* #722: @48 = (@48+@70) */
  w48 += w70;
  /* #723: @48 = (@48/@14) */
  w48 /= w14;
  /* #724: @69 = (@42*@69) */
  w69  = (w42*w69);
  /* #725: @48 = (@48-@69) */
  w48 -= w69;
  /* #726: @1 = (@28*@48) */
  for (i=0, rr=w1, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w48);
  /* #727: @37 = (@10*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #728: @1 = (@1+@37) */
  for (i=0, rr=w1, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #729: @37 = (@31*@53) */
  for (i=0, rr=w37, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w53);
  /* #730: @63 = (@9*@63) */
  for (i=0, rr=w63, cs=w63; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #731: @37 = (@37+@63) */
  for (i=0, rr=w37, cs=w63; i<3; ++i) (*rr++) += (*cs++);
  /* #732: @37 = (2.*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #733: @1 = (@1+@37) */
  for (i=0, rr=w1, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #734: (@61[1:4] += @1) */
  for (rr=w61+1, ss=w1; rr!=w61+4; rr+=1) *rr += *ss++;
  /* #735: @55 = (@0*@61) */
  for (i=0, rr=w55, cs=w61; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #736: @61 = (@17*@61) */
  for (i=0, rr=w61, cs=w61; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #737: @55 = (@55-@61) */
  for (i=0, rr=w55, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #738: {@53, @48, @69, @70} = vertsplit(@55) */
  w53 = w55[0];
  w48 = w55[1];
  w69 = w55[2];
  w70 = w55[3];
  /* #739: @68 = (@7*@70) */
  w68  = (w7*w70);
  /* #740: @71 = (@6*@69) */
  w71  = (w6*w69);
  /* #741: @68 = (@68+@71) */
  w68 += w71;
  /* #742: @71 = (@5*@48) */
  w71  = (w5*w48);
  /* #743: @68 = (@68+@71) */
  w68 += w71;
  /* #744: @71 = (@4*@53) */
  w71  = (w4*w53);
  /* #745: @68 = (@68+@71) */
  w68 += w71;
  /* #746: @71 = (@6*@70) */
  w71  = (w6*w70);
  /* #747: @44 = (@7*@69) */
  w44  = (w7*w69);
  /* #748: @71 = (@71-@44) */
  w71 -= w44;
  /* #749: @44 = (@4*@48) */
  w44  = (w4*w48);
  /* #750: @71 = (@71+@44) */
  w71 += w44;
  /* #751: @44 = (@5*@53) */
  w44  = (w5*w53);
  /* #752: @71 = (@71-@44) */
  w71 -= w44;
  /* #753: @44 = (@4*@69) */
  w44  = (w4*w69);
  /* #754: @72 = (@5*@70) */
  w72  = (w5*w70);
  /* #755: @44 = (@44-@72) */
  w44 -= w72;
  /* #756: @72 = (@7*@48) */
  w72  = (w7*w48);
  /* #757: @44 = (@44+@72) */
  w44 += w72;
  /* #758: @72 = (@6*@53) */
  w72  = (w6*w53);
  /* #759: @44 = (@44-@72) */
  w44 -= w72;
  /* #760: @70 = (@4*@70) */
  w70  = (w4*w70);
  /* #761: @69 = (@5*@69) */
  w69  = (w5*w69);
  /* #762: @70 = (@70+@69) */
  w70 += w69;
  /* #763: @48 = (@6*@48) */
  w48  = (w6*w48);
  /* #764: @70 = (@70-@48) */
  w70 -= w48;
  /* #765: @53 = (@7*@53) */
  w53  = (w7*w53);
  /* #766: @70 = (@70-@53) */
  w70 -= w53;
  /* #767: @55 = vertcat(@68, @71, @44, @70) */
  rr=w55;
  *rr++ = w68;
  *rr++ = w71;
  *rr++ = w44;
  *rr++ = w70;
  /* #768: @68 = dot(@26, @55) */
  w68 = casadi_dot(4, w26, w55);
  /* #769: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w8;
  /* #770: @61 = (@27*@50) */
  for (i=0, rr=w61, cr=w27; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #771: @60 = (@60-@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) -= (*cs++);
  /* #772: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #773: @71 = dot(@60, @39) */
  w71 = casadi_dot(4, w60, w39);
  /* #774: @68 = (@68+@71) */
  w68 += w71;
  /* #775: @68 = (@68/@8) */
  w68 /= w8;
  /* #776: @71 = (@67*@50) */
  w71  = (w67*w50);
  /* #777: @68 = (@68-@71) */
  w68 -= w71;
  /* #778: @60 = (@25*@68) */
  for (i=0, rr=w60, cr=w25; i<4; ++i) (*rr++)  = ((*cr++)*w68);
  /* #779: @45 = (@43*@45) */
  w45  = (w43*w45);
  /* #780: @61 = dense(@45) */
  casadi_densify((&w45), casadi_s11, w61, 0);
  /* #781: @60 = (@60+@61) */
  for (i=0, rr=w60, cs=w61; i<4; ++i) (*rr++) += (*cs++);
  /* #782: (@21[6:10] += @60) */
  for (rr=w21+6, ss=w60; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #783: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #784: @45 = @18[0] */
  for (rr=(&w45), ss=(&w18)+0; ss!=(&w18)+1; ss+=1) *rr++ = *ss;
  /* #785: @45 = (-@45) */
  w45 = (- w45 );
  /* #786: @18 = @45' */
  casadi_copy((&w45), 1, (&w18));
  /* #787: @1 = mac(@18,@23,@1) */
  casadi_mtimes((&w18), casadi_s12, w23, casadi_s2, w1, casadi_s1, w, 0);
  /* #788: @1 = @1' */
  /* #789: @37 = zeros(1x3) */
  casadi_clear(w37, 3);
  /* #790: @45 = @45' */
  /* #791: @37 = mac(@45,@47,@37) */
  casadi_mtimes((&w45), casadi_s12, w47, casadi_s2, w37, casadi_s1, w, 0);
  /* #792: @37 = @37' */
  /* #793: @1 = (@1+@37) */
  for (i=0, rr=w1, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #794: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #795: (@21[:3] += @1) */
  for (rr=w21+0, ss=w1; rr!=w21+3; rr+=1) *rr += *ss++;
  /* #796: {@45, @18, @68, @71, @44, @70, @53, @48, @69, @72, @73, @76, @40} = vertsplit(@21) */
  w45 = w21[0];
  w18 = w21[1];
  w68 = w21[2];
  w71 = w21[3];
  w44 = w21[4];
  w70 = w21[5];
  w53 = w21[6];
  w48 = w21[7];
  w69 = w21[8];
  w72 = w21[9];
  w73 = w21[10];
  w76 = w21[11];
  w40 = w21[12];
  /* #797: @55 = (@55/@8) */
  for (i=0, rr=w55; i<4; ++i) (*rr++) /= w8;
  /* #798: @60 = (@33*@50) */
  for (i=0, rr=w60, cr=w33; i<4; ++i) (*rr++)  = ((*cr++)*w50);
  /* #799: @55 = (@55-@60) */
  for (i=0, rr=w55, cs=w60; i<4; ++i) (*rr++) -= (*cs++);
  /* #800: {@50, @74, @75, @52} = vertsplit(@55) */
  w50 = w55[0];
  w74 = w55[1];
  w75 = w55[2];
  w52 = w55[3];
  /* #801: @50 = (@50+@53) */
  w50 += w53;
  /* #802: @48 = (@48-@74) */
  w48 -= w74;
  /* #803: @69 = (@69-@75) */
  w69 -= w75;
  /* #804: @72 = (@72-@52) */
  w72 -= w52;
  /* #805: @21 = vertcat(@45, @18, @68, @71, @44, @70, @50, @48, @69, @72, @73, @76, @40) */
  rr=w21;
  *rr++ = w45;
  *rr++ = w18;
  *rr++ = w68;
  *rr++ = w71;
  *rr++ = w44;
  *rr++ = w70;
  *rr++ = w50;
  *rr++ = w48;
  *rr++ = w69;
  *rr++ = w72;
  *rr++ = w73;
  *rr++ = w76;
  *rr++ = w40;
  /* #806: @77 = @21[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w77, ss=w21; cii!=casadi_s4+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #807: (@54[6, 7, 8, 17, 18, 19, 20] = @77) */
  for (cii=casadi_s13, rr=w54, ss=w77; cii!=casadi_s13+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #808: @77 = @21[0, 1, 2, 6, 7, 8, 9] */
  for (cii=casadi_s4, rr=w77, ss=w21; cii!=casadi_s4+7; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #809: (@54[2, 5, 8, 11, 15, 19, 23] = @77) */
  for (cii=casadi_s14, rr=w54, ss=w77; cii!=casadi_s14+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #810: @21 = zeros(13x1) */
  casadi_clear(w21, 13);
  /* #811: @55 = zeros(4x1) */
  casadi_clear(w55, 4);
  /* #812: @57 = 00 */
  /* #813: @58 = 00 */
  /* #814: @59 = 00 */
  /* #815: @45 = ones(13x1,1nz) */
  w45 = 1.;
  /* #816: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @18, NULL, NULL, NULL} = vertsplit(@45) */
  w18 = w45;
  /* #817: @45 = (-@18) */
  w45 = (- w18 );
  /* #818: @68 = vertcat(@57, @58, @59, @45) */
  rr=(&w68);
  *rr++ = w45;
  /* #819: @68 = (@68/@8) */
  w68 /= w8;
  /* #820: @60 = dense(@68) */
  casadi_densify((&w68), casadi_s15, w60, 0);
  /* #821: @68 = project(@25) */
  casadi_sparsify(w25, (&w68), casadi_s15, 0);
  /* #822: @45 = @18[0] */
  for (rr=(&w45), ss=(&w18)+0; ss!=(&w18)+1; ss+=1) *rr++ = *ss;
  /* #823: @18 = dot(@68, @45) */
  w18 = casadi_dot(1, (&w68), (&w45));
  /* #824: @18 = (@18/@8) */
  w18 /= w8;
  /* #825: @24 = (@24*@18) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) *= w18;
  /* #826: @60 = (@60-@24) */
  for (i=0, rr=w60, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #827: {@68, @71, @44, @70} = vertsplit(@60) */
  w68 = w60[0];
  w71 = w60[1];
  w44 = w60[2];
  w70 = w60[3];
  /* #828: @50 = (@4*@68) */
  w50  = (w4*w68);
  /* #829: @48 = (@5*@71) */
  w48  = (w5*w71);
  /* #830: @50 = (@50-@48) */
  w50 -= w48;
  /* #831: @48 = (@6*@44) */
  w48  = (w6*w44);
  /* #832: @50 = (@50-@48) */
  w50 -= w48;
  /* #833: @48 = (@7*@70) */
  w48  = (w7*w70);
  /* #834: @50 = (@50-@48) */
  w50 -= w48;
  /* #835: @48 = (@5*@68) */
  w48  = (w5*w68);
  /* #836: @69 = (@4*@71) */
  w69  = (w4*w71);
  /* #837: @48 = (@48+@69) */
  w48 += w69;
  /* #838: @69 = (@7*@44) */
  w69  = (w7*w44);
  /* #839: @48 = (@48+@69) */
  w48 += w69;
  /* #840: @69 = (@6*@70) */
  w69  = (w6*w70);
  /* #841: @48 = (@48-@69) */
  w48 -= w69;
  /* #842: @69 = (@6*@68) */
  w69  = (w6*w68);
  /* #843: @72 = (@7*@71) */
  w72  = (w7*w71);
  /* #844: @69 = (@69-@72) */
  w69 -= w72;
  /* #845: @72 = (@4*@44) */
  w72  = (w4*w44);
  /* #846: @69 = (@69+@72) */
  w69 += w72;
  /* #847: @72 = (@5*@70) */
  w72  = (w5*w70);
  /* #848: @69 = (@69+@72) */
  w69 += w72;
  /* #849: @68 = (@7*@68) */
  w68  = (w7*w68);
  /* #850: @71 = (@6*@71) */
  w71  = (w6*w71);
  /* #851: @68 = (@68+@71) */
  w68 += w71;
  /* #852: @44 = (@5*@44) */
  w44  = (w5*w44);
  /* #853: @68 = (@68-@44) */
  w68 -= w44;
  /* #854: @70 = (@4*@70) */
  w70  = (w4*w70);
  /* #855: @68 = (@68+@70) */
  w68 += w70;
  /* #856: @24 = vertcat(@50, @48, @69, @68) */
  rr=w24;
  *rr++ = w50;
  *rr++ = w48;
  *rr++ = w69;
  *rr++ = w68;
  /* #857: @61 = (@12*@24) */
  for (i=0, rr=w61, cs=w24; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #858: @24 = (@13*@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #859: @61 = (@61-@24) */
  for (i=0, rr=w61, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #860: @1 = @61[1:4] */
  for (rr=w1, ss=w61+1; ss!=w61+4; ss+=1) *rr++ = *ss;
  /* #861: @13 = dot(@28, @1) */
  w13 = casadi_dot(3, w28, w1);
  /* #862: @13 = (@13/@14) */
  w13 /= w14;
  /* #863: @12 = (@13/@2) */
  w12  = (w13/w2);
  /* #864: @51 = (@51*@13) */
  w51 *= w13;
  /* #865: @50 = @61[0] */
  for (rr=(&w50), ss=w61+0; ss!=w61+1; ss+=1) *rr++ = *ss;
  /* #866: @49 = (@49*@50) */
  w49 *= w50;
  /* #867: @51 = (@51+@49) */
  w51 += w49;
  /* #868: @41 = (@41*@51) */
  w41 *= w51;
  /* #869: @12 = (@12-@41) */
  w12 -= w41;
  /* #870: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #871: @37 = zeros(1x3) */
  casadi_clear(w37, 3);
  /* #872: @63 = (2.*@1) */
  for (i=0, rr=w63, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #873: @38 = (@9*@63) */
  for (i=0, rr=w38, cs=w63; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #874: @15 = (@15*@13) */
  w15 *= w13;
  /* #875: @46 = (@46*@50) */
  w46 *= w50;
  /* #876: @15 = (@15-@46) */
  w15 -= w46;
  /* #877: @20 = (@29*@15) */
  for (i=0, rr=w20, cr=w29; i<3; ++i) (*rr++)  = ((*cr++)*w15);
  /* #878: @38 = (@38+@20) */
  for (i=0, rr=w38, cs=w20; i<3; ++i) (*rr++) += (*cs++);
  /* #879: @38 = (@38/@14) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w14;
  /* #880: @30 = (@30*@13) */
  for (i=0, rr=w30; i<3; ++i) (*rr++) *= w13;
  /* #881: @38 = (@38-@30) */
  for (i=0, rr=w38, cs=w30; i<3; ++i) (*rr++) -= (*cs++);
  /* #882: @30 = @38' */
  casadi_copy(w38, 3, w30);
  /* #883: @37 = mac(@30,@32,@37) */
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w32+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #884: @37 = @37' */
  /* #885: @30 = zeros(1x3) */
  casadi_clear(w30, 3);
  /* #886: @20 = @38' */
  casadi_copy(w38, 3, w20);
  /* #887: @30 = mac(@20,@35,@30) */
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w20+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #888: @30 = @30' */
  /* #889: @37 = (@37+@30) */
  for (i=0, rr=w37, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #890: @30 = (@37/@14) */
  for (i=0, rr=w30, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #891: @64 = (@64*@13) */
  for (i=0, rr=w64; i<3; ++i) (*rr++) *= w13;
  /* #892: @30 = (@30-@64) */
  for (i=0, rr=w30, cs=w64; i<3; ++i) (*rr++) -= (*cs++);
  /* #893: @46 = dot(@29, @30) */
  w46 = casadi_dot(3, w29, w30);
  /* #894: @41 = dot(@63, @31) */
  w41 = casadi_dot(3, w63, w31);
  /* #895: @46 = (@46+@41) */
  w46 += w41;
  /* #896: @3 = (@3*@46) */
  w3 *= w46;
  /* #897: @12 = (@12+@3) */
  w12 += w3;
  /* #898: @12 = (-@12) */
  w12 = (- w12 );
  /* #899: (@55[0] += @12) */
  for (rr=w55+0, ss=(&w12); rr!=w55+1; rr+=1) *rr += *ss++;
  /* #900: @12 = dot(@36, @37) */
  w12 = casadi_dot(3, w36, w37);
  /* #901: @38 = (@38/@14) */
  for (i=0, rr=w38; i<3; ++i) (*rr++) /= w14;
  /* #902: @34 = (@34*@13) */
  for (i=0, rr=w34; i<3; ++i) (*rr++) *= w13;
  /* #903: @38 = (@38-@34) */
  for (i=0, rr=w38, cs=w34; i<3; ++i) (*rr++) -= (*cs++);
  /* #904: @38 = (-@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) *rr++ = (- *cs++ );
  /* #905: @3 = dot(@38, @22) */
  w3 = casadi_dot(3, w38, w22);
  /* #906: @12 = (@12+@3) */
  w12 += w3;
  /* #907: @50 = (@50/@2) */
  w50 /= w2;
  /* #908: @66 = (@66*@51) */
  w66 *= w51;
  /* #909: @50 = (@50-@66) */
  w50 -= w66;
  /* #910: @11 = (@11*@50) */
  w11 *= w50;
  /* #911: @16 = (@16*@46) */
  w16 *= w46;
  /* #912: @11 = (@11+@16) */
  w11 += w16;
  /* #913: @12 = (@12+@11) */
  w12 += w11;
  /* #914: @12 = (@12/@14) */
  w12 /= w14;
  /* #915: @42 = (@42*@13) */
  w42 *= w13;
  /* #916: @12 = (@12-@42) */
  w12 -= w42;
  /* #917: @28 = (@28*@12) */
  for (i=0, rr=w28; i<3; ++i) (*rr++) *= w12;
  /* #918: @1 = (@10*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w10*(*cs++));
  /* #919: @28 = (@28+@1) */
  for (i=0, rr=w28, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #920: @31 = (@31*@15) */
  for (i=0, rr=w31; i<3; ++i) (*rr++) *= w15;
  /* #921: @30 = (@9*@30) */
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w9*(*cs++));
  /* #922: @31 = (@31+@30) */
  for (i=0, rr=w31, cs=w30; i<3; ++i) (*rr++) += (*cs++);
  /* #923: @31 = (2.*@31) */
  for (i=0, rr=w31, cs=w31; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #924: @28 = (@28+@31) */
  for (i=0, rr=w28, cs=w31; i<3; ++i) (*rr++) += (*cs++);
  /* #925: (@55[1:4] += @28) */
  for (rr=w55+1, ss=w28; rr!=w55+4; rr+=1) *rr += *ss++;
  /* #926: @61 = (@0*@55) */
  for (i=0, rr=w61, cs=w55; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #927: @55 = (@17*@55) */
  for (i=0, rr=w55, cs=w55; i<4; ++i) (*rr++)  = (w17*(*cs++));
  /* #928: @61 = (@61-@55) */
  for (i=0, rr=w61, cs=w55; i<4; ++i) (*rr++) -= (*cs++);
  /* #929: {@17, @0, @9, @15} = vertsplit(@61) */
  w17 = w61[0];
  w0 = w61[1];
  w9 = w61[2];
  w15 = w61[3];
  /* #930: @10 = (@7*@15) */
  w10  = (w7*w15);
  /* #931: @12 = (@6*@9) */
  w12  = (w6*w9);
  /* #932: @10 = (@10+@12) */
  w10 += w12;
  /* #933: @12 = (@5*@0) */
  w12  = (w5*w0);
  /* #934: @10 = (@10+@12) */
  w10 += w12;
  /* #935: @12 = (@4*@17) */
  w12  = (w4*w17);
  /* #936: @10 = (@10+@12) */
  w10 += w12;
  /* #937: @12 = (@6*@15) */
  w12  = (w6*w15);
  /* #938: @42 = (@7*@9) */
  w42  = (w7*w9);
  /* #939: @12 = (@12-@42) */
  w12 -= w42;
  /* #940: @42 = (@4*@0) */
  w42  = (w4*w0);
  /* #941: @12 = (@12+@42) */
  w12 += w42;
  /* #942: @42 = (@5*@17) */
  w42  = (w5*w17);
  /* #943: @12 = (@12-@42) */
  w12 -= w42;
  /* #944: @42 = (@4*@9) */
  w42  = (w4*w9);
  /* #945: @13 = (@5*@15) */
  w13  = (w5*w15);
  /* #946: @42 = (@42-@13) */
  w42 -= w13;
  /* #947: @13 = (@7*@0) */
  w13  = (w7*w0);
  /* #948: @42 = (@42+@13) */
  w42 += w13;
  /* #949: @13 = (@6*@17) */
  w13  = (w6*w17);
  /* #950: @42 = (@42-@13) */
  w42 -= w13;
  /* #951: @4 = (@4*@15) */
  w4 *= w15;
  /* #952: @5 = (@5*@9) */
  w5 *= w9;
  /* #953: @4 = (@4+@5) */
  w4 += w5;
  /* #954: @6 = (@6*@0) */
  w6 *= w0;
  /* #955: @4 = (@4-@6) */
  w4 -= w6;
  /* #956: @7 = (@7*@17) */
  w7 *= w17;
  /* #957: @4 = (@4-@7) */
  w4 -= w7;
  /* #958: @61 = vertcat(@10, @12, @42, @4) */
  rr=w61;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w42;
  *rr++ = w4;
  /* #959: @10 = dot(@26, @61) */
  w10 = casadi_dot(4, w26, w61);
  /* #960: @60 = (@60/@8) */
  for (i=0, rr=w60; i<4; ++i) (*rr++) /= w8;
  /* #961: @27 = (@27*@18) */
  for (i=0, rr=w27; i<4; ++i) (*rr++) *= w18;
  /* #962: @60 = (@60-@27) */
  for (i=0, rr=w60, cs=w27; i<4; ++i) (*rr++) -= (*cs++);
  /* #963: @60 = (-@60) */
  for (i=0, rr=w60, cs=w60; i<4; ++i) *rr++ = (- *cs++ );
  /* #964: @12 = dot(@60, @39) */
  w12 = casadi_dot(4, w60, w39);
  /* #965: @10 = (@10+@12) */
  w10 += w12;
  /* #966: @10 = (@10/@8) */
  w10 /= w8;
  /* #967: @67 = (@67*@18) */
  w67 *= w18;
  /* #968: @10 = (@10-@67) */
  w10 -= w67;
  /* #969: @25 = (@25*@10) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) *= w10;
  /* #970: @43 = (@43*@45) */
  w43 *= w45;
  /* #971: @60 = dense(@43) */
  casadi_densify((&w43), casadi_s15, w60, 0);
  /* #972: @25 = (@25+@60) */
  for (i=0, rr=w25, cs=w60; i<4; ++i) (*rr++) += (*cs++);
  /* #973: (@21[6:10] += @25) */
  for (rr=w21+6, ss=w25; rr!=w21+10; rr+=1) *rr += *ss++;
  /* #974: {@43, @45, @10, @67, @12, @42, @4, @7, @17, @6, @0, @5, @9} = vertsplit(@21) */
  w43 = w21[0];
  w45 = w21[1];
  w10 = w21[2];
  w67 = w21[3];
  w12 = w21[4];
  w42 = w21[5];
  w4 = w21[6];
  w7 = w21[7];
  w17 = w21[8];
  w6 = w21[9];
  w0 = w21[10];
  w5 = w21[11];
  w9 = w21[12];
  /* #975: @61 = (@61/@8) */
  for (i=0, rr=w61; i<4; ++i) (*rr++) /= w8;
  /* #976: @33 = (@33*@18) */
  for (i=0, rr=w33; i<4; ++i) (*rr++) *= w18;
  /* #977: @61 = (@61-@33) */
  for (i=0, rr=w61, cs=w33; i<4; ++i) (*rr++) -= (*cs++);
  /* #978: {@18, @8, @15, @13} = vertsplit(@61) */
  w18 = w61[0];
  w8 = w61[1];
  w15 = w61[2];
  w13 = w61[3];
  /* #979: @18 = (@18+@4) */
  w18 += w4;
  /* #980: @7 = (@7-@8) */
  w7 -= w8;
  /* #981: @17 = (@17-@15) */
  w17 -= w15;
  /* #982: @6 = (@6-@13) */
  w6 -= w13;
  /* #983: @21 = vertcat(@43, @45, @10, @67, @12, @42, @18, @7, @17, @6, @0, @5, @9) */
  rr=w21;
  *rr++ = w43;
  *rr++ = w45;
  *rr++ = w10;
  *rr++ = w67;
  *rr++ = w12;
  *rr++ = w42;
  *rr++ = w18;
  *rr++ = w7;
  *rr++ = w17;
  *rr++ = w6;
  *rr++ = w0;
  *rr++ = w5;
  *rr++ = w9;
  /* #984: @61 = @21[6:10] */
  for (rr=w61, ss=w21+6; ss!=w21+10; ss+=1) *rr++ = *ss;
  /* #985: (@54[21:25] = @61) */
  for (rr=w54+21, ss=w61; rr!=w54+25; rr+=1) *rr = *ss++;
  /* #986: @61 = @21[6:10] */
  for (rr=w61, ss=w21+6; ss!=w21+10; ss+=1) *rr++ = *ss;
  /* #987: (@54[12:28:4] = @61) */
  for (rr=w54+12, ss=w61; rr!=w54+28; rr+=4) *rr = *ss++;
  /* #988: @79 = @54' */
  casadi_trans(w54,casadi_s16, w79, casadi_s16, iw);
  /* #989: output[2][0] = @79 */
  casadi_copy(w79, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s18;
    case 2: return casadi_s18;
    case 3: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    case 1: return casadi_s17;
    case 2: return casadi_s16;
    case 3: return casadi_s18;
    case 4: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 258;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
