/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s5[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[9] = {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0., 1.5968700000000000e-03};
static const casadi_real casadi_c1[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c2[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* Drone_ode_complete_expl_vde_adj:(i0[13],i1[13],i2[4],i3[17])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, w1, w2, w3, *w4=w+19, *w5=w+22, *w6=w+26, w7, w8, w9, w10, w11, w12, *w13=w+35, w14, w15, w16, *w17=w+47, w18, *w19=w+52, w20, *w21=w+57, w22, w23, *w24=w+68, *w25=w+71, *w26=w+80, *w27=w+89, *w28=w+98, *w29=w+107, w30, *w31=w+112, *w32=w+115, *w33=w+118, w34, w35, w36;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 13, w0);
  /* #1: {@1, @2, @3, @4, @5, @6} = vertsplit(@0) */
  w1 = w0[0];
  w2 = w0[1];
  w3 = w0[2];
  casadi_copy(w0+3, 3, w4);
  casadi_copy(w0+6, 4, w5);
  casadi_copy(w0+10, 3, w6);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #5: @3 = input[0][12] */
  w3 = arg[0] ? arg[0][12] : 0;
  /* #6: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #7: @5 = (@2*@5) */
  for (i=0, rr=w5, cs=w5; i<4; ++i) (*rr++)  = (w2*(*cs++));
  /* #8: {@2, @1, @7, @8} = vertsplit(@5) */
  w2 = w5[0];
  w1 = w5[1];
  w7 = w5[2];
  w8 = w5[3];
  /* #9: @9 = (@3*@8) */
  w9  = (w3*w8);
  /* #10: @10 = input[0][11] */
  w10 = arg[0] ? arg[0][11] : 0;
  /* #11: @11 = (@10*@7) */
  w11  = (w10*w7);
  /* #12: @9 = (@9+@11) */
  w9 += w11;
  /* #13: @11 = input[0][10] */
  w11 = arg[0] ? arg[0][10] : 0;
  /* #14: @12 = (@11*@1) */
  w12  = (w11*w1);
  /* #15: @9 = (@9+@12) */
  w9 += w12;
  /* #16: @5 = zeros(4x1) */
  casadi_clear(w5, 4);
  /* #17: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #18: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #19: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #20: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #21: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #22: @17 = vertcat(@12, @14, @15, @16) */
  rr=w17;
  *rr++ = w12;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #23: @18 = ||@17||_F */
  w18 = sqrt(casadi_dot(4, w17, w17));
  /* #24: @19 = (@17/@18) */
  for (i=0, rr=w19, cr=w17; i<4; ++i) (*rr++)  = ((*cr++)/w18);
  /* #25: @20 = @19[3] */
  for (rr=(&w20), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #26: @20 = (-@20) */
  w20 = (- w20 );
  /* #27: (@13[3] = @20) */
  for (rr=w13+3, ss=(&w20); rr!=w13+4; rr+=1) *rr = *ss++;
  /* #28: @20 = @19[2] */
  for (rr=(&w20), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #29: (@13[6] = @20) */
  for (rr=w13+6, ss=(&w20); rr!=w13+7; rr+=1) *rr = *ss++;
  /* #30: @20 = @19[1] */
  for (rr=(&w20), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #31: @20 = (-@20) */
  w20 = (- w20 );
  /* #32: (@13[7] = @20) */
  for (rr=w13+7, ss=(&w20); rr!=w13+8; rr+=1) *rr = *ss++;
  /* #33: @20 = @19[3] */
  for (rr=(&w20), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #34: (@13[1] = @20) */
  for (rr=w13+1, ss=(&w20); rr!=w13+2; rr+=1) *rr = *ss++;
  /* #35: @20 = @19[2] */
  for (rr=(&w20), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #36: @20 = (-@20) */
  w20 = (- w20 );
  /* #37: (@13[2] = @20) */
  for (rr=w13+2, ss=(&w20); rr!=w13+3; rr+=1) *rr = *ss++;
  /* #38: @20 = @19[1] */
  for (rr=(&w20), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #39: (@13[5] = @20) */
  for (rr=w13+5, ss=(&w20); rr!=w13+6; rr+=1) *rr = *ss++;
  /* #40: @21 = zeros(3x3) */
  casadi_clear(w21, 9);
  /* #41: @20 = 0 */
  w20 = 0.;
  /* #42: @22 = 0 */
  w22 = 0.;
  /* #43: @23 = input[2][0] */
  w23 = arg[2] ? arg[2][0] : 0;
  /* #44: @24 = vertcat(@20, @22, @23) */
  rr=w24;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w23;
  /* #45: @24 = @24' */
  /* #46: @21 = mac(@4,@24,@21) */
  for (i=0, rr=w21; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w24+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #47: @20 = dot(@13, @21) */
  w20 = casadi_dot(9, w13, w21);
  /* #48: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #49: (@5[0] += @20) */
  for (rr=w5+0, ss=(&w20); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #50: @20 = @19[0] */
  for (rr=(&w20), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #51: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #52: @25 = (@20*@21) */
  for (i=0, rr=w25, cs=w21; i<9; ++i) (*rr++)  = (w20*(*cs++));
  /* #53: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #54: @27 = (2.*@13) */
  for (i=0, rr=w27, cs=w13; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #55: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #56: @26 = mac(@28,@21,@26) */
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w21+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #57: @25 = (@25+@26) */
  for (i=0, rr=w25, cs=w26; i<9; ++i) (*rr++) += (*cs++);
  /* #58: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #59: @28 = @13' */
  for (i=0, rr=w28, cs=w13; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #60: @26 = mac(@21,@28,@26) */
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #61: @26 = (2.*@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #62: @25 = (@25+@26) */
  for (i=0, rr=w25, cs=w26; i<9; ++i) (*rr++) += (*cs++);
  /* #63: @22 = @25[5] */
  for (rr=(&w22), ss=w25+5; ss!=w25+6; ss+=1) *rr++ = *ss;
  /* #64: (@5[1] += @22) */
  for (rr=w5+1, ss=(&w22); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #65: @22 = 0 */
  w22 = 0.;
  /* #66: (@25[5] = @22) */
  for (rr=w25+5, ss=(&w22); rr!=w25+6; rr+=1) *rr = *ss++;
  /* #67: @22 = @25[2] */
  for (rr=(&w22), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #68: @22 = (-@22) */
  w22 = (- w22 );
  /* #69: (@5[2] += @22) */
  for (rr=w5+2, ss=(&w22); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #70: @22 = 0 */
  w22 = 0.;
  /* #71: (@25[2] = @22) */
  for (rr=w25+2, ss=(&w22); rr!=w25+3; rr+=1) *rr = *ss++;
  /* #72: @22 = @25[1] */
  for (rr=(&w22), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #73: (@5[3] += @22) */
  for (rr=w5+3, ss=(&w22); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #74: @22 = 0 */
  w22 = 0.;
  /* #75: (@25[1] = @22) */
  for (rr=w25+1, ss=(&w22); rr!=w25+2; rr+=1) *rr = *ss++;
  /* #76: @22 = @25[7] */
  for (rr=(&w22), ss=w25+7; ss!=w25+8; ss+=1) *rr++ = *ss;
  /* #77: @22 = (-@22) */
  w22 = (- w22 );
  /* #78: (@5[1] += @22) */
  for (rr=w5+1, ss=(&w22); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #79: @22 = 0 */
  w22 = 0.;
  /* #80: (@25[7] = @22) */
  for (rr=w25+7, ss=(&w22); rr!=w25+8; rr+=1) *rr = *ss++;
  /* #81: @22 = @25[6] */
  for (rr=(&w22), ss=w25+6; ss!=w25+7; ss+=1) *rr++ = *ss;
  /* #82: (@5[2] += @22) */
  for (rr=w5+2, ss=(&w22); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #83: @22 = 0 */
  w22 = 0.;
  /* #84: (@25[6] = @22) */
  for (rr=w25+6, ss=(&w22); rr!=w25+7; rr+=1) *rr = *ss++;
  /* #85: @22 = @25[3] */
  for (rr=(&w22), ss=w25+3; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #86: @22 = (-@22) */
  w22 = (- w22 );
  /* #87: (@5[3] += @22) */
  for (rr=w5+3, ss=(&w22); rr!=w5+4; rr+=1) *rr += *ss++;
  /* #88: @29 = (@5/@18) */
  for (i=0, rr=w29, cr=w5; i<4; ++i) (*rr++)  = ((*cr++)/w18);
  /* #89: @19 = (@19/@18) */
  for (i=0, rr=w19; i<4; ++i) (*rr++) /= w18;
  /* #90: @19 = (-@19) */
  for (i=0, rr=w19, cs=w19; i<4; ++i) *rr++ = (- *cs++ );
  /* #91: @22 = dot(@19, @5) */
  w22 = casadi_dot(4, w19, w5);
  /* #92: @22 = (@22/@18) */
  w22 /= w18;
  /* #93: @17 = (@22*@17) */
  for (i=0, rr=w17, cs=w17; i<4; ++i) (*rr++)  = (w22*(*cs++));
  /* #94: @29 = (@29+@17) */
  for (i=0, rr=w29, cs=w17; i<4; ++i) (*rr++) += (*cs++);
  /* #95: {@22, @18, @23, @30} = vertsplit(@29) */
  w22 = w29[0];
  w18 = w29[1];
  w23 = w29[2];
  w30 = w29[3];
  /* #96: @9 = (@9+@22) */
  w9 += w22;
  /* #97: output[0][3] = @9 */
  if (res[0]) res[0][3] = w9;
  /* #98: @9 = (@10*@8) */
  w9  = (w10*w8);
  /* #99: @22 = (@3*@7) */
  w22  = (w3*w7);
  /* #100: @9 = (@9-@22) */
  w9 -= w22;
  /* #101: @22 = (@11*@2) */
  w22  = (w11*w2);
  /* #102: @9 = (@9-@22) */
  w9 -= w22;
  /* #103: @9 = (@9+@18) */
  w9 += w18;
  /* #104: output[0][4] = @9 */
  if (res[0]) res[0][4] = w9;
  /* #105: @9 = (@3*@1) */
  w9  = (w3*w1);
  /* #106: @18 = (@11*@8) */
  w18  = (w11*w8);
  /* #107: @9 = (@9-@18) */
  w9 -= w18;
  /* #108: @18 = (@10*@2) */
  w18  = (w10*w2);
  /* #109: @9 = (@9-@18) */
  w9 -= w18;
  /* #110: @9 = (@9+@23) */
  w9 += w23;
  /* #111: output[0][5] = @9 */
  if (res[0]) res[0][5] = w9;
  /* #112: @9 = (@11*@7) */
  w9  = (w11*w7);
  /* #113: @23 = (@10*@1) */
  w23  = (w10*w1);
  /* #114: @9 = (@9-@23) */
  w9 -= w23;
  /* #115: @23 = (@3*@2) */
  w23  = (w3*w2);
  /* #116: @9 = (@9-@23) */
  w9 -= w23;
  /* #117: @9 = (@9+@30) */
  w9 += w30;
  /* #118: output[0][6] = @9 */
  if (res[0]) res[0][6] = w9;
  /* #119: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #120: @25 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  casadi_copy(casadi_c0, 9, w25);
  /* #121: @31 = vertcat(@11, @10, @3) */
  rr=w31;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w3;
  /* #122: @24 = mac(@25,@31,@24) */
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w25+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #123: @9 = @24[1] */
  for (rr=(&w9), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #124: @31 = zeros(3x1) */
  casadi_clear(w31, 3);
  /* #125: @32 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c1, 3, w32);
  /* #126: @33 = @32' */
  casadi_trans(w32,casadi_s0, w33, casadi_s0, iw);
  /* #127: @31 = mac(@33,@6,@31) */
  casadi_mtimes(w33, casadi_s0, w6, casadi_s1, w31, casadi_s1, w, 0);
  /* #128: @33 = (-@31) */
  for (i=0, rr=w33, cs=w31; i<3; ++i) *rr++ = (- *cs++ );
  /* #129: {@30, @23, @18} = vertsplit(@33) */
  w30 = w33[0];
  w23 = w33[1];
  w18 = w33[2];
  /* #130: @22 = (@9*@18) */
  w22  = (w9*w18);
  /* #131: @34 = @24[2] */
  for (rr=(&w34), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #132: @35 = (@34*@23) */
  w35  = (w34*w23);
  /* #133: @22 = (@22-@35) */
  w22 -= w35;
  /* #134: @33 = zeros(3x1) */
  casadi_clear(w33, 3);
  /* #135: @26 = @25' */
  for (i=0, rr=w26, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #136: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #137: @35 = (@3*@23) */
  w35  = (w3*w23);
  /* #138: @36 = (@10*@18) */
  w36  = (w10*w18);
  /* #139: @35 = (@35-@36) */
  w35 -= w36;
  /* #140: (@6[0] += @35) */
  for (rr=w6+0, ss=(&w35); rr!=w6+1; rr+=1) *rr += *ss++;
  /* #141: @35 = (@11*@18) */
  w35  = (w11*w18);
  /* #142: @3 = (@3*@30) */
  w3 *= w30;
  /* #143: @35 = (@35-@3) */
  w35 -= w3;
  /* #144: (@6[1] += @35) */
  for (rr=w6+1, ss=(&w35); rr!=w6+2; rr+=1) *rr += *ss++;
  /* #145: @10 = (@10*@30) */
  w10 *= w30;
  /* #146: @11 = (@11*@23) */
  w11 *= w23;
  /* #147: @10 = (@10-@11) */
  w10 -= w11;
  /* #148: (@6[2] += @10) */
  for (rr=w6+2, ss=(&w10); rr!=w6+3; rr+=1) *rr += *ss++;
  /* #149: @33 = mac(@26,@6,@33) */
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w26+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #150: {@10, @11, @35} = vertsplit(@33) */
  w10 = w33[0];
  w11 = w33[1];
  w35 = w33[2];
  /* #151: @22 = (@22+@10) */
  w22 += w10;
  /* #152: @10 = (@15*@8) */
  w10  = (w15*w8);
  /* #153: @22 = (@22-@10) */
  w22 -= w10;
  /* #154: @10 = (@16*@7) */
  w10  = (w16*w7);
  /* #155: @22 = (@22+@10) */
  w22 += w10;
  /* #156: @10 = (@12*@1) */
  w10  = (w12*w1);
  /* #157: @22 = (@22+@10) */
  w22 += w10;
  /* #158: @10 = (@14*@2) */
  w10  = (w14*w2);
  /* #159: @22 = (@22-@10) */
  w22 -= w10;
  /* #160: output[0][7] = @22 */
  if (res[0]) res[0][7] = w22;
  /* #161: @34 = (@34*@30) */
  w34 *= w30;
  /* #162: @22 = @24[0] */
  for (rr=(&w22), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #163: @18 = (@22*@18) */
  w18  = (w22*w18);
  /* #164: @34 = (@34-@18) */
  w34 -= w18;
  /* #165: @34 = (@34+@11) */
  w34 += w11;
  /* #166: @11 = (@14*@8) */
  w11  = (w14*w8);
  /* #167: @34 = (@34+@11) */
  w34 += w11;
  /* #168: @11 = (@12*@7) */
  w11  = (w12*w7);
  /* #169: @34 = (@34+@11) */
  w34 += w11;
  /* #170: @11 = (@16*@1) */
  w11  = (w16*w1);
  /* #171: @34 = (@34-@11) */
  w34 -= w11;
  /* #172: @11 = (@15*@2) */
  w11  = (w15*w2);
  /* #173: @34 = (@34-@11) */
  w34 -= w11;
  /* #174: output[0][8] = @34 */
  if (res[0]) res[0][8] = w34;
  /* #175: @22 = (@22*@23) */
  w22 *= w23;
  /* #176: @9 = (@9*@30) */
  w9 *= w30;
  /* #177: @22 = (@22-@9) */
  w22 -= w9;
  /* #178: @22 = (@22+@35) */
  w22 += w35;
  /* #179: @12 = (@12*@8) */
  w12 *= w8;
  /* #180: @22 = (@22+@12) */
  w22 += w12;
  /* #181: @14 = (@14*@7) */
  w14 *= w7;
  /* #182: @22 = (@22-@14) */
  w22 -= w14;
  /* #183: @15 = (@15*@1) */
  w15 *= w1;
  /* #184: @22 = (@22+@15) */
  w22 += w15;
  /* #185: @16 = (@16*@2) */
  w16 *= w2;
  /* #186: @22 = (@22-@16) */
  w22 -= w16;
  /* #187: output[0][9] = @22 */
  if (res[0]) res[0][9] = w22;
  /* #188: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #189: @26 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c2, 9, w26);
  /* #190: @25 = zeros(3x3) */
  casadi_clear(w25, 9);
  /* #191: @25 = mac(@27,@13,@25) */
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #192: @26 = (@26+@25) */
  for (i=0, rr=w26, cs=w25; i<9; ++i) (*rr++) += (*cs++);
  /* #193: @13 = (@20*@13) */
  for (i=0, rr=w13, cs=w13; i<9; ++i) (*rr++)  = (w20*(*cs++));
  /* #194: @26 = (@26+@13) */
  for (i=0, rr=w26, cs=w13; i<9; ++i) (*rr++) += (*cs++);
  /* #195: @13 = @26' */
  for (i=0, rr=w13, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #196: @24 = mac(@13,@4,@24) */
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #197: {NULL, NULL, @20} = vertsplit(@24) */
  w20 = w24[2];
  /* #198: output[0][10] = @20 */
  if (res[0]) res[0][10] = w20;
  /* #199: {@20, @22, @16} = vertsplit(@31) */
  w20 = w31[0];
  w22 = w31[1];
  w16 = w31[2];
  /* #200: output[0][11] = @20 */
  if (res[0]) res[0][11] = w20;
  /* #201: output[0][12] = @22 */
  if (res[0]) res[0][12] = w22;
  /* #202: output[0][13] = @16 */
  if (res[0]) res[0][13] = w16;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 124;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
