/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

static const casadi_real casadi_c0[16] = {-1.4692000000000001e+00, 3.8819999999999999e-01, 2.5999999999999999e-03, -2.6100000000000002e-02, 1.1340000000000000e-01, -1.2123999999999999e+00, -1.6600000000000000e-02, -3.1699999999999999e-02, -9.1130000000000000e-01, -1.0155000000000001e+00, -3.2147000000000001e+00, -5.0680000000000003e-01, 6.2329999999999997e-01, 8.7860000000000005e-01, 2.0790000000000000e-01, -5.4358000000000004e+00};
static const casadi_real casadi_c1[16] = {2.3498999999999999e+00, -2.2889999999999999e-01, 2.7000000000000001e-03, 7.7000000000000002e-03, 3.5000000000000001e-03, 1.7269000000000001e+00, 2.0299999999999999e-02, 9.4299999999999995e-02, 1.0634999999999999e+00, 6.6339999999999999e-01, 3.2273000000000001e+00, 4.5829999999999999e-01, -6.7599999999999993e-02, -7.4309999999999998e-01, -1.9850000000000001e-01, 5.2310999999999996e+00};

/* Drone_ode_expl_ode_fun:(i0[8],i1[4],i2[])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+8, *w1=w+16, *w2=w+32, w3, w4, *w5=w+50, *w6=w+82, *w7=w+114, *w8=w+146, *w9=w+210, w10, w11, w12, w13, w14, w15, *w16=w+280, *w17=w+288, *w18=w+304;
  /* #0: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #1: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #2: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #5: (@2[0] = @4) */
  for (rr=w2+0, ss=(&w4); rr!=w2+1; rr+=1) *rr = *ss++;
  /* #6: @4 = sin(@3) */
  w4 = sin( w3 );
  /* #7: @4 = (-@4) */
  w4 = (- w4 );
  /* #8: (@2[4] = @4) */
  for (rr=w2+4, ss=(&w4); rr!=w2+5; rr+=1) *rr = *ss++;
  /* #9: @4 = 0 */
  w4 = 0.;
  /* #10: (@2[8] = @4) */
  for (rr=w2+8, ss=(&w4); rr!=w2+9; rr+=1) *rr = *ss++;
  /* #11: @4 = 0 */
  w4 = 0.;
  /* #12: (@2[12] = @4) */
  for (rr=w2+12, ss=(&w4); rr!=w2+13; rr+=1) *rr = *ss++;
  /* #13: @4 = sin(@3) */
  w4 = sin( w3 );
  /* #14: (@2[1] = @4) */
  for (rr=w2+1, ss=(&w4); rr!=w2+2; rr+=1) *rr = *ss++;
  /* #15: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #16: (@2[5] = @4) */
  for (rr=w2+5, ss=(&w4); rr!=w2+6; rr+=1) *rr = *ss++;
  /* #17: @4 = 0 */
  w4 = 0.;
  /* #18: (@2[9] = @4) */
  for (rr=w2+9, ss=(&w4); rr!=w2+10; rr+=1) *rr = *ss++;
  /* #19: @4 = 0 */
  w4 = 0.;
  /* #20: (@2[13] = @4) */
  for (rr=w2+13, ss=(&w4); rr!=w2+14; rr+=1) *rr = *ss++;
  /* #21: @4 = 0 */
  w4 = 0.;
  /* #22: (@2[2] = @4) */
  for (rr=w2+2, ss=(&w4); rr!=w2+3; rr+=1) *rr = *ss++;
  /* #23: @4 = 0 */
  w4 = 0.;
  /* #24: (@2[6] = @4) */
  for (rr=w2+6, ss=(&w4); rr!=w2+7; rr+=1) *rr = *ss++;
  /* #25: @4 = 1 */
  w4 = 1.;
  /* #26: (@2[10] = @4) */
  for (rr=w2+10, ss=(&w4); rr!=w2+11; rr+=1) *rr = *ss++;
  /* #27: @4 = 0 */
  w4 = 0.;
  /* #28: (@2[14] = @4) */
  for (rr=w2+14, ss=(&w4); rr!=w2+15; rr+=1) *rr = *ss++;
  /* #29: @4 = 0 */
  w4 = 0.;
  /* #30: (@2[3] = @4) */
  for (rr=w2+3, ss=(&w4); rr!=w2+4; rr+=1) *rr = *ss++;
  /* #31: @4 = 0 */
  w4 = 0.;
  /* #32: (@2[7] = @4) */
  for (rr=w2+7, ss=(&w4); rr!=w2+8; rr+=1) *rr = *ss++;
  /* #33: @4 = 0 */
  w4 = 0.;
  /* #34: (@2[11] = @4) */
  for (rr=w2+11, ss=(&w4); rr!=w2+12; rr+=1) *rr = *ss++;
  /* #35: @4 = 1 */
  w4 = 1.;
  /* #36: (@2[15] = @4) */
  for (rr=w2+15, ss=(&w4); rr!=w2+16; rr+=1) *rr = *ss++;
  /* #37: @5 = horzcat(@1, @2) */
  rr=w5;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<16; ++i) *rr++ = *cs++;
  /* #38: @6 = @5' */
  for (i=0, rr=w6, cs=w5; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #39: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #40: @2 = 
  [[-1.4692, 0.1134, -0.9113, 0.6233], 
   [0.3882, -1.2124, -1.0155, 0.8786], 
   [0.0026, -0.0166, -3.2147, 0.2079], 
   [-0.0261, -0.0317, -0.5068, -5.4358]] */
  casadi_copy(casadi_c0, 16, w2);
  /* #41: @5 = horzcat(@1, @2) */
  rr=w5;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<16; ++i) *rr++ = *cs++;
  /* #42: @7 = @5' */
  for (i=0, rr=w7, cs=w5; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #43: @8 = horzcat(@6, @7) */
  rr=w8;
  for (i=0, cs=w6; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<32; ++i) *rr++ = *cs++;
  /* #44: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #45: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #46: @10 = input[0][1] */
  w10 = arg[0] ? arg[0][1] : 0;
  /* #47: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #48: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #49: @13 = input[0][5] */
  w13 = arg[0] ? arg[0][5] : 0;
  /* #50: @14 = input[0][6] */
  w14 = arg[0] ? arg[0][6] : 0;
  /* #51: @15 = input[0][7] */
  w15 = arg[0] ? arg[0][7] : 0;
  /* #52: @16 = vertcat(@4, @10, @11, @3, @12, @13, @14, @15) */
  rr=w16;
  *rr++ = w4;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w3;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #53: @0 = mac(@9,@16,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w16+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #54: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #55: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #56: @2 = 
  [[2.3499, 0.0035, 1.0635, -0.0676], 
   [-0.2289, 1.7269, 0.6634, -0.7431], 
   [0.0027, 0.0203, 3.2273, -0.1985], 
   [0.0077, 0.0943, 0.4583, 5.2311]] */
  casadi_copy(casadi_c1, 16, w2);
  /* #57: @17 = @2' */
  for (i=0, rr=w17, cs=w2; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #58: @6 = horzcat(@1, @17) */
  rr=w6;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<16; ++i) *rr++ = *cs++;
  /* #59: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #60: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #61: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #62: @11 = input[1][2] */
  w11 = arg[1] ? arg[1][2] : 0;
  /* #63: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #64: @18 = vertcat(@4, @10, @11, @3) */
  rr=w18;
  *rr++ = w4;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w3;
  /* #65: @16 = mac(@7,@18,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*8]**tt++;
  /* #66: @0 = (@0+@16) */
  for (i=0, rr=w0, cs=w16; i<8; ++i) (*rr++) += (*cs++);
  /* #67: output[0][0] = @0 */
  casadi_copy(w0, 8, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 308;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
