/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[23] = {8, 4, 0, 4, 8, 12, 16, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7};
static const casadi_int casadi_s1[27] = {4, 8, 0, 0, 0, 0, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[27] = {8, 8, 0, 0, 0, 0, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[27] = {8, 8, 0, 4, 8, 12, 16, 16, 16, 16, 16, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7};
static const casadi_int casadi_s4[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s6[39] = {8, 4, 0, 8, 16, 24, 32, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s10[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[3] = {0, 0, 0};

static const casadi_real casadi_c0[16] = {-1.4692000000000001e+00, 3.8819999999999999e-01, 2.5999999999999999e-03, -2.6100000000000002e-02, 1.1340000000000000e-01, -1.2123999999999999e+00, -1.6600000000000000e-02, -3.1699999999999999e-02, -9.1130000000000000e-01, -1.0155000000000001e+00, -3.2147000000000001e+00, -5.0680000000000003e-01, 6.2329999999999997e-01, 8.7860000000000005e-01, 2.0790000000000000e-01, -5.4358000000000004e+00};
static const casadi_real casadi_c1[16] = {2.3498999999999999e+00, -2.2889999999999999e-01, 2.7000000000000001e-03, 7.7000000000000002e-03, 3.5000000000000001e-03, 1.7269000000000001e+00, 2.0299999999999999e-02, 9.4299999999999995e-02, 1.0634999999999999e+00, 6.6339999999999999e-01, 3.2273000000000001e+00, 4.5829999999999999e-01, -6.7599999999999993e-02, -7.4309999999999998e-01, -1.9850000000000001e-01, 5.2310999999999996e+00};

/* Drone_ode_expl_vde_forw:(i0[8],i1[8x8],i2[8x4],i3[4],i4[])->(o0[8],o1[8x8],o2[8x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+8, *w1=w+16, *w2=w+32, w3, w4, *w5=w+50, *w6=w+82, *w7=w+114, *w8=w+146, *w9=w+210, w10, w11, w12, w13, w14, w15, *w16=w+280, *w17=w+288, *w18=w+296, *w19=w+312, *w20=w+316, *w21=w+324, *w22=w+332, *w23=w+340, *w24=w+348, *w25=w+356, *w26=w+364, *w27=w+372;
  /* #0: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #1: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #2: @2 = zeros(4x4) */
  casadi_clear(w2, 16);
  /* #3: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #5: (@2[0] = @4) */
  for (rr=w2+0, ss=(&w4); rr!=w2+1; rr+=1) *rr = *ss++;
  /* #6: @4 = sin(@3) */
  w4 = sin( w3 );
  /* #7: @4 = (-@4) */
  w4 = (- w4 );
  /* #8: (@2[4] = @4) */
  for (rr=w2+4, ss=(&w4); rr!=w2+5; rr+=1) *rr = *ss++;
  /* #9: @4 = 0 */
  w4 = 0.;
  /* #10: (@2[8] = @4) */
  for (rr=w2+8, ss=(&w4); rr!=w2+9; rr+=1) *rr = *ss++;
  /* #11: @4 = 0 */
  w4 = 0.;
  /* #12: (@2[12] = @4) */
  for (rr=w2+12, ss=(&w4); rr!=w2+13; rr+=1) *rr = *ss++;
  /* #13: @4 = sin(@3) */
  w4 = sin( w3 );
  /* #14: (@2[1] = @4) */
  for (rr=w2+1, ss=(&w4); rr!=w2+2; rr+=1) *rr = *ss++;
  /* #15: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #16: (@2[5] = @4) */
  for (rr=w2+5, ss=(&w4); rr!=w2+6; rr+=1) *rr = *ss++;
  /* #17: @4 = 0 */
  w4 = 0.;
  /* #18: (@2[9] = @4) */
  for (rr=w2+9, ss=(&w4); rr!=w2+10; rr+=1) *rr = *ss++;
  /* #19: @4 = 0 */
  w4 = 0.;
  /* #20: (@2[13] = @4) */
  for (rr=w2+13, ss=(&w4); rr!=w2+14; rr+=1) *rr = *ss++;
  /* #21: @4 = 0 */
  w4 = 0.;
  /* #22: (@2[2] = @4) */
  for (rr=w2+2, ss=(&w4); rr!=w2+3; rr+=1) *rr = *ss++;
  /* #23: @4 = 0 */
  w4 = 0.;
  /* #24: (@2[6] = @4) */
  for (rr=w2+6, ss=(&w4); rr!=w2+7; rr+=1) *rr = *ss++;
  /* #25: @4 = 1 */
  w4 = 1.;
  /* #26: (@2[10] = @4) */
  for (rr=w2+10, ss=(&w4); rr!=w2+11; rr+=1) *rr = *ss++;
  /* #27: @4 = 0 */
  w4 = 0.;
  /* #28: (@2[14] = @4) */
  for (rr=w2+14, ss=(&w4); rr!=w2+15; rr+=1) *rr = *ss++;
  /* #29: @4 = 0 */
  w4 = 0.;
  /* #30: (@2[3] = @4) */
  for (rr=w2+3, ss=(&w4); rr!=w2+4; rr+=1) *rr = *ss++;
  /* #31: @4 = 0 */
  w4 = 0.;
  /* #32: (@2[7] = @4) */
  for (rr=w2+7, ss=(&w4); rr!=w2+8; rr+=1) *rr = *ss++;
  /* #33: @4 = 0 */
  w4 = 0.;
  /* #34: (@2[11] = @4) */
  for (rr=w2+11, ss=(&w4); rr!=w2+12; rr+=1) *rr = *ss++;
  /* #35: @4 = 1 */
  w4 = 1.;
  /* #36: (@2[15] = @4) */
  for (rr=w2+15, ss=(&w4); rr!=w2+16; rr+=1) *rr = *ss++;
  /* #37: @5 = horzcat(@1, @2) */
  rr=w5;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<16; ++i) *rr++ = *cs++;
  /* #38: @6 = @5' */
  for (i=0, rr=w6, cs=w5; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #39: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #40: @2 = 
  [[-1.4692, 0.1134, -0.9113, 0.6233], 
   [0.3882, -1.2124, -1.0155, 0.8786], 
   [0.0026, -0.0166, -3.2147, 0.2079], 
   [-0.0261, -0.0317, -0.5068, -5.4358]] */
  casadi_copy(casadi_c0, 16, w2);
  /* #41: @5 = horzcat(@1, @2) */
  rr=w5;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<16; ++i) *rr++ = *cs++;
  /* #42: @7 = @5' */
  for (i=0, rr=w7, cs=w5; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #43: @8 = horzcat(@6, @7) */
  rr=w8;
  for (i=0, cs=w6; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<32; ++i) *rr++ = *cs++;
  /* #44: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #45: @4 = input[0][0] */
  w4 = arg[0] ? arg[0][0] : 0;
  /* #46: @10 = input[0][1] */
  w10 = arg[0] ? arg[0][1] : 0;
  /* #47: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #48: @12 = input[0][4] */
  w12 = arg[0] ? arg[0][4] : 0;
  /* #49: @13 = input[0][5] */
  w13 = arg[0] ? arg[0][5] : 0;
  /* #50: @14 = input[0][6] */
  w14 = arg[0] ? arg[0][6] : 0;
  /* #51: @15 = input[0][7] */
  w15 = arg[0] ? arg[0][7] : 0;
  /* #52: @16 = vertcat(@4, @10, @11, @3, @12, @13, @14, @15) */
  rr=w16;
  *rr++ = w4;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w3;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #53: @0 = mac(@9,@16,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w16+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #54: @17 = zeros(8x1) */
  casadi_clear(w17, 8);
  /* #55: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #56: @2 = 
  [[2.3499, 0.0035, 1.0635, -0.0676], 
   [-0.2289, 1.7269, 0.6634, -0.7431], 
   [0.0027, 0.0203, 3.2273, -0.1985], 
   [0.0077, 0.0943, 0.4583, 5.2311]] */
  casadi_copy(casadi_c1, 16, w2);
  /* #57: @18 = @2' */
  for (i=0, rr=w18, cs=w2; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #58: @6 = horzcat(@1, @18) */
  rr=w6;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<16; ++i) *rr++ = *cs++;
  /* #59: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #60: @4 = input[3][0] */
  w4 = arg[3] ? arg[3][0] : 0;
  /* #61: @10 = input[3][1] */
  w10 = arg[3] ? arg[3][1] : 0;
  /* #62: @11 = input[3][2] */
  w11 = arg[3] ? arg[3][2] : 0;
  /* #63: @12 = input[3][3] */
  w12 = arg[3] ? arg[3][3] : 0;
  /* #64: @19 = vertcat(@4, @10, @11, @12) */
  rr=w19;
  *rr++ = w4;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #65: @17 = mac(@7,@19,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w7+j, tt=w19+i*4; k<4; ++k) *rr += ss[k*8]**tt++;
  /* #66: @0 = (@0+@17) */
  for (i=0, rr=w0, cs=w17; i<8; ++i) (*rr++) += (*cs++);
  /* #67: output[0][0] = @0 */
  casadi_copy(w0, 8, res[0]);
  /* #68: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #69: @8 = input[1][0] */
  casadi_copy(arg[1], 64, w8);
  /* #70: {@17, @20, @21, @22, @23, @24, @25, @26} = horzsplit(@8) */
  casadi_copy(w8, 8, w17);
  casadi_copy(w8+8, 8, w20);
  casadi_copy(w8+16, 8, w21);
  casadi_copy(w8+24, 8, w22);
  casadi_copy(w8+32, 8, w23);
  casadi_copy(w8+40, 8, w24);
  casadi_copy(w8+48, 8, w25);
  casadi_copy(w8+56, 8, w26);
  /* #71: @0 = mac(@9,@17,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w17+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #72: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #73: @28 = zeros(4x4,0nz) */
  /* #74: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #75: @4 = sin(@3) */
  w4 = sin( w3 );
  /* #76: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@17) */
  w10 = w17[3];
  /* #77: @11 = (@4*@10) */
  w11  = (w4*w10);
  /* #78: @11 = (-@11) */
  w11 = (- w11 );
  /* #79: (@1[0] += @11) */
  for (rr=w1+0, ss=(&w11); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #80: @11 = 0 */
  w11 = 0.;
  /* #81: (@1[4] = @11) */
  for (rr=w1+4, ss=(&w11); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #82: @11 = cos(@3) */
  w11 = cos( w3 );
  /* #83: @12 = (@11*@10) */
  w12  = (w11*w10);
  /* #84: @12 = (-@12) */
  w12 = (- w12 );
  /* #85: (@1[4] += @12) */
  for (rr=w1+4, ss=(&w12); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #86: @12 = 0 */
  w12 = 0.;
  /* #87: (@1[8] = @12) */
  for (rr=w1+8, ss=(&w12); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #88: @12 = 0 */
  w12 = 0.;
  /* #89: (@1[12] = @12) */
  for (rr=w1+12, ss=(&w12); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #90: @12 = 0 */
  w12 = 0.;
  /* #91: (@1[1] = @12) */
  for (rr=w1+1, ss=(&w12); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #92: @12 = cos(@3) */
  w12 = cos( w3 );
  /* #93: @13 = (@12*@10) */
  w13  = (w12*w10);
  /* #94: (@1[1] += @13) */
  for (rr=w1+1, ss=(&w13); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #95: @13 = 0 */
  w13 = 0.;
  /* #96: (@1[5] = @13) */
  for (rr=w1+5, ss=(&w13); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #97: @13 = sin(@3) */
  w13 = sin( w3 );
  /* #98: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #99: @10 = (-@10) */
  w10 = (- w10 );
  /* #100: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #101: @10 = 0 */
  w10 = 0.;
  /* #102: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #103: @10 = 0 */
  w10 = 0.;
  /* #104: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #105: @10 = 0 */
  w10 = 0.;
  /* #106: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #107: @10 = 0 */
  w10 = 0.;
  /* #108: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #109: @10 = 0 */
  w10 = 0.;
  /* #110: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #111: @10 = 0 */
  w10 = 0.;
  /* #112: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #113: @10 = 0 */
  w10 = 0.;
  /* #114: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #115: @10 = 0 */
  w10 = 0.;
  /* #116: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #117: @10 = 0 */
  w10 = 0.;
  /* #118: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #119: @10 = 0 */
  w10 = 0.;
  /* #120: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #121: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #122: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #123: @28 = zeros(8x4,0nz) */
  /* #124: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #125: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #126: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #127: @0 = (@0+@27) */
  for (i=0, rr=w0, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #128: output[1][0] = @0 */
  casadi_copy(w0, 8, res[1]);
  /* #129: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #130: @0 = mac(@9,@20,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w20+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #131: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #132: @28 = zeros(4x4,0nz) */
  /* #133: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #134: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@20) */
  w10 = w20[3];
  /* #135: @14 = (@4*@10) */
  w14  = (w4*w10);
  /* #136: @14 = (-@14) */
  w14 = (- w14 );
  /* #137: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #138: @14 = 0 */
  w14 = 0.;
  /* #139: (@1[4] = @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #140: @14 = (@11*@10) */
  w14  = (w11*w10);
  /* #141: @14 = (-@14) */
  w14 = (- w14 );
  /* #142: (@1[4] += @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #143: @14 = 0 */
  w14 = 0.;
  /* #144: (@1[8] = @14) */
  for (rr=w1+8, ss=(&w14); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #145: @14 = 0 */
  w14 = 0.;
  /* #146: (@1[12] = @14) */
  for (rr=w1+12, ss=(&w14); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #147: @14 = 0 */
  w14 = 0.;
  /* #148: (@1[1] = @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #149: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #150: (@1[1] += @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #151: @14 = 0 */
  w14 = 0.;
  /* #152: (@1[5] = @14) */
  for (rr=w1+5, ss=(&w14); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #153: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #154: @10 = (-@10) */
  w10 = (- w10 );
  /* #155: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #156: @10 = 0 */
  w10 = 0.;
  /* #157: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #158: @10 = 0 */
  w10 = 0.;
  /* #159: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #160: @10 = 0 */
  w10 = 0.;
  /* #161: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #162: @10 = 0 */
  w10 = 0.;
  /* #163: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #164: @10 = 0 */
  w10 = 0.;
  /* #165: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #166: @10 = 0 */
  w10 = 0.;
  /* #167: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #168: @10 = 0 */
  w10 = 0.;
  /* #169: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #170: @10 = 0 */
  w10 = 0.;
  /* #171: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #172: @10 = 0 */
  w10 = 0.;
  /* #173: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #174: @10 = 0 */
  w10 = 0.;
  /* #175: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #176: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #177: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #178: @28 = zeros(8x4,0nz) */
  /* #179: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #180: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #181: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #182: @0 = (@0+@27) */
  for (i=0, rr=w0, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #183: output[1][1] = @0 */
  if (res[1]) casadi_copy(w0, 8, res[1]+8);
  /* #184: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #185: @0 = mac(@9,@21,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w21+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #186: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #187: @28 = zeros(4x4,0nz) */
  /* #188: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #189: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@21) */
  w10 = w21[3];
  /* #190: @14 = (@4*@10) */
  w14  = (w4*w10);
  /* #191: @14 = (-@14) */
  w14 = (- w14 );
  /* #192: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #193: @14 = 0 */
  w14 = 0.;
  /* #194: (@1[4] = @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #195: @14 = (@11*@10) */
  w14  = (w11*w10);
  /* #196: @14 = (-@14) */
  w14 = (- w14 );
  /* #197: (@1[4] += @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #198: @14 = 0 */
  w14 = 0.;
  /* #199: (@1[8] = @14) */
  for (rr=w1+8, ss=(&w14); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #200: @14 = 0 */
  w14 = 0.;
  /* #201: (@1[12] = @14) */
  for (rr=w1+12, ss=(&w14); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #202: @14 = 0 */
  w14 = 0.;
  /* #203: (@1[1] = @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #204: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #205: (@1[1] += @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #206: @14 = 0 */
  w14 = 0.;
  /* #207: (@1[5] = @14) */
  for (rr=w1+5, ss=(&w14); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #208: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #209: @10 = (-@10) */
  w10 = (- w10 );
  /* #210: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #211: @10 = 0 */
  w10 = 0.;
  /* #212: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #213: @10 = 0 */
  w10 = 0.;
  /* #214: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #215: @10 = 0 */
  w10 = 0.;
  /* #216: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #217: @10 = 0 */
  w10 = 0.;
  /* #218: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #219: @10 = 0 */
  w10 = 0.;
  /* #220: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #221: @10 = 0 */
  w10 = 0.;
  /* #222: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #223: @10 = 0 */
  w10 = 0.;
  /* #224: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #225: @10 = 0 */
  w10 = 0.;
  /* #226: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #227: @10 = 0 */
  w10 = 0.;
  /* #228: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #229: @10 = 0 */
  w10 = 0.;
  /* #230: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #231: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #232: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #233: @28 = zeros(8x4,0nz) */
  /* #234: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #235: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #236: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #237: @0 = (@0+@27) */
  for (i=0, rr=w0, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #238: output[1][2] = @0 */
  if (res[1]) casadi_copy(w0, 8, res[1]+16);
  /* #239: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #240: @0 = mac(@9,@22,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w22+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #241: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #242: @28 = zeros(4x4,0nz) */
  /* #243: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #244: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@22) */
  w10 = w22[3];
  /* #245: @14 = (@4*@10) */
  w14  = (w4*w10);
  /* #246: @14 = (-@14) */
  w14 = (- w14 );
  /* #247: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #248: @14 = 0 */
  w14 = 0.;
  /* #249: (@1[4] = @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #250: @14 = (@11*@10) */
  w14  = (w11*w10);
  /* #251: @14 = (-@14) */
  w14 = (- w14 );
  /* #252: (@1[4] += @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #253: @14 = 0 */
  w14 = 0.;
  /* #254: (@1[8] = @14) */
  for (rr=w1+8, ss=(&w14); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #255: @14 = 0 */
  w14 = 0.;
  /* #256: (@1[12] = @14) */
  for (rr=w1+12, ss=(&w14); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #257: @14 = 0 */
  w14 = 0.;
  /* #258: (@1[1] = @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #259: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #260: (@1[1] += @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #261: @14 = 0 */
  w14 = 0.;
  /* #262: (@1[5] = @14) */
  for (rr=w1+5, ss=(&w14); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #263: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #264: @10 = (-@10) */
  w10 = (- w10 );
  /* #265: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #266: @10 = 0 */
  w10 = 0.;
  /* #267: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #268: @10 = 0 */
  w10 = 0.;
  /* #269: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #270: @10 = 0 */
  w10 = 0.;
  /* #271: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #272: @10 = 0 */
  w10 = 0.;
  /* #273: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #274: @10 = 0 */
  w10 = 0.;
  /* #275: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #276: @10 = 0 */
  w10 = 0.;
  /* #277: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #278: @10 = 0 */
  w10 = 0.;
  /* #279: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #280: @10 = 0 */
  w10 = 0.;
  /* #281: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #282: @10 = 0 */
  w10 = 0.;
  /* #283: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #284: @10 = 0 */
  w10 = 0.;
  /* #285: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #286: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #287: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #288: @28 = zeros(8x4,0nz) */
  /* #289: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #290: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #291: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #292: @0 = (@0+@27) */
  for (i=0, rr=w0, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #293: output[1][3] = @0 */
  if (res[1]) casadi_copy(w0, 8, res[1]+24);
  /* #294: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #295: @0 = mac(@9,@23,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w23+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #296: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #297: @28 = zeros(4x4,0nz) */
  /* #298: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #299: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@23) */
  w10 = w23[3];
  /* #300: @14 = (@4*@10) */
  w14  = (w4*w10);
  /* #301: @14 = (-@14) */
  w14 = (- w14 );
  /* #302: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #303: @14 = 0 */
  w14 = 0.;
  /* #304: (@1[4] = @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #305: @14 = (@11*@10) */
  w14  = (w11*w10);
  /* #306: @14 = (-@14) */
  w14 = (- w14 );
  /* #307: (@1[4] += @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #308: @14 = 0 */
  w14 = 0.;
  /* #309: (@1[8] = @14) */
  for (rr=w1+8, ss=(&w14); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #310: @14 = 0 */
  w14 = 0.;
  /* #311: (@1[12] = @14) */
  for (rr=w1+12, ss=(&w14); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #312: @14 = 0 */
  w14 = 0.;
  /* #313: (@1[1] = @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #314: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #315: (@1[1] += @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #316: @14 = 0 */
  w14 = 0.;
  /* #317: (@1[5] = @14) */
  for (rr=w1+5, ss=(&w14); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #318: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #319: @10 = (-@10) */
  w10 = (- w10 );
  /* #320: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #321: @10 = 0 */
  w10 = 0.;
  /* #322: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #323: @10 = 0 */
  w10 = 0.;
  /* #324: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #325: @10 = 0 */
  w10 = 0.;
  /* #326: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #327: @10 = 0 */
  w10 = 0.;
  /* #328: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #329: @10 = 0 */
  w10 = 0.;
  /* #330: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #331: @10 = 0 */
  w10 = 0.;
  /* #332: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #333: @10 = 0 */
  w10 = 0.;
  /* #334: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #335: @10 = 0 */
  w10 = 0.;
  /* #336: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #337: @10 = 0 */
  w10 = 0.;
  /* #338: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #339: @10 = 0 */
  w10 = 0.;
  /* #340: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #341: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #342: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #343: @28 = zeros(8x4,0nz) */
  /* #344: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #345: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #346: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #347: @0 = (@0+@27) */
  for (i=0, rr=w0, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #348: output[1][4] = @0 */
  if (res[1]) casadi_copy(w0, 8, res[1]+32);
  /* #349: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #350: @0 = mac(@9,@24,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w24+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #351: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #352: @28 = zeros(4x4,0nz) */
  /* #353: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #354: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@24) */
  w10 = w24[3];
  /* #355: @14 = (@4*@10) */
  w14  = (w4*w10);
  /* #356: @14 = (-@14) */
  w14 = (- w14 );
  /* #357: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #358: @14 = 0 */
  w14 = 0.;
  /* #359: (@1[4] = @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #360: @14 = (@11*@10) */
  w14  = (w11*w10);
  /* #361: @14 = (-@14) */
  w14 = (- w14 );
  /* #362: (@1[4] += @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #363: @14 = 0 */
  w14 = 0.;
  /* #364: (@1[8] = @14) */
  for (rr=w1+8, ss=(&w14); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #365: @14 = 0 */
  w14 = 0.;
  /* #366: (@1[12] = @14) */
  for (rr=w1+12, ss=(&w14); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #367: @14 = 0 */
  w14 = 0.;
  /* #368: (@1[1] = @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #369: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #370: (@1[1] += @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #371: @14 = 0 */
  w14 = 0.;
  /* #372: (@1[5] = @14) */
  for (rr=w1+5, ss=(&w14); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #373: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #374: @10 = (-@10) */
  w10 = (- w10 );
  /* #375: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #376: @10 = 0 */
  w10 = 0.;
  /* #377: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #378: @10 = 0 */
  w10 = 0.;
  /* #379: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #380: @10 = 0 */
  w10 = 0.;
  /* #381: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #382: @10 = 0 */
  w10 = 0.;
  /* #383: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #384: @10 = 0 */
  w10 = 0.;
  /* #385: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #386: @10 = 0 */
  w10 = 0.;
  /* #387: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #388: @10 = 0 */
  w10 = 0.;
  /* #389: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #390: @10 = 0 */
  w10 = 0.;
  /* #391: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #392: @10 = 0 */
  w10 = 0.;
  /* #393: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #394: @10 = 0 */
  w10 = 0.;
  /* #395: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #396: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #397: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #398: @28 = zeros(8x4,0nz) */
  /* #399: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #400: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #401: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #402: @0 = (@0+@27) */
  for (i=0, rr=w0, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #403: output[1][5] = @0 */
  if (res[1]) casadi_copy(w0, 8, res[1]+40);
  /* #404: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #405: @0 = mac(@9,@25,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w25+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #406: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #407: @28 = zeros(4x4,0nz) */
  /* #408: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #409: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@25) */
  w10 = w25[3];
  /* #410: @14 = (@4*@10) */
  w14  = (w4*w10);
  /* #411: @14 = (-@14) */
  w14 = (- w14 );
  /* #412: (@1[0] += @14) */
  for (rr=w1+0, ss=(&w14); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #413: @14 = 0 */
  w14 = 0.;
  /* #414: (@1[4] = @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #415: @14 = (@11*@10) */
  w14  = (w11*w10);
  /* #416: @14 = (-@14) */
  w14 = (- w14 );
  /* #417: (@1[4] += @14) */
  for (rr=w1+4, ss=(&w14); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #418: @14 = 0 */
  w14 = 0.;
  /* #419: (@1[8] = @14) */
  for (rr=w1+8, ss=(&w14); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #420: @14 = 0 */
  w14 = 0.;
  /* #421: (@1[12] = @14) */
  for (rr=w1+12, ss=(&w14); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #422: @14 = 0 */
  w14 = 0.;
  /* #423: (@1[1] = @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #424: @14 = (@12*@10) */
  w14  = (w12*w10);
  /* #425: (@1[1] += @14) */
  for (rr=w1+1, ss=(&w14); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #426: @14 = 0 */
  w14 = 0.;
  /* #427: (@1[5] = @14) */
  for (rr=w1+5, ss=(&w14); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #428: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #429: @10 = (-@10) */
  w10 = (- w10 );
  /* #430: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #431: @10 = 0 */
  w10 = 0.;
  /* #432: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #433: @10 = 0 */
  w10 = 0.;
  /* #434: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #435: @10 = 0 */
  w10 = 0.;
  /* #436: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #437: @10 = 0 */
  w10 = 0.;
  /* #438: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #439: @10 = 0 */
  w10 = 0.;
  /* #440: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #441: @10 = 0 */
  w10 = 0.;
  /* #442: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #443: @10 = 0 */
  w10 = 0.;
  /* #444: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #445: @10 = 0 */
  w10 = 0.;
  /* #446: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #447: @10 = 0 */
  w10 = 0.;
  /* #448: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #449: @10 = 0 */
  w10 = 0.;
  /* #450: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #451: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #452: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #453: @28 = zeros(8x4,0nz) */
  /* #454: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #455: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #456: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #457: @0 = (@0+@27) */
  for (i=0, rr=w0, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #458: output[1][6] = @0 */
  if (res[1]) casadi_copy(w0, 8, res[1]+48);
  /* #459: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #460: @0 = mac(@9,@26,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w26+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #461: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #462: @28 = zeros(4x4,0nz) */
  /* #463: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #464: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@26) */
  w10 = w26[3];
  /* #465: @4 = (@4*@10) */
  w4 *= w10;
  /* #466: @4 = (-@4) */
  w4 = (- w4 );
  /* #467: (@1[0] += @4) */
  for (rr=w1+0, ss=(&w4); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #468: @4 = 0 */
  w4 = 0.;
  /* #469: (@1[4] = @4) */
  for (rr=w1+4, ss=(&w4); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #470: @11 = (@11*@10) */
  w11 *= w10;
  /* #471: @11 = (-@11) */
  w11 = (- w11 );
  /* #472: (@1[4] += @11) */
  for (rr=w1+4, ss=(&w11); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #473: @11 = 0 */
  w11 = 0.;
  /* #474: (@1[8] = @11) */
  for (rr=w1+8, ss=(&w11); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #475: @11 = 0 */
  w11 = 0.;
  /* #476: (@1[12] = @11) */
  for (rr=w1+12, ss=(&w11); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #477: @11 = 0 */
  w11 = 0.;
  /* #478: (@1[1] = @11) */
  for (rr=w1+1, ss=(&w11); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #479: @12 = (@12*@10) */
  w12 *= w10;
  /* #480: (@1[1] += @12) */
  for (rr=w1+1, ss=(&w12); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #481: @12 = 0 */
  w12 = 0.;
  /* #482: (@1[5] = @12) */
  for (rr=w1+5, ss=(&w12); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #483: @13 = (@13*@10) */
  w13 *= w10;
  /* #484: @13 = (-@13) */
  w13 = (- w13 );
  /* #485: (@1[5] += @13) */
  for (rr=w1+5, ss=(&w13); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #486: @13 = 0 */
  w13 = 0.;
  /* #487: (@1[9] = @13) */
  for (rr=w1+9, ss=(&w13); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #488: @13 = 0 */
  w13 = 0.;
  /* #489: (@1[13] = @13) */
  for (rr=w1+13, ss=(&w13); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #490: @13 = 0 */
  w13 = 0.;
  /* #491: (@1[2] = @13) */
  for (rr=w1+2, ss=(&w13); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #492: @13 = 0 */
  w13 = 0.;
  /* #493: (@1[6] = @13) */
  for (rr=w1+6, ss=(&w13); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #494: @13 = 0 */
  w13 = 0.;
  /* #495: (@1[10] = @13) */
  for (rr=w1+10, ss=(&w13); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #496: @13 = 0 */
  w13 = 0.;
  /* #497: (@1[14] = @13) */
  for (rr=w1+14, ss=(&w13); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #498: @13 = 0 */
  w13 = 0.;
  /* #499: (@1[3] = @13) */
  for (rr=w1+3, ss=(&w13); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #500: @13 = 0 */
  w13 = 0.;
  /* #501: (@1[7] = @13) */
  for (rr=w1+7, ss=(&w13); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #502: @13 = 0 */
  w13 = 0.;
  /* #503: (@1[11] = @13) */
  for (rr=w1+11, ss=(&w13); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #504: @13 = 0 */
  w13 = 0.;
  /* #505: (@1[15] = @13) */
  for (rr=w1+15, ss=(&w13); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #506: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #507: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #508: @28 = zeros(8x4,0nz) */
  /* #509: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #510: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #511: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #512: @0 = (@0+@27) */
  for (i=0, rr=w0, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #513: output[1][7] = @0 */
  if (res[1]) casadi_copy(w0, 8, res[1]+56);
  /* #514: @6 = zeros(4x8) */
  casadi_clear(w6, 32);
  /* #515: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #516: @13 = ones(4x1,1nz) */
  w13 = 1.;
  /* #517: {@10, NULL, NULL, NULL} = vertsplit(@13) */
  w10 = w13;
  /* #518: @28 = 00 */
  /* #519: @29 = 00 */
  /* #520: @30 = 00 */
  /* #521: @13 = vertcat(@10, @28, @29, @30) */
  rr=(&w13);
  *rr++ = w10;
  /* #522: @0 = mac(@7,@13,@0) */
  casadi_mtimes(w7, casadi_s6, (&w13), casadi_s5, w0, casadi_s4, w, 0);
  /* #523: (@6[:32:4] = @0) */
  for (rr=w6+0, ss=w0; rr!=w6+32; rr+=4) *rr = *ss++;
  /* #524: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #525: @28 = 00 */
  /* #526: @13 = ones(4x1,1nz) */
  w13 = 1.;
  /* #527: {NULL, @10, NULL, NULL} = vertsplit(@13) */
  w10 = w13;
  /* #528: @29 = 00 */
  /* #529: @30 = 00 */
  /* #530: @13 = vertcat(@28, @10, @29, @30) */
  rr=(&w13);
  *rr++ = w10;
  /* #531: @0 = mac(@7,@13,@0) */
  casadi_mtimes(w7, casadi_s6, (&w13), casadi_s7, w0, casadi_s4, w, 0);
  /* #532: (@6[1:33:4] = @0) */
  for (rr=w6+1, ss=w0; rr!=w6+33; rr+=4) *rr = *ss++;
  /* #533: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #534: @28 = 00 */
  /* #535: @29 = 00 */
  /* #536: @13 = ones(4x1,1nz) */
  w13 = 1.;
  /* #537: {NULL, NULL, @10, NULL} = vertsplit(@13) */
  w10 = w13;
  /* #538: @30 = 00 */
  /* #539: @13 = vertcat(@28, @29, @10, @30) */
  rr=(&w13);
  *rr++ = w10;
  /* #540: @0 = mac(@7,@13,@0) */
  casadi_mtimes(w7, casadi_s6, (&w13), casadi_s8, w0, casadi_s4, w, 0);
  /* #541: (@6[2:34:4] = @0) */
  for (rr=w6+2, ss=w0; rr!=w6+34; rr+=4) *rr = *ss++;
  /* #542: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #543: @28 = 00 */
  /* #544: @29 = 00 */
  /* #545: @30 = 00 */
  /* #546: @13 = ones(4x1,1nz) */
  w13 = 1.;
  /* #547: {NULL, NULL, NULL, @10} = vertsplit(@13) */
  w10 = w13;
  /* #548: @13 = vertcat(@28, @29, @30, @10) */
  rr=(&w13);
  *rr++ = w10;
  /* #549: @0 = mac(@7,@13,@0) */
  casadi_mtimes(w7, casadi_s6, (&w13), casadi_s9, w0, casadi_s4, w, 0);
  /* #550: (@6[3:35:4] = @0) */
  for (rr=w6+3, ss=w0; rr!=w6+35; rr+=4) *rr = *ss++;
  /* #551: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #552: @0 = zeros(8x1) */
  casadi_clear(w0, 8);
  /* #553: @6 = input[2][0] */
  casadi_copy(arg[2], 32, w6);
  /* #554: {@27, @26, @25, @24} = horzsplit(@6) */
  casadi_copy(w6, 8, w27);
  casadi_copy(w6+8, 8, w26);
  casadi_copy(w6+16, 8, w25);
  casadi_copy(w6+24, 8, w24);
  /* #555: @0 = mac(@9,@27,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w27+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #556: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #557: @28 = zeros(4x4,0nz) */
  /* #558: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #559: @13 = sin(@3) */
  w13 = sin( w3 );
  /* #560: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@27) */
  w10 = w27[3];
  /* #561: @12 = (@13*@10) */
  w12  = (w13*w10);
  /* #562: @12 = (-@12) */
  w12 = (- w12 );
  /* #563: (@1[0] += @12) */
  for (rr=w1+0, ss=(&w12); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #564: @12 = 0 */
  w12 = 0.;
  /* #565: (@1[4] = @12) */
  for (rr=w1+4, ss=(&w12); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #566: @12 = cos(@3) */
  w12 = cos( w3 );
  /* #567: @11 = (@12*@10) */
  w11  = (w12*w10);
  /* #568: @11 = (-@11) */
  w11 = (- w11 );
  /* #569: (@1[4] += @11) */
  for (rr=w1+4, ss=(&w11); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #570: @11 = 0 */
  w11 = 0.;
  /* #571: (@1[8] = @11) */
  for (rr=w1+8, ss=(&w11); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #572: @11 = 0 */
  w11 = 0.;
  /* #573: (@1[12] = @11) */
  for (rr=w1+12, ss=(&w11); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #574: @11 = 0 */
  w11 = 0.;
  /* #575: (@1[1] = @11) */
  for (rr=w1+1, ss=(&w11); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #576: @11 = cos(@3) */
  w11 = cos( w3 );
  /* #577: @4 = (@11*@10) */
  w4  = (w11*w10);
  /* #578: (@1[1] += @4) */
  for (rr=w1+1, ss=(&w4); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #579: @4 = 0 */
  w4 = 0.;
  /* #580: (@1[5] = @4) */
  for (rr=w1+5, ss=(&w4); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #581: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #582: @10 = (@3*@10) */
  w10  = (w3*w10);
  /* #583: @10 = (-@10) */
  w10 = (- w10 );
  /* #584: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #585: @10 = 0 */
  w10 = 0.;
  /* #586: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #587: @10 = 0 */
  w10 = 0.;
  /* #588: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #589: @10 = 0 */
  w10 = 0.;
  /* #590: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #591: @10 = 0 */
  w10 = 0.;
  /* #592: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #593: @10 = 0 */
  w10 = 0.;
  /* #594: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #595: @10 = 0 */
  w10 = 0.;
  /* #596: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #597: @10 = 0 */
  w10 = 0.;
  /* #598: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #599: @10 = 0 */
  w10 = 0.;
  /* #600: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #601: @10 = 0 */
  w10 = 0.;
  /* #602: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #603: @10 = 0 */
  w10 = 0.;
  /* #604: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #605: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #606: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #607: @28 = zeros(8x4,0nz) */
  /* #608: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #609: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #610: @23 = mac(@1,@16,@23) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w23, casadi_s4, w, 0);
  /* #611: @0 = (@0+@23) */
  for (i=0, rr=w0, cs=w23; i<8; ++i) (*rr++) += (*cs++);
  /* #612: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #613: @23 = mac(@9,@26,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w26+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #614: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #615: @28 = zeros(4x4,0nz) */
  /* #616: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #617: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@26) */
  w10 = w26[3];
  /* #618: @4 = (@13*@10) */
  w4  = (w13*w10);
  /* #619: @4 = (-@4) */
  w4 = (- w4 );
  /* #620: (@1[0] += @4) */
  for (rr=w1+0, ss=(&w4); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #621: @4 = 0 */
  w4 = 0.;
  /* #622: (@1[4] = @4) */
  for (rr=w1+4, ss=(&w4); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #623: @4 = (@12*@10) */
  w4  = (w12*w10);
  /* #624: @4 = (-@4) */
  w4 = (- w4 );
  /* #625: (@1[4] += @4) */
  for (rr=w1+4, ss=(&w4); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #626: @4 = 0 */
  w4 = 0.;
  /* #627: (@1[8] = @4) */
  for (rr=w1+8, ss=(&w4); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #628: @4 = 0 */
  w4 = 0.;
  /* #629: (@1[12] = @4) */
  for (rr=w1+12, ss=(&w4); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #630: @4 = 0 */
  w4 = 0.;
  /* #631: (@1[1] = @4) */
  for (rr=w1+1, ss=(&w4); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #632: @4 = (@11*@10) */
  w4  = (w11*w10);
  /* #633: (@1[1] += @4) */
  for (rr=w1+1, ss=(&w4); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #634: @4 = 0 */
  w4 = 0.;
  /* #635: (@1[5] = @4) */
  for (rr=w1+5, ss=(&w4); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #636: @10 = (@3*@10) */
  w10  = (w3*w10);
  /* #637: @10 = (-@10) */
  w10 = (- w10 );
  /* #638: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #639: @10 = 0 */
  w10 = 0.;
  /* #640: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #641: @10 = 0 */
  w10 = 0.;
  /* #642: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #643: @10 = 0 */
  w10 = 0.;
  /* #644: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #645: @10 = 0 */
  w10 = 0.;
  /* #646: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #647: @10 = 0 */
  w10 = 0.;
  /* #648: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #649: @10 = 0 */
  w10 = 0.;
  /* #650: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #651: @10 = 0 */
  w10 = 0.;
  /* #652: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #653: @10 = 0 */
  w10 = 0.;
  /* #654: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #655: @10 = 0 */
  w10 = 0.;
  /* #656: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #657: @10 = 0 */
  w10 = 0.;
  /* #658: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #659: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #660: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #661: @28 = zeros(8x4,0nz) */
  /* #662: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #663: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #664: @27 = mac(@1,@16,@27) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w27, casadi_s4, w, 0);
  /* #665: @23 = (@23+@27) */
  for (i=0, rr=w23, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #666: @27 = zeros(8x1) */
  casadi_clear(w27, 8);
  /* #667: @27 = mac(@9,@25,@27) */
  for (i=0, rr=w27; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w25+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #668: @26 = zeros(8x1) */
  casadi_clear(w26, 8);
  /* #669: @28 = zeros(4x4,0nz) */
  /* #670: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #671: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@25) */
  w10 = w25[3];
  /* #672: @4 = (@13*@10) */
  w4  = (w13*w10);
  /* #673: @4 = (-@4) */
  w4 = (- w4 );
  /* #674: (@1[0] += @4) */
  for (rr=w1+0, ss=(&w4); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #675: @4 = 0 */
  w4 = 0.;
  /* #676: (@1[4] = @4) */
  for (rr=w1+4, ss=(&w4); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #677: @4 = (@12*@10) */
  w4  = (w12*w10);
  /* #678: @4 = (-@4) */
  w4 = (- w4 );
  /* #679: (@1[4] += @4) */
  for (rr=w1+4, ss=(&w4); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #680: @4 = 0 */
  w4 = 0.;
  /* #681: (@1[8] = @4) */
  for (rr=w1+8, ss=(&w4); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #682: @4 = 0 */
  w4 = 0.;
  /* #683: (@1[12] = @4) */
  for (rr=w1+12, ss=(&w4); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #684: @4 = 0 */
  w4 = 0.;
  /* #685: (@1[1] = @4) */
  for (rr=w1+1, ss=(&w4); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #686: @4 = (@11*@10) */
  w4  = (w11*w10);
  /* #687: (@1[1] += @4) */
  for (rr=w1+1, ss=(&w4); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #688: @4 = 0 */
  w4 = 0.;
  /* #689: (@1[5] = @4) */
  for (rr=w1+5, ss=(&w4); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #690: @10 = (@3*@10) */
  w10  = (w3*w10);
  /* #691: @10 = (-@10) */
  w10 = (- w10 );
  /* #692: (@1[5] += @10) */
  for (rr=w1+5, ss=(&w10); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #693: @10 = 0 */
  w10 = 0.;
  /* #694: (@1[9] = @10) */
  for (rr=w1+9, ss=(&w10); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #695: @10 = 0 */
  w10 = 0.;
  /* #696: (@1[13] = @10) */
  for (rr=w1+13, ss=(&w10); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #697: @10 = 0 */
  w10 = 0.;
  /* #698: (@1[2] = @10) */
  for (rr=w1+2, ss=(&w10); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #699: @10 = 0 */
  w10 = 0.;
  /* #700: (@1[6] = @10) */
  for (rr=w1+6, ss=(&w10); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #701: @10 = 0 */
  w10 = 0.;
  /* #702: (@1[10] = @10) */
  for (rr=w1+10, ss=(&w10); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #703: @10 = 0 */
  w10 = 0.;
  /* #704: (@1[14] = @10) */
  for (rr=w1+14, ss=(&w10); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #705: @10 = 0 */
  w10 = 0.;
  /* #706: (@1[3] = @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #707: @10 = 0 */
  w10 = 0.;
  /* #708: (@1[7] = @10) */
  for (rr=w1+7, ss=(&w10); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #709: @10 = 0 */
  w10 = 0.;
  /* #710: (@1[11] = @10) */
  for (rr=w1+11, ss=(&w10); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #711: @10 = 0 */
  w10 = 0.;
  /* #712: (@1[15] = @10) */
  for (rr=w1+15, ss=(&w10); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #713: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #714: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #715: @28 = zeros(8x4,0nz) */
  /* #716: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #717: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #718: @26 = mac(@1,@16,@26) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w26, casadi_s4, w, 0);
  /* #719: @27 = (@27+@26) */
  for (i=0, rr=w27, cs=w26; i<8; ++i) (*rr++) += (*cs++);
  /* #720: @26 = zeros(8x1) */
  casadi_clear(w26, 8);
  /* #721: @26 = mac(@9,@24,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, ss=w9+j, tt=w24+i*8; k<8; ++k) *rr += ss[k*8]**tt++;
  /* #722: @25 = zeros(8x1) */
  casadi_clear(w25, 8);
  /* #723: @28 = zeros(4x4,0nz) */
  /* #724: @1 = zeros(4x4) */
  casadi_clear(w1, 16);
  /* #725: {NULL, NULL, NULL, @10, NULL, NULL, NULL, NULL} = vertsplit(@24) */
  w10 = w24[3];
  /* #726: @13 = (@13*@10) */
  w13 *= w10;
  /* #727: @13 = (-@13) */
  w13 = (- w13 );
  /* #728: (@1[0] += @13) */
  for (rr=w1+0, ss=(&w13); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #729: @13 = 0 */
  w13 = 0.;
  /* #730: (@1[4] = @13) */
  for (rr=w1+4, ss=(&w13); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #731: @12 = (@12*@10) */
  w12 *= w10;
  /* #732: @12 = (-@12) */
  w12 = (- w12 );
  /* #733: (@1[4] += @12) */
  for (rr=w1+4, ss=(&w12); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #734: @12 = 0 */
  w12 = 0.;
  /* #735: (@1[8] = @12) */
  for (rr=w1+8, ss=(&w12); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #736: @12 = 0 */
  w12 = 0.;
  /* #737: (@1[12] = @12) */
  for (rr=w1+12, ss=(&w12); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #738: @12 = 0 */
  w12 = 0.;
  /* #739: (@1[1] = @12) */
  for (rr=w1+1, ss=(&w12); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #740: @11 = (@11*@10) */
  w11 *= w10;
  /* #741: (@1[1] += @11) */
  for (rr=w1+1, ss=(&w11); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #742: @11 = 0 */
  w11 = 0.;
  /* #743: (@1[5] = @11) */
  for (rr=w1+5, ss=(&w11); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #744: @3 = (@3*@10) */
  w3 *= w10;
  /* #745: @3 = (-@3) */
  w3 = (- w3 );
  /* #746: (@1[5] += @3) */
  for (rr=w1+5, ss=(&w3); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #747: @3 = 0 */
  w3 = 0.;
  /* #748: (@1[9] = @3) */
  for (rr=w1+9, ss=(&w3); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #749: @3 = 0 */
  w3 = 0.;
  /* #750: (@1[13] = @3) */
  for (rr=w1+13, ss=(&w3); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #751: @3 = 0 */
  w3 = 0.;
  /* #752: (@1[2] = @3) */
  for (rr=w1+2, ss=(&w3); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #753: @3 = 0 */
  w3 = 0.;
  /* #754: (@1[6] = @3) */
  for (rr=w1+6, ss=(&w3); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #755: @3 = 0 */
  w3 = 0.;
  /* #756: (@1[10] = @3) */
  for (rr=w1+10, ss=(&w3); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #757: @3 = 0 */
  w3 = 0.;
  /* #758: (@1[14] = @3) */
  for (rr=w1+14, ss=(&w3); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #759: @3 = 0 */
  w3 = 0.;
  /* #760: (@1[3] = @3) */
  for (rr=w1+3, ss=(&w3); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #761: @3 = 0 */
  w3 = 0.;
  /* #762: (@1[7] = @3) */
  for (rr=w1+7, ss=(&w3); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #763: @3 = 0 */
  w3 = 0.;
  /* #764: (@1[11] = @3) */
  for (rr=w1+11, ss=(&w3); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #765: @3 = 0 */
  w3 = 0.;
  /* #766: (@1[15] = @3) */
  for (rr=w1+15, ss=(&w3); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #767: @18 = horzcat(@28, @1) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #768: @1 = @18' */
  casadi_trans(w18,casadi_s1, w1, casadi_s0, iw);
  /* #769: @28 = zeros(8x4,0nz) */
  /* #770: @18 = horzcat(@1, @28) */
  rr=w18;
  for (i=0, cs=w1; i<16; ++i) *rr++ = *cs++;
  /* #771: @1 = @18' */
  casadi_trans(w18,casadi_s3, w1, casadi_s2, iw);
  /* #772: @25 = mac(@1,@16,@25) */
  casadi_mtimes(w1, casadi_s2, w16, casadi_s4, w25, casadi_s4, w, 0);
  /* #773: @26 = (@26+@25) */
  for (i=0, rr=w26, cs=w25; i<8; ++i) (*rr++) += (*cs++);
  /* #774: @6 = horzcat(@0, @23, @27, @26) */
  rr=w6;
  for (i=0, cs=w0; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<8; ++i) *rr++ = *cs++;
  /* #775: @7 = (@7+@6) */
  for (i=0, rr=w7, cs=w6; i<32; ++i) (*rr++) += (*cs++);
  /* #776: output[2][0] = @7 */
  casadi_copy(w7, 32, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s10;
    case 2: return casadi_s6;
    case 3: return casadi_s11;
    case 4: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s10;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 380;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
