/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[15] = {1, 6, 0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[10] = {1, 6, 0, 1, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[10] = {1, 6, 0, 0, 1, 1, 1, 1, 1, 0};
static const casadi_int casadi_s4[10] = {1, 6, 0, 0, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s5[10] = {1, 6, 0, 0, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s6[10] = {1, 6, 0, 0, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s7[10] = {1, 6, 0, 0, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s8[51] = {12, 12, 0, 6, 12, 18, 24, 30, 36, 36, 36, 36, 36, 36, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s9[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s10[3] = {0, 0, 0};
static const casadi_int casadi_s11[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s12[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s13[15] = {0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_e_fun_jac_hess:(i0[12],i1[],i2[],i3[16])->(o0,o1[12],o2[12x12,36nz],o3[],o4[0x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+24, *w19=w+40, *w20=w+46, *w21=w+58, *w22=w+64, *w23=w+100, *w24=w+136, *w25=w+172;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x6) */
  casadi_clear(w1, 6);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = input[3][12] */
  w14 = arg[3] ? arg[3][12] : 0;
  /* #15: @15 = input[3][13] */
  w15 = arg[3] ? arg[3][13] : 0;
  /* #16: @16 = input[3][14] */
  w16 = arg[3] ? arg[3][14] : 0;
  /* #17: @17 = input[3][15] */
  w17 = arg[3] ? arg[3][15] : 0;
  /* #18: @18 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17) */
  rr=w18;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #19: @19 = @18[:6] */
  for (rr=w19, ss=w18+0; ss!=w18+6; ss+=1) *rr++ = *ss;
  /* #20: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #21: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #22: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #23: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #24: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #25: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #26: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #27: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #28: @10 = input[0][8] */
  w10 = arg[0] ? arg[0][8] : 0;
  /* #29: @11 = input[0][9] */
  w11 = arg[0] ? arg[0][9] : 0;
  /* #30: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #31: @13 = input[0][11] */
  w13 = arg[0] ? arg[0][11] : 0;
  /* #32: @20 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w20;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #33: @21 = @20[:6] */
  for (rr=w21, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #34: @19 = (@19-@21) */
  for (i=0, rr=w19, cs=w21; i<6; ++i) (*rr++) -= (*cs++);
  /* #35: @21 = @19' */
  casadi_copy(w19, 6, w21);
  /* #36: @22 = zeros(6x6) */
  casadi_clear(w22, 36);
  /* #37: @2 = 1 */
  w2 = 1.;
  /* #38: (@22[0] = @2) */
  for (rr=w22+0, ss=(&w2); rr!=w22+1; rr+=1) *rr = *ss++;
  /* #39: @2 = 1 */
  w2 = 1.;
  /* #40: (@22[7] = @2) */
  for (rr=w22+7, ss=(&w2); rr!=w22+8; rr+=1) *rr = *ss++;
  /* #41: @2 = 1 */
  w2 = 1.;
  /* #42: (@22[14] = @2) */
  for (rr=w22+14, ss=(&w2); rr!=w22+15; rr+=1) *rr = *ss++;
  /* #43: @2 = 0 */
  w2 = 0.;
  /* #44: (@22[21] = @2) */
  for (rr=w22+21, ss=(&w2); rr!=w22+22; rr+=1) *rr = *ss++;
  /* #45: @2 = 0 */
  w2 = 0.;
  /* #46: (@22[28] = @2) */
  for (rr=w22+28, ss=(&w2); rr!=w22+29; rr+=1) *rr = *ss++;
  /* #47: @2 = 1 */
  w2 = 1.;
  /* #48: (@22[35] = @2) */
  for (rr=w22+35, ss=(&w2); rr!=w22+36; rr+=1) *rr = *ss++;
  /* #49: @1 = mac(@21,@22,@1) */
  for (i=0, rr=w1; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #50: @0 = mac(@1,@19,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w19+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #51: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #52: @20 = zeros(12x1) */
  casadi_clear(w20, 12);
  /* #53: @1 = @1' */
  /* #54: @21 = zeros(1x6) */
  casadi_clear(w21, 6);
  /* #55: @19 = @19' */
  /* #56: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #57: @21 = mac(@19,@23,@21) */
  for (i=0, rr=w21; i<6; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w19+j, tt=w23+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #58: @21 = @21' */
  /* #59: @1 = (@1+@21) */
  for (i=0, rr=w1, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #60: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #61: (@20[:6] += @1) */
  for (rr=w20+0, ss=w1; rr!=w20+6; rr+=1) *rr += *ss++;
  /* #62: output[1][0] = @20 */
  casadi_copy(w20, 12, res[1]);
  /* #63: @24 = zeros(12x12,36nz) */
  casadi_clear(w24, 36);
  /* #64: @20 = zeros(12x1) */
  casadi_clear(w20, 12);
  /* #65: @1 = zeros(1x6) */
  casadi_clear(w1, 6);
  /* #66: @25 = ones(12x1,7nz) */
  casadi_fill(w25, 7, 1.);
  /* #67: {@0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@25) */
  w0 = w25[0];
  /* #68: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #69: @2 = (-@2) */
  w2 = (- w2 );
  /* #70: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #71: @1 = mac(@0,@22,@1) */
  casadi_mtimes((&w0), casadi_s2, w22, casadi_s1, w1, casadi_s0, w, 0);
  /* #72: @1 = @1' */
  /* #73: @21 = zeros(1x6) */
  casadi_clear(w21, 6);
  /* #74: @2 = @2' */
  /* #75: @21 = mac(@2,@23,@21) */
  casadi_mtimes((&w2), casadi_s2, w23, casadi_s1, w21, casadi_s0, w, 0);
  /* #76: @21 = @21' */
  /* #77: @1 = (@1+@21) */
  for (i=0, rr=w1, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #78: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #79: (@20[:6] += @1) */
  for (rr=w20+0, ss=w1; rr!=w20+6; rr+=1) *rr += *ss++;
  /* #80: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #81: (@24[:6] = @1) */
  for (rr=w24+0, ss=w1; rr!=w24+6; rr+=1) *rr = *ss++;
  /* #82: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #83: (@24[:36:6] = @1) */
  for (rr=w24+0, ss=w1; rr!=w24+36; rr+=6) *rr = *ss++;
  /* #84: @20 = zeros(12x1) */
  casadi_clear(w20, 12);
  /* #85: @1 = zeros(1x6) */
  casadi_clear(w1, 6);
  /* #86: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #87: {NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #88: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #89: @2 = (-@2) */
  w2 = (- w2 );
  /* #90: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #91: @1 = mac(@0,@22,@1) */
  casadi_mtimes((&w0), casadi_s3, w22, casadi_s1, w1, casadi_s0, w, 0);
  /* #92: @1 = @1' */
  /* #93: @21 = zeros(1x6) */
  casadi_clear(w21, 6);
  /* #94: @2 = @2' */
  /* #95: @21 = mac(@2,@23,@21) */
  casadi_mtimes((&w2), casadi_s3, w23, casadi_s1, w21, casadi_s0, w, 0);
  /* #96: @21 = @21' */
  /* #97: @1 = (@1+@21) */
  for (i=0, rr=w1, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #98: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #99: (@20[:6] += @1) */
  for (rr=w20+0, ss=w1; rr!=w20+6; rr+=1) *rr += *ss++;
  /* #100: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #101: (@24[6:12] = @1) */
  for (rr=w24+6, ss=w1; rr!=w24+12; rr+=1) *rr = *ss++;
  /* #102: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #103: (@24[1:37:6] = @1) */
  for (rr=w24+1, ss=w1; rr!=w24+37; rr+=6) *rr = *ss++;
  /* #104: @20 = zeros(12x1) */
  casadi_clear(w20, 12);
  /* #105: @1 = zeros(1x6) */
  casadi_clear(w1, 6);
  /* #106: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #107: {NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #108: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #109: @2 = (-@2) */
  w2 = (- w2 );
  /* #110: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #111: @1 = mac(@0,@22,@1) */
  casadi_mtimes((&w0), casadi_s4, w22, casadi_s1, w1, casadi_s0, w, 0);
  /* #112: @1 = @1' */
  /* #113: @21 = zeros(1x6) */
  casadi_clear(w21, 6);
  /* #114: @2 = @2' */
  /* #115: @21 = mac(@2,@23,@21) */
  casadi_mtimes((&w2), casadi_s4, w23, casadi_s1, w21, casadi_s0, w, 0);
  /* #116: @21 = @21' */
  /* #117: @1 = (@1+@21) */
  for (i=0, rr=w1, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #118: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #119: (@20[:6] += @1) */
  for (rr=w20+0, ss=w1; rr!=w20+6; rr+=1) *rr += *ss++;
  /* #120: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #121: (@24[12:18] = @1) */
  for (rr=w24+12, ss=w1; rr!=w24+18; rr+=1) *rr = *ss++;
  /* #122: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #123: (@24[2:38:6] = @1) */
  for (rr=w24+2, ss=w1; rr!=w24+38; rr+=6) *rr = *ss++;
  /* #124: @20 = zeros(12x1) */
  casadi_clear(w20, 12);
  /* #125: @1 = zeros(1x6) */
  casadi_clear(w1, 6);
  /* #126: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #127: {NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #128: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #129: @2 = (-@2) */
  w2 = (- w2 );
  /* #130: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #131: @1 = mac(@0,@22,@1) */
  casadi_mtimes((&w0), casadi_s5, w22, casadi_s1, w1, casadi_s0, w, 0);
  /* #132: @1 = @1' */
  /* #133: @21 = zeros(1x6) */
  casadi_clear(w21, 6);
  /* #134: @2 = @2' */
  /* #135: @21 = mac(@2,@23,@21) */
  casadi_mtimes((&w2), casadi_s5, w23, casadi_s1, w21, casadi_s0, w, 0);
  /* #136: @21 = @21' */
  /* #137: @1 = (@1+@21) */
  for (i=0, rr=w1, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #138: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #139: (@20[:6] += @1) */
  for (rr=w20+0, ss=w1; rr!=w20+6; rr+=1) *rr += *ss++;
  /* #140: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #141: (@24[18:24] = @1) */
  for (rr=w24+18, ss=w1; rr!=w24+24; rr+=1) *rr = *ss++;
  /* #142: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #143: (@24[3:39:6] = @1) */
  for (rr=w24+3, ss=w1; rr!=w24+39; rr+=6) *rr = *ss++;
  /* #144: @20 = zeros(12x1) */
  casadi_clear(w20, 12);
  /* #145: @1 = zeros(1x6) */
  casadi_clear(w1, 6);
  /* #146: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #147: {NULL, NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #148: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #149: @2 = (-@2) */
  w2 = (- w2 );
  /* #150: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #151: @1 = mac(@0,@22,@1) */
  casadi_mtimes((&w0), casadi_s6, w22, casadi_s1, w1, casadi_s0, w, 0);
  /* #152: @1 = @1' */
  /* #153: @21 = zeros(1x6) */
  casadi_clear(w21, 6);
  /* #154: @2 = @2' */
  /* #155: @21 = mac(@2,@23,@21) */
  casadi_mtimes((&w2), casadi_s6, w23, casadi_s1, w21, casadi_s0, w, 0);
  /* #156: @21 = @21' */
  /* #157: @1 = (@1+@21) */
  for (i=0, rr=w1, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #158: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #159: (@20[:6] += @1) */
  for (rr=w20+0, ss=w1; rr!=w20+6; rr+=1) *rr += *ss++;
  /* #160: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #161: (@24[24:30] = @1) */
  for (rr=w24+24, ss=w1; rr!=w24+30; rr+=1) *rr = *ss++;
  /* #162: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #163: (@24[4:40:6] = @1) */
  for (rr=w24+4, ss=w1; rr!=w24+40; rr+=6) *rr = *ss++;
  /* #164: @20 = zeros(12x1) */
  casadi_clear(w20, 12);
  /* #165: @1 = zeros(1x6) */
  casadi_clear(w1, 6);
  /* #166: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #167: {NULL, NULL, NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w0 = w2;
  /* #168: @2 = @0[0] */
  for (rr=(&w2), ss=(&w0)+0; ss!=(&w0)+1; ss+=1) *rr++ = *ss;
  /* #169: @2 = (-@2) */
  w2 = (- w2 );
  /* #170: @0 = @2' */
  casadi_copy((&w2), 1, (&w0));
  /* #171: @1 = mac(@0,@22,@1) */
  casadi_mtimes((&w0), casadi_s7, w22, casadi_s1, w1, casadi_s0, w, 0);
  /* #172: @1 = @1' */
  /* #173: @21 = zeros(1x6) */
  casadi_clear(w21, 6);
  /* #174: @2 = @2' */
  /* #175: @21 = mac(@2,@23,@21) */
  casadi_mtimes((&w2), casadi_s7, w23, casadi_s1, w21, casadi_s0, w, 0);
  /* #176: @21 = @21' */
  /* #177: @1 = (@1+@21) */
  for (i=0, rr=w1, cs=w21; i<6; ++i) (*rr++) += (*cs++);
  /* #178: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<6; ++i) *rr++ = (- *cs++ );
  /* #179: (@20[:6] += @1) */
  for (rr=w20+0, ss=w1; rr!=w20+6; rr+=1) *rr += *ss++;
  /* #180: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #181: (@24[30:36] = @1) */
  for (rr=w24+30, ss=w1; rr!=w24+36; rr+=1) *rr = *ss++;
  /* #182: @1 = @20[:6] */
  for (rr=w1, ss=w20+0; ss!=w20+6; ss+=1) *rr++ = *ss;
  /* #183: (@24[5:41:6] = @1) */
  for (rr=w24+5, ss=w1; rr!=w24+41; rr+=6) *rr = *ss++;
  /* #184: @23 = @24' */
  casadi_trans(w24,casadi_s8, w23, casadi_s8, iw);
  /* #185: output[2][0] = @23 */
  casadi_copy(w23, 36, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s10;
    case 3: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    case 1: return casadi_s9;
    case 2: return casadi_s8;
    case 3: return casadi_s10;
    case 4: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 179;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
